<?php
/**
 * GetRevdokuStatus200ResponseDataConnection
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Revdoku\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Revdoku\Api\Model;

use \ArrayAccess;
use \Revdoku\Api\ObjectSerializer;

/**
 * GetRevdokuStatus200ResponseDataConnection Class Doc Comment
 *
 * @category Class
 * @package  Revdoku\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetRevdokuStatus200ResponseDataConnection implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'getRevdokuStatus_200_response_data_connection';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'api_key_id' => 'string',
        'label' => 'string',
        'token_type' => 'string',
        'scope' => 'string',
        'expires_at' => '\DateTime',
        'last_used_at' => '\DateTime',
        'mailbox_access' => 'string',
        'mailbox_ids' => 'string[]',
        'denied_mailbox_ids' => 'string[]',
        'mailbox_permissions' => 'array<string,string>',
        'permissions' => 'array<string,bool>',
        'agent' => 'array<string,mixed>',
        'transport' => 'string',
        'renewal' => '\Revdoku\Api\Model\GetRevdokuStatus200ResponseDataConnectionRenewal'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'api_key_id' => null,
        'label' => null,
        'token_type' => null,
        'scope' => null,
        'expires_at' => 'date-time',
        'last_used_at' => 'date-time',
        'mailbox_access' => null,
        'mailbox_ids' => null,
        'denied_mailbox_ids' => null,
        'mailbox_permissions' => null,
        'permissions' => null,
        'agent' => null,
        'transport' => null,
        'renewal' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'api_key_id' => true,
        'label' => true,
        'token_type' => true,
        'scope' => true,
        'expires_at' => true,
        'last_used_at' => true,
        'mailbox_access' => true,
        'mailbox_ids' => false,
        'denied_mailbox_ids' => false,
        'mailbox_permissions' => false,
        'permissions' => false,
        'agent' => true,
        'transport' => true,
        'renewal' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'api_key_id' => 'api_key_id',
        'label' => 'label',
        'token_type' => 'token_type',
        'scope' => 'scope',
        'expires_at' => 'expires_at',
        'last_used_at' => 'last_used_at',
        'mailbox_access' => 'mailbox_access',
        'mailbox_ids' => 'mailbox_ids',
        'denied_mailbox_ids' => 'denied_mailbox_ids',
        'mailbox_permissions' => 'mailbox_permissions',
        'permissions' => 'permissions',
        'agent' => 'agent',
        'transport' => 'transport',
        'renewal' => 'renewal'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'api_key_id' => 'setApiKeyId',
        'label' => 'setLabel',
        'token_type' => 'setTokenType',
        'scope' => 'setScope',
        'expires_at' => 'setExpiresAt',
        'last_used_at' => 'setLastUsedAt',
        'mailbox_access' => 'setMailboxAccess',
        'mailbox_ids' => 'setMailboxIds',
        'denied_mailbox_ids' => 'setDeniedMailboxIds',
        'mailbox_permissions' => 'setMailboxPermissions',
        'permissions' => 'setPermissions',
        'agent' => 'setAgent',
        'transport' => 'setTransport',
        'renewal' => 'setRenewal'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'api_key_id' => 'getApiKeyId',
        'label' => 'getLabel',
        'token_type' => 'getTokenType',
        'scope' => 'getScope',
        'expires_at' => 'getExpiresAt',
        'last_used_at' => 'getLastUsedAt',
        'mailbox_access' => 'getMailboxAccess',
        'mailbox_ids' => 'getMailboxIds',
        'denied_mailbox_ids' => 'getDeniedMailboxIds',
        'mailbox_permissions' => 'getMailboxPermissions',
        'permissions' => 'getPermissions',
        'agent' => 'getAgent',
        'transport' => 'getTransport',
        'renewal' => 'getRenewal'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('api_key_id', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('token_type', $data ?? [], null);
        $this->setIfExists('scope', $data ?? [], null);
        $this->setIfExists('expires_at', $data ?? [], null);
        $this->setIfExists('last_used_at', $data ?? [], null);
        $this->setIfExists('mailbox_access', $data ?? [], null);
        $this->setIfExists('mailbox_ids', $data ?? [], null);
        $this->setIfExists('denied_mailbox_ids', $data ?? [], null);
        $this->setIfExists('mailbox_permissions', $data ?? [], null);
        $this->setIfExists('permissions', $data ?? [], null);
        $this->setIfExists('agent', $data ?? [], null);
        $this->setIfExists('transport', $data ?? [], null);
        $this->setIfExists('renewal', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets api_key_id
     *
     * @return string|null
     */
    public function getApiKeyId()
    {
        return $this->container['api_key_id'];
    }

    /**
     * Sets api_key_id
     *
     * @param string|null $api_key_id api_key_id
     *
     * @return self
     */
    public function setApiKeyId($api_key_id)
    {
        if (is_null($api_key_id)) {
            array_push($this->openAPINullablesSetToNull, 'api_key_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_key_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_key_id'] = $api_key_id;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            array_push($this->openAPINullablesSetToNull, 'label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets token_type
     *
     * @return string|null
     */
    public function getTokenType()
    {
        return $this->container['token_type'];
    }

    /**
     * Sets token_type
     *
     * @param string|null $token_type token_type
     *
     * @return self
     */
    public function setTokenType($token_type)
    {
        if (is_null($token_type)) {
            array_push($this->openAPINullablesSetToNull, 'token_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('token_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['token_type'] = $token_type;

        return $this;
    }

    /**
     * Gets scope
     *
     * @return string|null
     */
    public function getScope()
    {
        return $this->container['scope'];
    }

    /**
     * Sets scope
     *
     * @param string|null $scope scope
     *
     * @return self
     */
    public function setScope($scope)
    {
        if (is_null($scope)) {
            array_push($this->openAPINullablesSetToNull, 'scope');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('scope', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['scope'] = $scope;

        return $this;
    }

    /**
     * Gets expires_at
     *
     * @return \DateTime|null
     */
    public function getExpiresAt()
    {
        return $this->container['expires_at'];
    }

    /**
     * Sets expires_at
     *
     * @param \DateTime|null $expires_at expires_at
     *
     * @return self
     */
    public function setExpiresAt($expires_at)
    {
        if (is_null($expires_at)) {
            array_push($this->openAPINullablesSetToNull, 'expires_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('expires_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['expires_at'] = $expires_at;

        return $this;
    }

    /**
     * Gets last_used_at
     *
     * @return \DateTime|null
     */
    public function getLastUsedAt()
    {
        return $this->container['last_used_at'];
    }

    /**
     * Sets last_used_at
     *
     * @param \DateTime|null $last_used_at last_used_at
     *
     * @return self
     */
    public function setLastUsedAt($last_used_at)
    {
        if (is_null($last_used_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_used_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_used_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_used_at'] = $last_used_at;

        return $this;
    }

    /**
     * Gets mailbox_access
     *
     * @return string|null
     */
    public function getMailboxAccess()
    {
        return $this->container['mailbox_access'];
    }

    /**
     * Sets mailbox_access
     *
     * @param string|null $mailbox_access mailbox_access
     *
     * @return self
     */
    public function setMailboxAccess($mailbox_access)
    {
        if (is_null($mailbox_access)) {
            array_push($this->openAPINullablesSetToNull, 'mailbox_access');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('mailbox_access', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['mailbox_access'] = $mailbox_access;

        return $this;
    }

    /**
     * Gets mailbox_ids
     *
     * @return string[]|null
     */
    public function getMailboxIds()
    {
        return $this->container['mailbox_ids'];
    }

    /**
     * Sets mailbox_ids
     *
     * @param string[]|null $mailbox_ids mailbox_ids
     *
     * @return self
     */
    public function setMailboxIds($mailbox_ids)
    {
        if (is_null($mailbox_ids)) {
            throw new \InvalidArgumentException('non-nullable mailbox_ids cannot be null');
        }
        $this->container['mailbox_ids'] = $mailbox_ids;

        return $this;
    }

    /**
     * Gets denied_mailbox_ids
     *
     * @return string[]|null
     */
    public function getDeniedMailboxIds()
    {
        return $this->container['denied_mailbox_ids'];
    }

    /**
     * Sets denied_mailbox_ids
     *
     * @param string[]|null $denied_mailbox_ids denied_mailbox_ids
     *
     * @return self
     */
    public function setDeniedMailboxIds($denied_mailbox_ids)
    {
        if (is_null($denied_mailbox_ids)) {
            throw new \InvalidArgumentException('non-nullable denied_mailbox_ids cannot be null');
        }
        $this->container['denied_mailbox_ids'] = $denied_mailbox_ids;

        return $this;
    }

    /**
     * Gets mailbox_permissions
     *
     * @return array<string,string>|null
     */
    public function getMailboxPermissions()
    {
        return $this->container['mailbox_permissions'];
    }

    /**
     * Sets mailbox_permissions
     *
     * @param array<string,string>|null $mailbox_permissions mailbox_permissions
     *
     * @return self
     */
    public function setMailboxPermissions($mailbox_permissions)
    {
        if (is_null($mailbox_permissions)) {
            throw new \InvalidArgumentException('non-nullable mailbox_permissions cannot be null');
        }
        $this->container['mailbox_permissions'] = $mailbox_permissions;

        return $this;
    }

    /**
     * Gets permissions
     *
     * @return array<string,bool>|null
     */
    public function getPermissions()
    {
        return $this->container['permissions'];
    }

    /**
     * Sets permissions
     *
     * @param array<string,bool>|null $permissions permissions
     *
     * @return self
     */
    public function setPermissions($permissions)
    {
        if (is_null($permissions)) {
            throw new \InvalidArgumentException('non-nullable permissions cannot be null');
        }
        $this->container['permissions'] = $permissions;

        return $this;
    }

    /**
     * Gets agent
     *
     * @return array<string,mixed>|null
     */
    public function getAgent()
    {
        return $this->container['agent'];
    }

    /**
     * Sets agent
     *
     * @param array<string,mixed>|null $agent agent
     *
     * @return self
     */
    public function setAgent($agent)
    {
        if (is_null($agent)) {
            array_push($this->openAPINullablesSetToNull, 'agent');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('agent', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['agent'] = $agent;

        return $this;
    }

    /**
     * Gets transport
     *
     * @return string|null
     */
    public function getTransport()
    {
        return $this->container['transport'];
    }

    /**
     * Sets transport
     *
     * @param string|null $transport transport
     *
     * @return self
     */
    public function setTransport($transport)
    {
        if (is_null($transport)) {
            array_push($this->openAPINullablesSetToNull, 'transport');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('transport', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['transport'] = $transport;

        return $this;
    }

    /**
     * Gets renewal
     *
     * @return \Revdoku\Api\Model\GetRevdokuStatus200ResponseDataConnectionRenewal|null
     */
    public function getRenewal()
    {
        return $this->container['renewal'];
    }

    /**
     * Sets renewal
     *
     * @param \Revdoku\Api\Model\GetRevdokuStatus200ResponseDataConnectionRenewal|null $renewal renewal
     *
     * @return self
     */
    public function setRenewal($renewal)
    {
        if (is_null($renewal)) {
            throw new \InvalidArgumentException('non-nullable renewal cannot be null');
        }
        $this->container['renewal'] = $renewal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


