<?php
/**
 * PreparedFileUpload
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Revdoku\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Revdoku\Api\Model;

use \ArrayAccess;
use \Revdoku\Api\ObjectSerializer;

/**
 * PreparedFileUpload Class Doc Comment
 *
 * @category Class
 * @description A new upload returns signed_id and direct_upload. Identical content returns skipped&#x3D;true, duplicate&#x3D;true, file and version without a storage upload.
 * @package  Revdoku\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PreparedFileUpload implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'PreparedFileUpload';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'signed_id' => 'string',
        'filename' => 'string',
        'byte_size' => 'int',
        'checksum' => 'string',
        'content_type' => 'string',
        'service_name' => 'string',
        'direct_upload' => '\Revdoku\Api\Model\StorageUpload',
        'file' => '\Revdoku\Api\Model\MailboxFile',
        'version' => '\Revdoku\Api\Model\FileVersion',
        'skipped' => 'bool',
        'duplicate' => 'bool',
        'reason' => 'string',
        'details' => 'array<string,mixed>'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'signed_id' => null,
        'filename' => null,
        'byte_size' => 'int64',
        'checksum' => null,
        'content_type' => null,
        'service_name' => null,
        'direct_upload' => null,
        'file' => null,
        'version' => null,
        'skipped' => null,
        'duplicate' => null,
        'reason' => null,
        'details' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'signed_id' => false,
        'filename' => false,
        'byte_size' => false,
        'checksum' => false,
        'content_type' => false,
        'service_name' => false,
        'direct_upload' => false,
        'file' => false,
        'version' => false,
        'skipped' => false,
        'duplicate' => false,
        'reason' => false,
        'details' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'signed_id' => 'signed_id',
        'filename' => 'filename',
        'byte_size' => 'byte_size',
        'checksum' => 'checksum',
        'content_type' => 'content_type',
        'service_name' => 'service_name',
        'direct_upload' => 'direct_upload',
        'file' => 'file',
        'version' => 'version',
        'skipped' => 'skipped',
        'duplicate' => 'duplicate',
        'reason' => 'reason',
        'details' => 'details'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'signed_id' => 'setSignedId',
        'filename' => 'setFilename',
        'byte_size' => 'setByteSize',
        'checksum' => 'setChecksum',
        'content_type' => 'setContentType',
        'service_name' => 'setServiceName',
        'direct_upload' => 'setDirectUpload',
        'file' => 'setFile',
        'version' => 'setVersion',
        'skipped' => 'setSkipped',
        'duplicate' => 'setDuplicate',
        'reason' => 'setReason',
        'details' => 'setDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'signed_id' => 'getSignedId',
        'filename' => 'getFilename',
        'byte_size' => 'getByteSize',
        'checksum' => 'getChecksum',
        'content_type' => 'getContentType',
        'service_name' => 'getServiceName',
        'direct_upload' => 'getDirectUpload',
        'file' => 'getFile',
        'version' => 'getVersion',
        'skipped' => 'getSkipped',
        'duplicate' => 'getDuplicate',
        'reason' => 'getReason',
        'details' => 'getDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('signed_id', $data ?? [], null);
        $this->setIfExists('filename', $data ?? [], null);
        $this->setIfExists('byte_size', $data ?? [], null);
        $this->setIfExists('checksum', $data ?? [], null);
        $this->setIfExists('content_type', $data ?? [], null);
        $this->setIfExists('service_name', $data ?? [], null);
        $this->setIfExists('direct_upload', $data ?? [], null);
        $this->setIfExists('file', $data ?? [], null);
        $this->setIfExists('version', $data ?? [], null);
        $this->setIfExists('skipped', $data ?? [], null);
        $this->setIfExists('duplicate', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('details', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets signed_id
     *
     * @return string|null
     */
    public function getSignedId()
    {
        return $this->container['signed_id'];
    }

    /**
     * Sets signed_id
     *
     * @param string|null $signed_id signed_id
     *
     * @return self
     */
    public function setSignedId($signed_id)
    {
        if (is_null($signed_id)) {
            throw new \InvalidArgumentException('non-nullable signed_id cannot be null');
        }
        $this->container['signed_id'] = $signed_id;

        return $this;
    }

    /**
     * Gets filename
     *
     * @return string|null
     */
    public function getFilename()
    {
        return $this->container['filename'];
    }

    /**
     * Sets filename
     *
     * @param string|null $filename filename
     *
     * @return self
     */
    public function setFilename($filename)
    {
        if (is_null($filename)) {
            throw new \InvalidArgumentException('non-nullable filename cannot be null');
        }
        $this->container['filename'] = $filename;

        return $this;
    }

    /**
     * Gets byte_size
     *
     * @return int|null
     */
    public function getByteSize()
    {
        return $this->container['byte_size'];
    }

    /**
     * Sets byte_size
     *
     * @param int|null $byte_size byte_size
     *
     * @return self
     */
    public function setByteSize($byte_size)
    {
        if (is_null($byte_size)) {
            throw new \InvalidArgumentException('non-nullable byte_size cannot be null');
        }
        $this->container['byte_size'] = $byte_size;

        return $this;
    }

    /**
     * Gets checksum
     *
     * @return string|null
     */
    public function getChecksum()
    {
        return $this->container['checksum'];
    }

    /**
     * Sets checksum
     *
     * @param string|null $checksum checksum
     *
     * @return self
     */
    public function setChecksum($checksum)
    {
        if (is_null($checksum)) {
            throw new \InvalidArgumentException('non-nullable checksum cannot be null');
        }
        $this->container['checksum'] = $checksum;

        return $this;
    }

    /**
     * Gets content_type
     *
     * @return string|null
     */
    public function getContentType()
    {
        return $this->container['content_type'];
    }

    /**
     * Sets content_type
     *
     * @param string|null $content_type content_type
     *
     * @return self
     */
    public function setContentType($content_type)
    {
        if (is_null($content_type)) {
            throw new \InvalidArgumentException('non-nullable content_type cannot be null');
        }
        $this->container['content_type'] = $content_type;

        return $this;
    }

    /**
     * Gets service_name
     *
     * @return string|null
     */
    public function getServiceName()
    {
        return $this->container['service_name'];
    }

    /**
     * Sets service_name
     *
     * @param string|null $service_name service_name
     *
     * @return self
     */
    public function setServiceName($service_name)
    {
        if (is_null($service_name)) {
            throw new \InvalidArgumentException('non-nullable service_name cannot be null');
        }
        $this->container['service_name'] = $service_name;

        return $this;
    }

    /**
     * Gets direct_upload
     *
     * @return \Revdoku\Api\Model\StorageUpload|null
     */
    public function getDirectUpload()
    {
        return $this->container['direct_upload'];
    }

    /**
     * Sets direct_upload
     *
     * @param \Revdoku\Api\Model\StorageUpload|null $direct_upload direct_upload
     *
     * @return self
     */
    public function setDirectUpload($direct_upload)
    {
        if (is_null($direct_upload)) {
            throw new \InvalidArgumentException('non-nullable direct_upload cannot be null');
        }
        $this->container['direct_upload'] = $direct_upload;

        return $this;
    }

    /**
     * Gets file
     *
     * @return \Revdoku\Api\Model\MailboxFile|null
     */
    public function getFile()
    {
        return $this->container['file'];
    }

    /**
     * Sets file
     *
     * @param \Revdoku\Api\Model\MailboxFile|null $file file
     *
     * @return self
     */
    public function setFile($file)
    {
        if (is_null($file)) {
            throw new \InvalidArgumentException('non-nullable file cannot be null');
        }
        $this->container['file'] = $file;

        return $this;
    }

    /**
     * Gets version
     *
     * @return \Revdoku\Api\Model\FileVersion|null
     */
    public function getVersion()
    {
        return $this->container['version'];
    }

    /**
     * Sets version
     *
     * @param \Revdoku\Api\Model\FileVersion|null $version version
     *
     * @return self
     */
    public function setVersion($version)
    {
        if (is_null($version)) {
            throw new \InvalidArgumentException('non-nullable version cannot be null');
        }
        $this->container['version'] = $version;

        return $this;
    }

    /**
     * Gets skipped
     *
     * @return bool|null
     */
    public function getSkipped()
    {
        return $this->container['skipped'];
    }

    /**
     * Sets skipped
     *
     * @param bool|null $skipped skipped
     *
     * @return self
     */
    public function setSkipped($skipped)
    {
        if (is_null($skipped)) {
            throw new \InvalidArgumentException('non-nullable skipped cannot be null');
        }
        $this->container['skipped'] = $skipped;

        return $this;
    }

    /**
     * Gets duplicate
     *
     * @return bool|null
     */
    public function getDuplicate()
    {
        return $this->container['duplicate'];
    }

    /**
     * Sets duplicate
     *
     * @param bool|null $duplicate duplicate
     *
     * @return self
     */
    public function setDuplicate($duplicate)
    {
        if (is_null($duplicate)) {
            throw new \InvalidArgumentException('non-nullable duplicate cannot be null');
        }
        $this->container['duplicate'] = $duplicate;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return string|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param string|null $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets details
     *
     * @return array<string,mixed>|null
     */
    public function getDetails()
    {
        return $this->container['details'];
    }

    /**
     * Sets details
     *
     * @param array<string,mixed>|null $details details
     *
     * @return self
     */
    public function setDetails($details)
    {
        if (is_null($details)) {
            throw new \InvalidArgumentException('non-nullable details cannot be null');
        }
        $this->container['details'] = $details;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


