/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.535
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the ListAccounts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAccounts200Response{}

// ListAccounts200Response struct for ListAccounts200Response
type ListAccounts200Response struct {
	Success bool `json:"success"`
	Data ListAccounts200ResponseData `json:"data"`
	AdditionalProperties map[string]interface{}
}

type _ListAccounts200Response ListAccounts200Response

// NewListAccounts200Response instantiates a new ListAccounts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAccounts200Response(success bool, data ListAccounts200ResponseData) *ListAccounts200Response {
	this := ListAccounts200Response{}
	this.Success = success
	this.Data = data
	return &this
}

// NewListAccounts200ResponseWithDefaults instantiates a new ListAccounts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAccounts200ResponseWithDefaults() *ListAccounts200Response {
	this := ListAccounts200Response{}
	return &this
}

// GetSuccess returns the Success field value
func (o *ListAccounts200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *ListAccounts200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *ListAccounts200Response) SetSuccess(v bool) {
	o.Success = v
}

// GetData returns the Data field value
func (o *ListAccounts200Response) GetData() ListAccounts200ResponseData {
	if o == nil {
		var ret ListAccounts200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListAccounts200Response) GetDataOk() (*ListAccounts200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *ListAccounts200Response) SetData(v ListAccounts200ResponseData) {
	o.Data = v
}

func (o ListAccounts200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAccounts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["success"] = o.Success
	toSerialize["data"] = o.Data

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAccounts200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"success",
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAccounts200Response := _ListAccounts200Response{}

	err = json.Unmarshal(data, &varListAccounts200Response)

	if err != nil {
		return err
	}

	*o = ListAccounts200Response(varListAccounts200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "success")
		delete(additionalProperties, "data")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAccounts200Response struct {
	value *ListAccounts200Response
	isSet bool
}

func (v NullableListAccounts200Response) Get() *ListAccounts200Response {
	return v.value
}

func (v *NullableListAccounts200Response) Set(val *ListAccounts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListAccounts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListAccounts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAccounts200Response(val *ListAccounts200Response) *NullableListAccounts200Response {
	return &NullableListAccounts200Response{value: val, isSet: true}
}

func (v NullableListAccounts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAccounts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


