/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.526
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
)

// checks if the GetRevdokuStatus200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevdokuStatus200ResponseData{}

// GetRevdokuStatus200ResponseData struct for GetRevdokuStatus200ResponseData
type GetRevdokuStatus200ResponseData struct {
	Account *AccountIdentity `json:"account,omitempty"`
	DefaultAccountId NullableString `json:"default_account_id,omitempty"`
	Accounts []AccountIdentity `json:"accounts,omitempty"`
	Features map[string]interface{} `json:"features,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetRevdokuStatus200ResponseData GetRevdokuStatus200ResponseData

// NewGetRevdokuStatus200ResponseData instantiates a new GetRevdokuStatus200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevdokuStatus200ResponseData() *GetRevdokuStatus200ResponseData {
	this := GetRevdokuStatus200ResponseData{}
	return &this
}

// NewGetRevdokuStatus200ResponseDataWithDefaults instantiates a new GetRevdokuStatus200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevdokuStatus200ResponseDataWithDefaults() *GetRevdokuStatus200ResponseData {
	this := GetRevdokuStatus200ResponseData{}
	return &this
}

// GetAccount returns the Account field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseData) GetAccount() AccountIdentity {
	if o == nil || IsNil(o.Account) {
		var ret AccountIdentity
		return ret
	}
	return *o.Account
}

// GetAccountOk returns a tuple with the Account field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseData) GetAccountOk() (*AccountIdentity, bool) {
	if o == nil || IsNil(o.Account) {
		return nil, false
	}
	return o.Account, true
}

// HasAccount returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseData) HasAccount() bool {
	if o != nil && !IsNil(o.Account) {
		return true
	}

	return false
}

// SetAccount gets a reference to the given AccountIdentity and assigns it to the Account field.
func (o *GetRevdokuStatus200ResponseData) SetAccount(v AccountIdentity) {
	o.Account = &v
}

// GetDefaultAccountId returns the DefaultAccountId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseData) GetDefaultAccountId() string {
	if o == nil || IsNil(o.DefaultAccountId.Get()) {
		var ret string
		return ret
	}
	return *o.DefaultAccountId.Get()
}

// GetDefaultAccountIdOk returns a tuple with the DefaultAccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseData) GetDefaultAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAccountId.Get(), o.DefaultAccountId.IsSet()
}

// HasDefaultAccountId returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseData) HasDefaultAccountId() bool {
	if o != nil && o.DefaultAccountId.IsSet() {
		return true
	}

	return false
}

// SetDefaultAccountId gets a reference to the given NullableString and assigns it to the DefaultAccountId field.
func (o *GetRevdokuStatus200ResponseData) SetDefaultAccountId(v string) {
	o.DefaultAccountId.Set(&v)
}
// SetDefaultAccountIdNil sets the value for DefaultAccountId to be an explicit nil
func (o *GetRevdokuStatus200ResponseData) SetDefaultAccountIdNil() {
	o.DefaultAccountId.Set(nil)
}

// UnsetDefaultAccountId ensures that no value is present for DefaultAccountId, not even an explicit nil
func (o *GetRevdokuStatus200ResponseData) UnsetDefaultAccountId() {
	o.DefaultAccountId.Unset()
}

// GetAccounts returns the Accounts field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseData) GetAccounts() []AccountIdentity {
	if o == nil || IsNil(o.Accounts) {
		var ret []AccountIdentity
		return ret
	}
	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseData) GetAccountsOk() ([]AccountIdentity, bool) {
	if o == nil || IsNil(o.Accounts) {
		return nil, false
	}
	return o.Accounts, true
}

// HasAccounts returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseData) HasAccounts() bool {
	if o != nil && !IsNil(o.Accounts) {
		return true
	}

	return false
}

// SetAccounts gets a reference to the given []AccountIdentity and assigns it to the Accounts field.
func (o *GetRevdokuStatus200ResponseData) SetAccounts(v []AccountIdentity) {
	o.Accounts = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseData) GetFeatures() map[string]interface{} {
	if o == nil || IsNil(o.Features) {
		var ret map[string]interface{}
		return ret
	}
	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseData) GetFeaturesOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Features) {
		return map[string]interface{}{}, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseData) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given map[string]interface{} and assigns it to the Features field.
func (o *GetRevdokuStatus200ResponseData) SetFeatures(v map[string]interface{}) {
	o.Features = v
}

func (o GetRevdokuStatus200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevdokuStatus200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Account) {
		toSerialize["account"] = o.Account
	}
	if o.DefaultAccountId.IsSet() {
		toSerialize["default_account_id"] = o.DefaultAccountId.Get()
	}
	if !IsNil(o.Accounts) {
		toSerialize["accounts"] = o.Accounts
	}
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetRevdokuStatus200ResponseData) UnmarshalJSON(data []byte) (err error) {
	varGetRevdokuStatus200ResponseData := _GetRevdokuStatus200ResponseData{}

	err = json.Unmarshal(data, &varGetRevdokuStatus200ResponseData)

	if err != nil {
		return err
	}

	*o = GetRevdokuStatus200ResponseData(varGetRevdokuStatus200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "account")
		delete(additionalProperties, "default_account_id")
		delete(additionalProperties, "accounts")
		delete(additionalProperties, "features")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetRevdokuStatus200ResponseData struct {
	value *GetRevdokuStatus200ResponseData
	isSet bool
}

func (v NullableGetRevdokuStatus200ResponseData) Get() *GetRevdokuStatus200ResponseData {
	return v.value
}

func (v *NullableGetRevdokuStatus200ResponseData) Set(val *GetRevdokuStatus200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevdokuStatus200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevdokuStatus200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevdokuStatus200ResponseData(val *GetRevdokuStatus200ResponseData) *NullableGetRevdokuStatus200ResponseData {
	return &NullableGetRevdokuStatus200ResponseData{value: val, isSet: true}
}

func (v NullableGetRevdokuStatus200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevdokuStatus200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


