/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the MailboxFileResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxFileResponseData{}

// MailboxFileResponseData struct for MailboxFileResponseData
type MailboxFileResponseData struct {
	File MailboxFile `json:"file"`
	AdditionalProperties map[string]interface{}
}

type _MailboxFileResponseData MailboxFileResponseData

// NewMailboxFileResponseData instantiates a new MailboxFileResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxFileResponseData(file MailboxFile) *MailboxFileResponseData {
	this := MailboxFileResponseData{}
	this.File = file
	return &this
}

// NewMailboxFileResponseDataWithDefaults instantiates a new MailboxFileResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxFileResponseDataWithDefaults() *MailboxFileResponseData {
	this := MailboxFileResponseData{}
	return &this
}

// GetFile returns the File field value
func (o *MailboxFileResponseData) GetFile() MailboxFile {
	if o == nil {
		var ret MailboxFile
		return ret
	}

	return o.File
}

// GetFileOk returns a tuple with the File field value
// and a boolean to check if the value has been set.
func (o *MailboxFileResponseData) GetFileOk() (*MailboxFile, bool) {
	if o == nil {
		return nil, false
	}
	return &o.File, true
}

// SetFile sets field value
func (o *MailboxFileResponseData) SetFile(v MailboxFile) {
	o.File = v
}

func (o MailboxFileResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxFileResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["file"] = o.File

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailboxFileResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"file",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxFileResponseData := _MailboxFileResponseData{}

	err = json.Unmarshal(data, &varMailboxFileResponseData)

	if err != nil {
		return err
	}

	*o = MailboxFileResponseData(varMailboxFileResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailboxFileResponseData struct {
	value *MailboxFileResponseData
	isSet bool
}

func (v NullableMailboxFileResponseData) Get() *MailboxFileResponseData {
	return v.value
}

func (v *NullableMailboxFileResponseData) Set(val *MailboxFileResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxFileResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxFileResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxFileResponseData(val *MailboxFileResponseData) *NullableMailboxFileResponseData {
	return &NullableMailboxFileResponseData{value: val, isSet: true}
}

func (v NullableMailboxFileResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxFileResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


