/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.526
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the ListMailboxes200ResponseDataMailboxesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListMailboxes200ResponseDataMailboxesInner{}

// ListMailboxes200ResponseDataMailboxesInner struct for ListMailboxes200ResponseDataMailboxesInner
type ListMailboxes200ResponseDataMailboxesInner struct {
	Id string `json:"id"`
	Title string `json:"title"`
	AdditionalProperties map[string]interface{}
}

type _ListMailboxes200ResponseDataMailboxesInner ListMailboxes200ResponseDataMailboxesInner

// NewListMailboxes200ResponseDataMailboxesInner instantiates a new ListMailboxes200ResponseDataMailboxesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListMailboxes200ResponseDataMailboxesInner(id string, title string) *ListMailboxes200ResponseDataMailboxesInner {
	this := ListMailboxes200ResponseDataMailboxesInner{}
	this.Id = id
	this.Title = title
	return &this
}

// NewListMailboxes200ResponseDataMailboxesInnerWithDefaults instantiates a new ListMailboxes200ResponseDataMailboxesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListMailboxes200ResponseDataMailboxesInnerWithDefaults() *ListMailboxes200ResponseDataMailboxesInner {
	this := ListMailboxes200ResponseDataMailboxesInner{}
	return &this
}

// GetId returns the Id field value
func (o *ListMailboxes200ResponseDataMailboxesInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *ListMailboxes200ResponseDataMailboxesInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ListMailboxes200ResponseDataMailboxesInner) SetId(v string) {
	o.Id = v
}

// GetTitle returns the Title field value
func (o *ListMailboxes200ResponseDataMailboxesInner) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *ListMailboxes200ResponseDataMailboxesInner) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *ListMailboxes200ResponseDataMailboxesInner) SetTitle(v string) {
	o.Title = v
}

func (o ListMailboxes200ResponseDataMailboxesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListMailboxes200ResponseDataMailboxesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["title"] = o.Title

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListMailboxes200ResponseDataMailboxesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"title",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListMailboxes200ResponseDataMailboxesInner := _ListMailboxes200ResponseDataMailboxesInner{}

	err = json.Unmarshal(data, &varListMailboxes200ResponseDataMailboxesInner)

	if err != nil {
		return err
	}

	*o = ListMailboxes200ResponseDataMailboxesInner(varListMailboxes200ResponseDataMailboxesInner)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "title")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListMailboxes200ResponseDataMailboxesInner struct {
	value *ListMailboxes200ResponseDataMailboxesInner
	isSet bool
}

func (v NullableListMailboxes200ResponseDataMailboxesInner) Get() *ListMailboxes200ResponseDataMailboxesInner {
	return v.value
}

func (v *NullableListMailboxes200ResponseDataMailboxesInner) Set(val *ListMailboxes200ResponseDataMailboxesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListMailboxes200ResponseDataMailboxesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListMailboxes200ResponseDataMailboxesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListMailboxes200ResponseDataMailboxesInner(val *ListMailboxes200ResponseDataMailboxesInner) *NullableListMailboxes200ResponseDataMailboxesInner {
	return &NullableListMailboxes200ResponseDataMailboxesInner{value: val, isSet: true}
}

func (v NullableListMailboxes200ResponseDataMailboxesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListMailboxes200ResponseDataMailboxesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


