/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.535
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the VerifyAgentSignupRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerifyAgentSignupRequest{}

// VerifyAgentSignupRequest struct for VerifyAgentSignupRequest
type VerifyAgentSignupRequest struct {
	// Six-digit email verification code.
	Code string `json:"code" validate:"regexp=^[0-9]{6}$"`
	// Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
	SignupToken string `json:"signup_token" validate:"regexp=^[A-Za-z0-9_-]{43}$"`
	AdditionalProperties map[string]interface{}
}

type _VerifyAgentSignupRequest VerifyAgentSignupRequest

// NewVerifyAgentSignupRequest instantiates a new VerifyAgentSignupRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerifyAgentSignupRequest(code string, signupToken string) *VerifyAgentSignupRequest {
	this := VerifyAgentSignupRequest{}
	this.Code = code
	this.SignupToken = signupToken
	return &this
}

// NewVerifyAgentSignupRequestWithDefaults instantiates a new VerifyAgentSignupRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerifyAgentSignupRequestWithDefaults() *VerifyAgentSignupRequest {
	this := VerifyAgentSignupRequest{}
	return &this
}

// GetCode returns the Code field value
func (o *VerifyAgentSignupRequest) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *VerifyAgentSignupRequest) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *VerifyAgentSignupRequest) SetCode(v string) {
	o.Code = v
}

// GetSignupToken returns the SignupToken field value
func (o *VerifyAgentSignupRequest) GetSignupToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SignupToken
}

// GetSignupTokenOk returns a tuple with the SignupToken field value
// and a boolean to check if the value has been set.
func (o *VerifyAgentSignupRequest) GetSignupTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SignupToken, true
}

// SetSignupToken sets field value
func (o *VerifyAgentSignupRequest) SetSignupToken(v string) {
	o.SignupToken = v
}

func (o VerifyAgentSignupRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerifyAgentSignupRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["signup_token"] = o.SignupToken

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *VerifyAgentSignupRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"signup_token",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varVerifyAgentSignupRequest := _VerifyAgentSignupRequest{}

	err = json.Unmarshal(data, &varVerifyAgentSignupRequest)

	if err != nil {
		return err
	}

	*o = VerifyAgentSignupRequest(varVerifyAgentSignupRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "code")
		delete(additionalProperties, "signup_token")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableVerifyAgentSignupRequest struct {
	value *VerifyAgentSignupRequest
	isSet bool
}

func (v NullableVerifyAgentSignupRequest) Get() *VerifyAgentSignupRequest {
	return v.value
}

func (v *NullableVerifyAgentSignupRequest) Set(val *VerifyAgentSignupRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableVerifyAgentSignupRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableVerifyAgentSignupRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerifyAgentSignupRequest(val *VerifyAgentSignupRequest) *NullableVerifyAgentSignupRequest {
	return &NullableVerifyAgentSignupRequest{value: val, isSet: true}
}

func (v NullableVerifyAgentSignupRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerifyAgentSignupRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


