/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.535
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateMailbox201Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateMailbox201Response{}

// CreateMailbox201Response struct for CreateMailbox201Response
type CreateMailbox201Response struct {
	Data CreateMailbox201ResponseData `json:"data"`
	Success bool `json:"success"`
	AdditionalProperties map[string]interface{}
}

type _CreateMailbox201Response CreateMailbox201Response

// NewCreateMailbox201Response instantiates a new CreateMailbox201Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateMailbox201Response(data CreateMailbox201ResponseData, success bool) *CreateMailbox201Response {
	this := CreateMailbox201Response{}
	this.Data = data
	this.Success = success
	return &this
}

// NewCreateMailbox201ResponseWithDefaults instantiates a new CreateMailbox201Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateMailbox201ResponseWithDefaults() *CreateMailbox201Response {
	this := CreateMailbox201Response{}
	return &this
}

// GetData returns the Data field value
func (o *CreateMailbox201Response) GetData() CreateMailbox201ResponseData {
	if o == nil {
		var ret CreateMailbox201ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *CreateMailbox201Response) GetDataOk() (*CreateMailbox201ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *CreateMailbox201Response) SetData(v CreateMailbox201ResponseData) {
	o.Data = v
}

// GetSuccess returns the Success field value
func (o *CreateMailbox201Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *CreateMailbox201Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *CreateMailbox201Response) SetSuccess(v bool) {
	o.Success = v
}

func (o CreateMailbox201Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateMailbox201Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["success"] = o.Success

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateMailbox201Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateMailbox201Response := _CreateMailbox201Response{}

	err = json.Unmarshal(data, &varCreateMailbox201Response)

	if err != nil {
		return err
	}

	*o = CreateMailbox201Response(varCreateMailbox201Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateMailbox201Response struct {
	value *CreateMailbox201Response
	isSet bool
}

func (v NullableCreateMailbox201Response) Get() *CreateMailbox201Response {
	return v.value
}

func (v *NullableCreateMailbox201Response) Set(val *CreateMailbox201Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateMailbox201Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateMailbox201Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateMailbox201Response(val *CreateMailbox201Response) *NullableCreateMailbox201Response {
	return &NullableCreateMailbox201Response{value: val, isSet: true}
}

func (v NullableCreateMailbox201Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateMailbox201Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


