/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the MailboxCounts type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MailboxCounts{}

// MailboxCounts Exact authorized mailbox totals after query filtering, before status filtering and pagination.
type MailboxCounts struct {
	Active int64 `json:"active"`
	Archived int64 `json:"archived"`
	Total int64 `json:"total"`
	AdditionalProperties map[string]interface{}
}

type _MailboxCounts MailboxCounts

// NewMailboxCounts instantiates a new MailboxCounts object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMailboxCounts(active int64, archived int64, total int64) *MailboxCounts {
	this := MailboxCounts{}
	this.Active = active
	this.Archived = archived
	this.Total = total
	return &this
}

// NewMailboxCountsWithDefaults instantiates a new MailboxCounts object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMailboxCountsWithDefaults() *MailboxCounts {
	this := MailboxCounts{}
	return &this
}

// GetActive returns the Active field value
func (o *MailboxCounts) GetActive() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Active
}

// GetActiveOk returns a tuple with the Active field value
// and a boolean to check if the value has been set.
func (o *MailboxCounts) GetActiveOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Active, true
}

// SetActive sets field value
func (o *MailboxCounts) SetActive(v int64) {
	o.Active = v
}

// GetArchived returns the Archived field value
func (o *MailboxCounts) GetArchived() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value
// and a boolean to check if the value has been set.
func (o *MailboxCounts) GetArchivedOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Archived, true
}

// SetArchived sets field value
func (o *MailboxCounts) SetArchived(v int64) {
	o.Archived = v
}

// GetTotal returns the Total field value
func (o *MailboxCounts) GetTotal() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *MailboxCounts) GetTotalOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *MailboxCounts) SetTotal(v int64) {
	o.Total = v
}

func (o MailboxCounts) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MailboxCounts) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["active"] = o.Active
	toSerialize["archived"] = o.Archived
	toSerialize["total"] = o.Total

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *MailboxCounts) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"active",
		"archived",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMailboxCounts := _MailboxCounts{}

	err = json.Unmarshal(data, &varMailboxCounts)

	if err != nil {
		return err
	}

	*o = MailboxCounts(varMailboxCounts)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "active")
		delete(additionalProperties, "archived")
		delete(additionalProperties, "total")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableMailboxCounts struct {
	value *MailboxCounts
	isSet bool
}

func (v NullableMailboxCounts) Get() *MailboxCounts {
	return v.value
}

func (v *NullableMailboxCounts) Set(val *MailboxCounts) {
	v.value = val
	v.isSet = true
}

func (v NullableMailboxCounts) IsSet() bool {
	return v.isSet
}

func (v *NullableMailboxCounts) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMailboxCounts(val *MailboxCounts) *NullableMailboxCounts {
	return &NullableMailboxCounts{value: val, isSet: true}
}

func (v NullableMailboxCounts) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMailboxCounts) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


