/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"time"
)

// checks if the FileVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FileVersion{}

// FileVersion struct for FileVersion
type FileVersion struct {
	Id *string `json:"id,omitempty"`
	FileId *string `json:"file_id,omitempty"`
	Name *string `json:"name,omitempty"`
	MimeType *string `json:"mime_type,omitempty"`
	Sha256 *string `json:"sha256,omitempty"`
	Reason NullableString `json:"reason,omitempty"`
	MetaKey *string `json:"meta_key,omitempty"`
	CreatedBySystem *string `json:"created_by_system,omitempty"`
	Deleted *bool `json:"deleted,omitempty"`
	Ready *bool `json:"ready,omitempty"`
	HasText *bool `json:"has_text,omitempty"`
	NormalizationRequired *bool `json:"normalization_required,omitempty"`
	MetaReady *bool `json:"meta_ready,omitempty"`
	VersionNumber *int64 `json:"version_number,omitempty"`
	ByteSize *int64 `json:"byte_size,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	MetaCreatedAt *time.Time `json:"meta_created_at,omitempty"`
	CreatedBy *FileActor `json:"created_by,omitempty"`
	UpdatedBy *FileActor `json:"updated_by,omitempty"`
	CreatedByAgent map[string]interface{} `json:"created_by_agent,omitempty"`
	UpdatedByAgent map[string]interface{} `json:"updated_by_agent,omitempty"`
	CreatedByApiKey map[string]interface{} `json:"created_by_api_key,omitempty"`
	UpdatedByApiKey map[string]interface{} `json:"updated_by_api_key,omitempty"`
	Read *bool `json:"read,omitempty"`
	ReadAt NullableTime `json:"read_at,omitempty"`
	ReadBy NullableFileActor `json:"read_by,omitempty"`
	ReadByApiKey NullableFileKey `json:"read_by_api_key,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _FileVersion FileVersion

// NewFileVersion instantiates a new FileVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFileVersion() *FileVersion {
	this := FileVersion{}
	return &this
}

// NewFileVersionWithDefaults instantiates a new FileVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFileVersionWithDefaults() *FileVersion {
	this := FileVersion{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *FileVersion) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *FileVersion) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *FileVersion) SetId(v string) {
	o.Id = &v
}

// GetFileId returns the FileId field value if set, zero value otherwise.
func (o *FileVersion) GetFileId() string {
	if o == nil || IsNil(o.FileId) {
		var ret string
		return ret
	}
	return *o.FileId
}

// GetFileIdOk returns a tuple with the FileId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetFileIdOk() (*string, bool) {
	if o == nil || IsNil(o.FileId) {
		return nil, false
	}
	return o.FileId, true
}

// HasFileId returns a boolean if a field has been set.
func (o *FileVersion) HasFileId() bool {
	if o != nil && !IsNil(o.FileId) {
		return true
	}

	return false
}

// SetFileId gets a reference to the given string and assigns it to the FileId field.
func (o *FileVersion) SetFileId(v string) {
	o.FileId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *FileVersion) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *FileVersion) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *FileVersion) SetName(v string) {
	o.Name = &v
}

// GetMimeType returns the MimeType field value if set, zero value otherwise.
func (o *FileVersion) GetMimeType() string {
	if o == nil || IsNil(o.MimeType) {
		var ret string
		return ret
	}
	return *o.MimeType
}

// GetMimeTypeOk returns a tuple with the MimeType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetMimeTypeOk() (*string, bool) {
	if o == nil || IsNil(o.MimeType) {
		return nil, false
	}
	return o.MimeType, true
}

// HasMimeType returns a boolean if a field has been set.
func (o *FileVersion) HasMimeType() bool {
	if o != nil && !IsNil(o.MimeType) {
		return true
	}

	return false
}

// SetMimeType gets a reference to the given string and assigns it to the MimeType field.
func (o *FileVersion) SetMimeType(v string) {
	o.MimeType = &v
}

// GetSha256 returns the Sha256 field value if set, zero value otherwise.
func (o *FileVersion) GetSha256() string {
	if o == nil || IsNil(o.Sha256) {
		var ret string
		return ret
	}
	return *o.Sha256
}

// GetSha256Ok returns a tuple with the Sha256 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetSha256Ok() (*string, bool) {
	if o == nil || IsNil(o.Sha256) {
		return nil, false
	}
	return o.Sha256, true
}

// HasSha256 returns a boolean if a field has been set.
func (o *FileVersion) HasSha256() bool {
	if o != nil && !IsNil(o.Sha256) {
		return true
	}

	return false
}

// SetSha256 gets a reference to the given string and assigns it to the Sha256 field.
func (o *FileVersion) SetSha256(v string) {
	o.Sha256 = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileVersion) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileVersion) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *FileVersion) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *FileVersion) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *FileVersion) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *FileVersion) UnsetReason() {
	o.Reason.Unset()
}

// GetMetaKey returns the MetaKey field value if set, zero value otherwise.
func (o *FileVersion) GetMetaKey() string {
	if o == nil || IsNil(o.MetaKey) {
		var ret string
		return ret
	}
	return *o.MetaKey
}

// GetMetaKeyOk returns a tuple with the MetaKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetMetaKeyOk() (*string, bool) {
	if o == nil || IsNil(o.MetaKey) {
		return nil, false
	}
	return o.MetaKey, true
}

// HasMetaKey returns a boolean if a field has been set.
func (o *FileVersion) HasMetaKey() bool {
	if o != nil && !IsNil(o.MetaKey) {
		return true
	}

	return false
}

// SetMetaKey gets a reference to the given string and assigns it to the MetaKey field.
func (o *FileVersion) SetMetaKey(v string) {
	o.MetaKey = &v
}

// GetCreatedBySystem returns the CreatedBySystem field value if set, zero value otherwise.
func (o *FileVersion) GetCreatedBySystem() string {
	if o == nil || IsNil(o.CreatedBySystem) {
		var ret string
		return ret
	}
	return *o.CreatedBySystem
}

// GetCreatedBySystemOk returns a tuple with the CreatedBySystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetCreatedBySystemOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedBySystem) {
		return nil, false
	}
	return o.CreatedBySystem, true
}

// HasCreatedBySystem returns a boolean if a field has been set.
func (o *FileVersion) HasCreatedBySystem() bool {
	if o != nil && !IsNil(o.CreatedBySystem) {
		return true
	}

	return false
}

// SetCreatedBySystem gets a reference to the given string and assigns it to the CreatedBySystem field.
func (o *FileVersion) SetCreatedBySystem(v string) {
	o.CreatedBySystem = &v
}

// GetDeleted returns the Deleted field value if set, zero value otherwise.
func (o *FileVersion) GetDeleted() bool {
	if o == nil || IsNil(o.Deleted) {
		var ret bool
		return ret
	}
	return *o.Deleted
}

// GetDeletedOk returns a tuple with the Deleted field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetDeletedOk() (*bool, bool) {
	if o == nil || IsNil(o.Deleted) {
		return nil, false
	}
	return o.Deleted, true
}

// HasDeleted returns a boolean if a field has been set.
func (o *FileVersion) HasDeleted() bool {
	if o != nil && !IsNil(o.Deleted) {
		return true
	}

	return false
}

// SetDeleted gets a reference to the given bool and assigns it to the Deleted field.
func (o *FileVersion) SetDeleted(v bool) {
	o.Deleted = &v
}

// GetReady returns the Ready field value if set, zero value otherwise.
func (o *FileVersion) GetReady() bool {
	if o == nil || IsNil(o.Ready) {
		var ret bool
		return ret
	}
	return *o.Ready
}

// GetReadyOk returns a tuple with the Ready field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.Ready) {
		return nil, false
	}
	return o.Ready, true
}

// HasReady returns a boolean if a field has been set.
func (o *FileVersion) HasReady() bool {
	if o != nil && !IsNil(o.Ready) {
		return true
	}

	return false
}

// SetReady gets a reference to the given bool and assigns it to the Ready field.
func (o *FileVersion) SetReady(v bool) {
	o.Ready = &v
}

// GetHasText returns the HasText field value if set, zero value otherwise.
func (o *FileVersion) GetHasText() bool {
	if o == nil || IsNil(o.HasText) {
		var ret bool
		return ret
	}
	return *o.HasText
}

// GetHasTextOk returns a tuple with the HasText field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetHasTextOk() (*bool, bool) {
	if o == nil || IsNil(o.HasText) {
		return nil, false
	}
	return o.HasText, true
}

// HasHasText returns a boolean if a field has been set.
func (o *FileVersion) HasHasText() bool {
	if o != nil && !IsNil(o.HasText) {
		return true
	}

	return false
}

// SetHasText gets a reference to the given bool and assigns it to the HasText field.
func (o *FileVersion) SetHasText(v bool) {
	o.HasText = &v
}

// GetNormalizationRequired returns the NormalizationRequired field value if set, zero value otherwise.
func (o *FileVersion) GetNormalizationRequired() bool {
	if o == nil || IsNil(o.NormalizationRequired) {
		var ret bool
		return ret
	}
	return *o.NormalizationRequired
}

// GetNormalizationRequiredOk returns a tuple with the NormalizationRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetNormalizationRequiredOk() (*bool, bool) {
	if o == nil || IsNil(o.NormalizationRequired) {
		return nil, false
	}
	return o.NormalizationRequired, true
}

// HasNormalizationRequired returns a boolean if a field has been set.
func (o *FileVersion) HasNormalizationRequired() bool {
	if o != nil && !IsNil(o.NormalizationRequired) {
		return true
	}

	return false
}

// SetNormalizationRequired gets a reference to the given bool and assigns it to the NormalizationRequired field.
func (o *FileVersion) SetNormalizationRequired(v bool) {
	o.NormalizationRequired = &v
}

// GetMetaReady returns the MetaReady field value if set, zero value otherwise.
func (o *FileVersion) GetMetaReady() bool {
	if o == nil || IsNil(o.MetaReady) {
		var ret bool
		return ret
	}
	return *o.MetaReady
}

// GetMetaReadyOk returns a tuple with the MetaReady field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetMetaReadyOk() (*bool, bool) {
	if o == nil || IsNil(o.MetaReady) {
		return nil, false
	}
	return o.MetaReady, true
}

// HasMetaReady returns a boolean if a field has been set.
func (o *FileVersion) HasMetaReady() bool {
	if o != nil && !IsNil(o.MetaReady) {
		return true
	}

	return false
}

// SetMetaReady gets a reference to the given bool and assigns it to the MetaReady field.
func (o *FileVersion) SetMetaReady(v bool) {
	o.MetaReady = &v
}

// GetVersionNumber returns the VersionNumber field value if set, zero value otherwise.
func (o *FileVersion) GetVersionNumber() int64 {
	if o == nil || IsNil(o.VersionNumber) {
		var ret int64
		return ret
	}
	return *o.VersionNumber
}

// GetVersionNumberOk returns a tuple with the VersionNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetVersionNumberOk() (*int64, bool) {
	if o == nil || IsNil(o.VersionNumber) {
		return nil, false
	}
	return o.VersionNumber, true
}

// HasVersionNumber returns a boolean if a field has been set.
func (o *FileVersion) HasVersionNumber() bool {
	if o != nil && !IsNil(o.VersionNumber) {
		return true
	}

	return false
}

// SetVersionNumber gets a reference to the given int64 and assigns it to the VersionNumber field.
func (o *FileVersion) SetVersionNumber(v int64) {
	o.VersionNumber = &v
}

// GetByteSize returns the ByteSize field value if set, zero value otherwise.
func (o *FileVersion) GetByteSize() int64 {
	if o == nil || IsNil(o.ByteSize) {
		var ret int64
		return ret
	}
	return *o.ByteSize
}

// GetByteSizeOk returns a tuple with the ByteSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetByteSizeOk() (*int64, bool) {
	if o == nil || IsNil(o.ByteSize) {
		return nil, false
	}
	return o.ByteSize, true
}

// HasByteSize returns a boolean if a field has been set.
func (o *FileVersion) HasByteSize() bool {
	if o != nil && !IsNil(o.ByteSize) {
		return true
	}

	return false
}

// SetByteSize gets a reference to the given int64 and assigns it to the ByteSize field.
func (o *FileVersion) SetByteSize(v int64) {
	o.ByteSize = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *FileVersion) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *FileVersion) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *FileVersion) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetMetaCreatedAt returns the MetaCreatedAt field value if set, zero value otherwise.
func (o *FileVersion) GetMetaCreatedAt() time.Time {
	if o == nil || IsNil(o.MetaCreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.MetaCreatedAt
}

// GetMetaCreatedAtOk returns a tuple with the MetaCreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetMetaCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.MetaCreatedAt) {
		return nil, false
	}
	return o.MetaCreatedAt, true
}

// HasMetaCreatedAt returns a boolean if a field has been set.
func (o *FileVersion) HasMetaCreatedAt() bool {
	if o != nil && !IsNil(o.MetaCreatedAt) {
		return true
	}

	return false
}

// SetMetaCreatedAt gets a reference to the given time.Time and assigns it to the MetaCreatedAt field.
func (o *FileVersion) SetMetaCreatedAt(v time.Time) {
	o.MetaCreatedAt = &v
}

// GetCreatedBy returns the CreatedBy field value if set, zero value otherwise.
func (o *FileVersion) GetCreatedBy() FileActor {
	if o == nil || IsNil(o.CreatedBy) {
		var ret FileActor
		return ret
	}
	return *o.CreatedBy
}

// GetCreatedByOk returns a tuple with the CreatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetCreatedByOk() (*FileActor, bool) {
	if o == nil || IsNil(o.CreatedBy) {
		return nil, false
	}
	return o.CreatedBy, true
}

// HasCreatedBy returns a boolean if a field has been set.
func (o *FileVersion) HasCreatedBy() bool {
	if o != nil && !IsNil(o.CreatedBy) {
		return true
	}

	return false
}

// SetCreatedBy gets a reference to the given FileActor and assigns it to the CreatedBy field.
func (o *FileVersion) SetCreatedBy(v FileActor) {
	o.CreatedBy = &v
}

// GetUpdatedBy returns the UpdatedBy field value if set, zero value otherwise.
func (o *FileVersion) GetUpdatedBy() FileActor {
	if o == nil || IsNil(o.UpdatedBy) {
		var ret FileActor
		return ret
	}
	return *o.UpdatedBy
}

// GetUpdatedByOk returns a tuple with the UpdatedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetUpdatedByOk() (*FileActor, bool) {
	if o == nil || IsNil(o.UpdatedBy) {
		return nil, false
	}
	return o.UpdatedBy, true
}

// HasUpdatedBy returns a boolean if a field has been set.
func (o *FileVersion) HasUpdatedBy() bool {
	if o != nil && !IsNil(o.UpdatedBy) {
		return true
	}

	return false
}

// SetUpdatedBy gets a reference to the given FileActor and assigns it to the UpdatedBy field.
func (o *FileVersion) SetUpdatedBy(v FileActor) {
	o.UpdatedBy = &v
}

// GetCreatedByAgent returns the CreatedByAgent field value if set, zero value otherwise.
func (o *FileVersion) GetCreatedByAgent() map[string]interface{} {
	if o == nil || IsNil(o.CreatedByAgent) {
		var ret map[string]interface{}
		return ret
	}
	return o.CreatedByAgent
}

// GetCreatedByAgentOk returns a tuple with the CreatedByAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetCreatedByAgentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CreatedByAgent) {
		return map[string]interface{}{}, false
	}
	return o.CreatedByAgent, true
}

// HasCreatedByAgent returns a boolean if a field has been set.
func (o *FileVersion) HasCreatedByAgent() bool {
	if o != nil && !IsNil(o.CreatedByAgent) {
		return true
	}

	return false
}

// SetCreatedByAgent gets a reference to the given map[string]interface{} and assigns it to the CreatedByAgent field.
func (o *FileVersion) SetCreatedByAgent(v map[string]interface{}) {
	o.CreatedByAgent = v
}

// GetUpdatedByAgent returns the UpdatedByAgent field value if set, zero value otherwise.
func (o *FileVersion) GetUpdatedByAgent() map[string]interface{} {
	if o == nil || IsNil(o.UpdatedByAgent) {
		var ret map[string]interface{}
		return ret
	}
	return o.UpdatedByAgent
}

// GetUpdatedByAgentOk returns a tuple with the UpdatedByAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetUpdatedByAgentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UpdatedByAgent) {
		return map[string]interface{}{}, false
	}
	return o.UpdatedByAgent, true
}

// HasUpdatedByAgent returns a boolean if a field has been set.
func (o *FileVersion) HasUpdatedByAgent() bool {
	if o != nil && !IsNil(o.UpdatedByAgent) {
		return true
	}

	return false
}

// SetUpdatedByAgent gets a reference to the given map[string]interface{} and assigns it to the UpdatedByAgent field.
func (o *FileVersion) SetUpdatedByAgent(v map[string]interface{}) {
	o.UpdatedByAgent = v
}

// GetCreatedByApiKey returns the CreatedByApiKey field value if set, zero value otherwise.
func (o *FileVersion) GetCreatedByApiKey() map[string]interface{} {
	if o == nil || IsNil(o.CreatedByApiKey) {
		var ret map[string]interface{}
		return ret
	}
	return o.CreatedByApiKey
}

// GetCreatedByApiKeyOk returns a tuple with the CreatedByApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetCreatedByApiKeyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CreatedByApiKey) {
		return map[string]interface{}{}, false
	}
	return o.CreatedByApiKey, true
}

// HasCreatedByApiKey returns a boolean if a field has been set.
func (o *FileVersion) HasCreatedByApiKey() bool {
	if o != nil && !IsNil(o.CreatedByApiKey) {
		return true
	}

	return false
}

// SetCreatedByApiKey gets a reference to the given map[string]interface{} and assigns it to the CreatedByApiKey field.
func (o *FileVersion) SetCreatedByApiKey(v map[string]interface{}) {
	o.CreatedByApiKey = v
}

// GetUpdatedByApiKey returns the UpdatedByApiKey field value if set, zero value otherwise.
func (o *FileVersion) GetUpdatedByApiKey() map[string]interface{} {
	if o == nil || IsNil(o.UpdatedByApiKey) {
		var ret map[string]interface{}
		return ret
	}
	return o.UpdatedByApiKey
}

// GetUpdatedByApiKeyOk returns a tuple with the UpdatedByApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetUpdatedByApiKeyOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.UpdatedByApiKey) {
		return map[string]interface{}{}, false
	}
	return o.UpdatedByApiKey, true
}

// HasUpdatedByApiKey returns a boolean if a field has been set.
func (o *FileVersion) HasUpdatedByApiKey() bool {
	if o != nil && !IsNil(o.UpdatedByApiKey) {
		return true
	}

	return false
}

// SetUpdatedByApiKey gets a reference to the given map[string]interface{} and assigns it to the UpdatedByApiKey field.
func (o *FileVersion) SetUpdatedByApiKey(v map[string]interface{}) {
	o.UpdatedByApiKey = v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *FileVersion) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FileVersion) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *FileVersion) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *FileVersion) SetRead(v bool) {
	o.Read = &v
}

// GetReadAt returns the ReadAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileVersion) GetReadAt() time.Time {
	if o == nil || IsNil(o.ReadAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ReadAt.Get()
}

// GetReadAtOk returns a tuple with the ReadAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileVersion) GetReadAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadAt.Get(), o.ReadAt.IsSet()
}

// HasReadAt returns a boolean if a field has been set.
func (o *FileVersion) HasReadAt() bool {
	if o != nil && o.ReadAt.IsSet() {
		return true
	}

	return false
}

// SetReadAt gets a reference to the given NullableTime and assigns it to the ReadAt field.
func (o *FileVersion) SetReadAt(v time.Time) {
	o.ReadAt.Set(&v)
}
// SetReadAtNil sets the value for ReadAt to be an explicit nil
func (o *FileVersion) SetReadAtNil() {
	o.ReadAt.Set(nil)
}

// UnsetReadAt ensures that no value is present for ReadAt, not even an explicit nil
func (o *FileVersion) UnsetReadAt() {
	o.ReadAt.Unset()
}

// GetReadBy returns the ReadBy field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileVersion) GetReadBy() FileActor {
	if o == nil || IsNil(o.ReadBy.Get()) {
		var ret FileActor
		return ret
	}
	return *o.ReadBy.Get()
}

// GetReadByOk returns a tuple with the ReadBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileVersion) GetReadByOk() (*FileActor, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadBy.Get(), o.ReadBy.IsSet()
}

// HasReadBy returns a boolean if a field has been set.
func (o *FileVersion) HasReadBy() bool {
	if o != nil && o.ReadBy.IsSet() {
		return true
	}

	return false
}

// SetReadBy gets a reference to the given NullableFileActor and assigns it to the ReadBy field.
func (o *FileVersion) SetReadBy(v FileActor) {
	o.ReadBy.Set(&v)
}
// SetReadByNil sets the value for ReadBy to be an explicit nil
func (o *FileVersion) SetReadByNil() {
	o.ReadBy.Set(nil)
}

// UnsetReadBy ensures that no value is present for ReadBy, not even an explicit nil
func (o *FileVersion) UnsetReadBy() {
	o.ReadBy.Unset()
}

// GetReadByApiKey returns the ReadByApiKey field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *FileVersion) GetReadByApiKey() FileKey {
	if o == nil || IsNil(o.ReadByApiKey.Get()) {
		var ret FileKey
		return ret
	}
	return *o.ReadByApiKey.Get()
}

// GetReadByApiKeyOk returns a tuple with the ReadByApiKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *FileVersion) GetReadByApiKeyOk() (*FileKey, bool) {
	if o == nil {
		return nil, false
	}
	return o.ReadByApiKey.Get(), o.ReadByApiKey.IsSet()
}

// HasReadByApiKey returns a boolean if a field has been set.
func (o *FileVersion) HasReadByApiKey() bool {
	if o != nil && o.ReadByApiKey.IsSet() {
		return true
	}

	return false
}

// SetReadByApiKey gets a reference to the given NullableFileKey and assigns it to the ReadByApiKey field.
func (o *FileVersion) SetReadByApiKey(v FileKey) {
	o.ReadByApiKey.Set(&v)
}
// SetReadByApiKeyNil sets the value for ReadByApiKey to be an explicit nil
func (o *FileVersion) SetReadByApiKeyNil() {
	o.ReadByApiKey.Set(nil)
}

// UnsetReadByApiKey ensures that no value is present for ReadByApiKey, not even an explicit nil
func (o *FileVersion) UnsetReadByApiKey() {
	o.ReadByApiKey.Unset()
}

func (o FileVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FileVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FileId) {
		toSerialize["file_id"] = o.FileId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.MimeType) {
		toSerialize["mime_type"] = o.MimeType
	}
	if !IsNil(o.Sha256) {
		toSerialize["sha256"] = o.Sha256
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}
	if !IsNil(o.MetaKey) {
		toSerialize["meta_key"] = o.MetaKey
	}
	if !IsNil(o.CreatedBySystem) {
		toSerialize["created_by_system"] = o.CreatedBySystem
	}
	if !IsNil(o.Deleted) {
		toSerialize["deleted"] = o.Deleted
	}
	if !IsNil(o.Ready) {
		toSerialize["ready"] = o.Ready
	}
	if !IsNil(o.HasText) {
		toSerialize["has_text"] = o.HasText
	}
	if !IsNil(o.NormalizationRequired) {
		toSerialize["normalization_required"] = o.NormalizationRequired
	}
	if !IsNil(o.MetaReady) {
		toSerialize["meta_ready"] = o.MetaReady
	}
	if !IsNil(o.VersionNumber) {
		toSerialize["version_number"] = o.VersionNumber
	}
	if !IsNil(o.ByteSize) {
		toSerialize["byte_size"] = o.ByteSize
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.MetaCreatedAt) {
		toSerialize["meta_created_at"] = o.MetaCreatedAt
	}
	if !IsNil(o.CreatedBy) {
		toSerialize["created_by"] = o.CreatedBy
	}
	if !IsNil(o.UpdatedBy) {
		toSerialize["updated_by"] = o.UpdatedBy
	}
	if !IsNil(o.CreatedByAgent) {
		toSerialize["created_by_agent"] = o.CreatedByAgent
	}
	if !IsNil(o.UpdatedByAgent) {
		toSerialize["updated_by_agent"] = o.UpdatedByAgent
	}
	if !IsNil(o.CreatedByApiKey) {
		toSerialize["created_by_api_key"] = o.CreatedByApiKey
	}
	if !IsNil(o.UpdatedByApiKey) {
		toSerialize["updated_by_api_key"] = o.UpdatedByApiKey
	}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	if o.ReadAt.IsSet() {
		toSerialize["read_at"] = o.ReadAt.Get()
	}
	if o.ReadBy.IsSet() {
		toSerialize["read_by"] = o.ReadBy.Get()
	}
	if o.ReadByApiKey.IsSet() {
		toSerialize["read_by_api_key"] = o.ReadByApiKey.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *FileVersion) UnmarshalJSON(data []byte) (err error) {
	varFileVersion := _FileVersion{}

	err = json.Unmarshal(data, &varFileVersion)

	if err != nil {
		return err
	}

	*o = FileVersion(varFileVersion)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "file_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "mime_type")
		delete(additionalProperties, "sha256")
		delete(additionalProperties, "reason")
		delete(additionalProperties, "meta_key")
		delete(additionalProperties, "created_by_system")
		delete(additionalProperties, "deleted")
		delete(additionalProperties, "ready")
		delete(additionalProperties, "has_text")
		delete(additionalProperties, "normalization_required")
		delete(additionalProperties, "meta_ready")
		delete(additionalProperties, "version_number")
		delete(additionalProperties, "byte_size")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "meta_created_at")
		delete(additionalProperties, "created_by")
		delete(additionalProperties, "updated_by")
		delete(additionalProperties, "created_by_agent")
		delete(additionalProperties, "updated_by_agent")
		delete(additionalProperties, "created_by_api_key")
		delete(additionalProperties, "updated_by_api_key")
		delete(additionalProperties, "read")
		delete(additionalProperties, "read_at")
		delete(additionalProperties, "read_by")
		delete(additionalProperties, "read_by_api_key")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableFileVersion struct {
	value *FileVersion
	isSet bool
}

func (v NullableFileVersion) Get() *FileVersion {
	return v.value
}

func (v *NullableFileVersion) Set(val *FileVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableFileVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableFileVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFileVersion(val *FileVersion) *NullableFileVersion {
	return &NullableFileVersion{value: val, isSet: true}
}

func (v NullableFileVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFileVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


