/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.526
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the CreateAccountEmailDomainRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountEmailDomainRequest{}

// CreateAccountEmailDomainRequest struct for CreateAccountEmailDomainRequest
type CreateAccountEmailDomainRequest struct {
	// Dedicated root or unused subdomain, such as mailbox.example.com. Subdomain recommended when root mail already exists.
	Hostname string `json:"hostname"`
	AccountId *string `json:"account_id,omitempty"`
	// Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts.
	Reason NullableString `json:"reason,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _CreateAccountEmailDomainRequest CreateAccountEmailDomainRequest

// NewCreateAccountEmailDomainRequest instantiates a new CreateAccountEmailDomainRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountEmailDomainRequest(hostname string) *CreateAccountEmailDomainRequest {
	this := CreateAccountEmailDomainRequest{}
	this.Hostname = hostname
	return &this
}

// NewCreateAccountEmailDomainRequestWithDefaults instantiates a new CreateAccountEmailDomainRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountEmailDomainRequestWithDefaults() *CreateAccountEmailDomainRequest {
	this := CreateAccountEmailDomainRequest{}
	return &this
}

// GetHostname returns the Hostname field value
func (o *CreateAccountEmailDomainRequest) GetHostname() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Hostname
}

// GetHostnameOk returns a tuple with the Hostname field value
// and a boolean to check if the value has been set.
func (o *CreateAccountEmailDomainRequest) GetHostnameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Hostname, true
}

// SetHostname sets field value
func (o *CreateAccountEmailDomainRequest) SetHostname(v string) {
	o.Hostname = v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *CreateAccountEmailDomainRequest) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountEmailDomainRequest) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *CreateAccountEmailDomainRequest) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *CreateAccountEmailDomainRequest) SetAccountId(v string) {
	o.AccountId = &v
}

// GetReason returns the Reason field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateAccountEmailDomainRequest) GetReason() string {
	if o == nil || IsNil(o.Reason.Get()) {
		var ret string
		return ret
	}
	return *o.Reason.Get()
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateAccountEmailDomainRequest) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Reason.Get(), o.Reason.IsSet()
}

// HasReason returns a boolean if a field has been set.
func (o *CreateAccountEmailDomainRequest) HasReason() bool {
	if o != nil && o.Reason.IsSet() {
		return true
	}

	return false
}

// SetReason gets a reference to the given NullableString and assigns it to the Reason field.
func (o *CreateAccountEmailDomainRequest) SetReason(v string) {
	o.Reason.Set(&v)
}
// SetReasonNil sets the value for Reason to be an explicit nil
func (o *CreateAccountEmailDomainRequest) SetReasonNil() {
	o.Reason.Set(nil)
}

// UnsetReason ensures that no value is present for Reason, not even an explicit nil
func (o *CreateAccountEmailDomainRequest) UnsetReason() {
	o.Reason.Unset()
}

func (o CreateAccountEmailDomainRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountEmailDomainRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["hostname"] = o.Hostname
	if !IsNil(o.AccountId) {
		toSerialize["account_id"] = o.AccountId
	}
	if o.Reason.IsSet() {
		toSerialize["reason"] = o.Reason.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *CreateAccountEmailDomainRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"hostname",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateAccountEmailDomainRequest := _CreateAccountEmailDomainRequest{}

	err = json.Unmarshal(data, &varCreateAccountEmailDomainRequest)

	if err != nil {
		return err
	}

	*o = CreateAccountEmailDomainRequest(varCreateAccountEmailDomainRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "hostname")
		delete(additionalProperties, "account_id")
		delete(additionalProperties, "reason")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableCreateAccountEmailDomainRequest struct {
	value *CreateAccountEmailDomainRequest
	isSet bool
}

func (v NullableCreateAccountEmailDomainRequest) Get() *CreateAccountEmailDomainRequest {
	return v.value
}

func (v *NullableCreateAccountEmailDomainRequest) Set(val *CreateAccountEmailDomainRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountEmailDomainRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountEmailDomainRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountEmailDomainRequest(val *CreateAccountEmailDomainRequest) *NullableCreateAccountEmailDomainRequest {
	return &NullableCreateAccountEmailDomainRequest{value: val, isSet: true}
}

func (v NullableCreateAccountEmailDomainRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountEmailDomainRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


