/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateMailboxEmailAllowlistRequestSenderAllowlist type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMailboxEmailAllowlistRequestSenderAllowlist{}

// UpdateMailboxEmailAllowlistRequestSenderAllowlist struct for UpdateMailboxEmailAllowlistRequestSenderAllowlist
type UpdateMailboxEmailAllowlistRequestSenderAllowlist struct {
	Enabled bool `json:"enabled"`
	Entries []string `json:"entries"`
	AdditionalProperties map[string]interface{}
}

type _UpdateMailboxEmailAllowlistRequestSenderAllowlist UpdateMailboxEmailAllowlistRequestSenderAllowlist

// NewUpdateMailboxEmailAllowlistRequestSenderAllowlist instantiates a new UpdateMailboxEmailAllowlistRequestSenderAllowlist object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMailboxEmailAllowlistRequestSenderAllowlist(enabled bool, entries []string) *UpdateMailboxEmailAllowlistRequestSenderAllowlist {
	this := UpdateMailboxEmailAllowlistRequestSenderAllowlist{}
	this.Enabled = enabled
	this.Entries = entries
	return &this
}

// NewUpdateMailboxEmailAllowlistRequestSenderAllowlistWithDefaults instantiates a new UpdateMailboxEmailAllowlistRequestSenderAllowlist object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMailboxEmailAllowlistRequestSenderAllowlistWithDefaults() *UpdateMailboxEmailAllowlistRequestSenderAllowlist {
	this := UpdateMailboxEmailAllowlistRequestSenderAllowlist{}
	return &this
}

// GetEnabled returns the Enabled field value
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) GetEnabled() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value
// and a boolean to check if the value has been set.
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) GetEnabledOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enabled, true
}

// SetEnabled sets field value
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) SetEnabled(v bool) {
	o.Enabled = v
}

// GetEntries returns the Entries field value
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) GetEntries() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Entries
}

// GetEntriesOk returns a tuple with the Entries field value
// and a boolean to check if the value has been set.
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) GetEntriesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Entries, true
}

// SetEntries sets field value
func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) SetEntries(v []string) {
	o.Entries = v
}

func (o UpdateMailboxEmailAllowlistRequestSenderAllowlist) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMailboxEmailAllowlistRequestSenderAllowlist) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["enabled"] = o.Enabled
	toSerialize["entries"] = o.Entries

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateMailboxEmailAllowlistRequestSenderAllowlist) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"enabled",
		"entries",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMailboxEmailAllowlistRequestSenderAllowlist := _UpdateMailboxEmailAllowlistRequestSenderAllowlist{}

	err = json.Unmarshal(data, &varUpdateMailboxEmailAllowlistRequestSenderAllowlist)

	if err != nil {
		return err
	}

	*o = UpdateMailboxEmailAllowlistRequestSenderAllowlist(varUpdateMailboxEmailAllowlistRequestSenderAllowlist)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "entries")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist struct {
	value *UpdateMailboxEmailAllowlistRequestSenderAllowlist
	isSet bool
}

func (v NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) Get() *UpdateMailboxEmailAllowlistRequestSenderAllowlist {
	return v.value
}

func (v *NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) Set(val *UpdateMailboxEmailAllowlistRequestSenderAllowlist) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMailboxEmailAllowlistRequestSenderAllowlist(val *UpdateMailboxEmailAllowlistRequestSenderAllowlist) *NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist {
	return &NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist{value: val, isSet: true}
}

func (v NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMailboxEmailAllowlistRequestSenderAllowlist) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


