/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the SetEmailWebhook200ResponseDataWebhook type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SetEmailWebhook200ResponseDataWebhook{}

// SetEmailWebhook200ResponseDataWebhook struct for SetEmailWebhook200ResponseDataWebhook
type SetEmailWebhook200ResponseDataWebhook struct {
	Url string `json:"url"`
	Event string `json:"event"`
	SigningSecret string `json:"signing_secret"`
	AdditionalProperties map[string]interface{}
}

type _SetEmailWebhook200ResponseDataWebhook SetEmailWebhook200ResponseDataWebhook

// NewSetEmailWebhook200ResponseDataWebhook instantiates a new SetEmailWebhook200ResponseDataWebhook object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSetEmailWebhook200ResponseDataWebhook(url string, event string, signingSecret string) *SetEmailWebhook200ResponseDataWebhook {
	this := SetEmailWebhook200ResponseDataWebhook{}
	this.Url = url
	this.Event = event
	this.SigningSecret = signingSecret
	return &this
}

// NewSetEmailWebhook200ResponseDataWebhookWithDefaults instantiates a new SetEmailWebhook200ResponseDataWebhook object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSetEmailWebhook200ResponseDataWebhookWithDefaults() *SetEmailWebhook200ResponseDataWebhook {
	this := SetEmailWebhook200ResponseDataWebhook{}
	return &this
}

// GetUrl returns the Url field value
func (o *SetEmailWebhook200ResponseDataWebhook) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *SetEmailWebhook200ResponseDataWebhook) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *SetEmailWebhook200ResponseDataWebhook) SetUrl(v string) {
	o.Url = v
}

// GetEvent returns the Event field value
func (o *SetEmailWebhook200ResponseDataWebhook) GetEvent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Event
}

// GetEventOk returns a tuple with the Event field value
// and a boolean to check if the value has been set.
func (o *SetEmailWebhook200ResponseDataWebhook) GetEventOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Event, true
}

// SetEvent sets field value
func (o *SetEmailWebhook200ResponseDataWebhook) SetEvent(v string) {
	o.Event = v
}

// GetSigningSecret returns the SigningSecret field value
func (o *SetEmailWebhook200ResponseDataWebhook) GetSigningSecret() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SigningSecret
}

// GetSigningSecretOk returns a tuple with the SigningSecret field value
// and a boolean to check if the value has been set.
func (o *SetEmailWebhook200ResponseDataWebhook) GetSigningSecretOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SigningSecret, true
}

// SetSigningSecret sets field value
func (o *SetEmailWebhook200ResponseDataWebhook) SetSigningSecret(v string) {
	o.SigningSecret = v
}

func (o SetEmailWebhook200ResponseDataWebhook) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SetEmailWebhook200ResponseDataWebhook) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["url"] = o.Url
	toSerialize["event"] = o.Event
	toSerialize["signing_secret"] = o.SigningSecret

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *SetEmailWebhook200ResponseDataWebhook) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"url",
		"event",
		"signing_secret",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSetEmailWebhook200ResponseDataWebhook := _SetEmailWebhook200ResponseDataWebhook{}

	err = json.Unmarshal(data, &varSetEmailWebhook200ResponseDataWebhook)

	if err != nil {
		return err
	}

	*o = SetEmailWebhook200ResponseDataWebhook(varSetEmailWebhook200ResponseDataWebhook)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "url")
		delete(additionalProperties, "event")
		delete(additionalProperties, "signing_secret")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableSetEmailWebhook200ResponseDataWebhook struct {
	value *SetEmailWebhook200ResponseDataWebhook
	isSet bool
}

func (v NullableSetEmailWebhook200ResponseDataWebhook) Get() *SetEmailWebhook200ResponseDataWebhook {
	return v.value
}

func (v *NullableSetEmailWebhook200ResponseDataWebhook) Set(val *SetEmailWebhook200ResponseDataWebhook) {
	v.value = val
	v.isSet = true
}

func (v NullableSetEmailWebhook200ResponseDataWebhook) IsSet() bool {
	return v.isSet
}

func (v *NullableSetEmailWebhook200ResponseDataWebhook) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSetEmailWebhook200ResponseDataWebhook(val *SetEmailWebhook200ResponseDataWebhook) *NullableSetEmailWebhook200ResponseDataWebhook {
	return &NullableSetEmailWebhook200ResponseDataWebhook{value: val, isSet: true}
}

func (v NullableSetEmailWebhook200ResponseDataWebhook) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSetEmailWebhook200ResponseDataWebhook) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


