/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the ListAccounts200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListAccounts200ResponseData{}

// ListAccounts200ResponseData struct for ListAccounts200ResponseData
type ListAccounts200ResponseData struct {
	Accounts []AccountIdentity `json:"accounts"`
	DefaultAccountId NullableString `json:"default_account_id"`
	Pagination AccountPagination `json:"pagination"`
	AdditionalProperties map[string]interface{}
}

type _ListAccounts200ResponseData ListAccounts200ResponseData

// NewListAccounts200ResponseData instantiates a new ListAccounts200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListAccounts200ResponseData(accounts []AccountIdentity, defaultAccountId NullableString, pagination AccountPagination) *ListAccounts200ResponseData {
	this := ListAccounts200ResponseData{}
	this.Accounts = accounts
	this.DefaultAccountId = defaultAccountId
	this.Pagination = pagination
	return &this
}

// NewListAccounts200ResponseDataWithDefaults instantiates a new ListAccounts200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListAccounts200ResponseDataWithDefaults() *ListAccounts200ResponseData {
	this := ListAccounts200ResponseData{}
	return &this
}

// GetAccounts returns the Accounts field value
func (o *ListAccounts200ResponseData) GetAccounts() []AccountIdentity {
	if o == nil {
		var ret []AccountIdentity
		return ret
	}

	return o.Accounts
}

// GetAccountsOk returns a tuple with the Accounts field value
// and a boolean to check if the value has been set.
func (o *ListAccounts200ResponseData) GetAccountsOk() ([]AccountIdentity, bool) {
	if o == nil {
		return nil, false
	}
	return o.Accounts, true
}

// SetAccounts sets field value
func (o *ListAccounts200ResponseData) SetAccounts(v []AccountIdentity) {
	o.Accounts = v
}

// GetDefaultAccountId returns the DefaultAccountId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *ListAccounts200ResponseData) GetDefaultAccountId() string {
	if o == nil || o.DefaultAccountId.Get() == nil {
		var ret string
		return ret
	}

	return *o.DefaultAccountId.Get()
}

// GetDefaultAccountIdOk returns a tuple with the DefaultAccountId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ListAccounts200ResponseData) GetDefaultAccountIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.DefaultAccountId.Get(), o.DefaultAccountId.IsSet()
}

// SetDefaultAccountId sets field value
func (o *ListAccounts200ResponseData) SetDefaultAccountId(v string) {
	o.DefaultAccountId.Set(&v)
}

// GetPagination returns the Pagination field value
func (o *ListAccounts200ResponseData) GetPagination() AccountPagination {
	if o == nil {
		var ret AccountPagination
		return ret
	}

	return o.Pagination
}

// GetPaginationOk returns a tuple with the Pagination field value
// and a boolean to check if the value has been set.
func (o *ListAccounts200ResponseData) GetPaginationOk() (*AccountPagination, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pagination, true
}

// SetPagination sets field value
func (o *ListAccounts200ResponseData) SetPagination(v AccountPagination) {
	o.Pagination = v
}

func (o ListAccounts200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListAccounts200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["accounts"] = o.Accounts
	toSerialize["default_account_id"] = o.DefaultAccountId.Get()
	toSerialize["pagination"] = o.Pagination

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ListAccounts200ResponseData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"accounts",
		"default_account_id",
		"pagination",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varListAccounts200ResponseData := _ListAccounts200ResponseData{}

	err = json.Unmarshal(data, &varListAccounts200ResponseData)

	if err != nil {
		return err
	}

	*o = ListAccounts200ResponseData(varListAccounts200ResponseData)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "accounts")
		delete(additionalProperties, "default_account_id")
		delete(additionalProperties, "pagination")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableListAccounts200ResponseData struct {
	value *ListAccounts200ResponseData
	isSet bool
}

func (v NullableListAccounts200ResponseData) Get() *ListAccounts200ResponseData {
	return v.value
}

func (v *NullableListAccounts200ResponseData) Set(val *ListAccounts200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableListAccounts200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableListAccounts200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListAccounts200ResponseData(val *ListAccounts200ResponseData) *NullableListAccounts200ResponseData {
	return &NullableListAccounts200ResponseData{value: val, isSet: true}
}

func (v NullableListAccounts200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListAccounts200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


