/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 2.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"fmt"
)

// checks if the UpdateMailboxEmailAllowlist200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateMailboxEmailAllowlist200Response{}

// UpdateMailboxEmailAllowlist200Response struct for UpdateMailboxEmailAllowlist200Response
type UpdateMailboxEmailAllowlist200Response struct {
	Data UpdateMailboxEmailAllowlist200ResponseData `json:"data"`
	Success bool `json:"success"`
	AdditionalProperties map[string]interface{}
}

type _UpdateMailboxEmailAllowlist200Response UpdateMailboxEmailAllowlist200Response

// NewUpdateMailboxEmailAllowlist200Response instantiates a new UpdateMailboxEmailAllowlist200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateMailboxEmailAllowlist200Response(data UpdateMailboxEmailAllowlist200ResponseData, success bool) *UpdateMailboxEmailAllowlist200Response {
	this := UpdateMailboxEmailAllowlist200Response{}
	this.Data = data
	this.Success = success
	return &this
}

// NewUpdateMailboxEmailAllowlist200ResponseWithDefaults instantiates a new UpdateMailboxEmailAllowlist200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateMailboxEmailAllowlist200ResponseWithDefaults() *UpdateMailboxEmailAllowlist200Response {
	this := UpdateMailboxEmailAllowlist200Response{}
	return &this
}

// GetData returns the Data field value
func (o *UpdateMailboxEmailAllowlist200Response) GetData() UpdateMailboxEmailAllowlist200ResponseData {
	if o == nil {
		var ret UpdateMailboxEmailAllowlist200ResponseData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *UpdateMailboxEmailAllowlist200Response) GetDataOk() (*UpdateMailboxEmailAllowlist200ResponseData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *UpdateMailboxEmailAllowlist200Response) SetData(v UpdateMailboxEmailAllowlist200ResponseData) {
	o.Data = v
}

// GetSuccess returns the Success field value
func (o *UpdateMailboxEmailAllowlist200Response) GetSuccess() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Success
}

// GetSuccessOk returns a tuple with the Success field value
// and a boolean to check if the value has been set.
func (o *UpdateMailboxEmailAllowlist200Response) GetSuccessOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Success, true
}

// SetSuccess sets field value
func (o *UpdateMailboxEmailAllowlist200Response) SetSuccess(v bool) {
	o.Success = v
}

func (o UpdateMailboxEmailAllowlist200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateMailboxEmailAllowlist200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["success"] = o.Success

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *UpdateMailboxEmailAllowlist200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"success",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateMailboxEmailAllowlist200Response := _UpdateMailboxEmailAllowlist200Response{}

	err = json.Unmarshal(data, &varUpdateMailboxEmailAllowlist200Response)

	if err != nil {
		return err
	}

	*o = UpdateMailboxEmailAllowlist200Response(varUpdateMailboxEmailAllowlist200Response)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "data")
		delete(additionalProperties, "success")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableUpdateMailboxEmailAllowlist200Response struct {
	value *UpdateMailboxEmailAllowlist200Response
	isSet bool
}

func (v NullableUpdateMailboxEmailAllowlist200Response) Get() *UpdateMailboxEmailAllowlist200Response {
	return v.value
}

func (v *NullableUpdateMailboxEmailAllowlist200Response) Set(val *UpdateMailboxEmailAllowlist200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateMailboxEmailAllowlist200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateMailboxEmailAllowlist200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateMailboxEmailAllowlist200Response(val *UpdateMailboxEmailAllowlist200Response) *NullableUpdateMailboxEmailAllowlist200Response {
	return &NullableUpdateMailboxEmailAllowlist200Response{value: val, isSet: true}
}

func (v NullableUpdateMailboxEmailAllowlist200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateMailboxEmailAllowlist200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


