/*
Revdoku public agent API

Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

API version: 1.0.527
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package revdoku

import (
	"encoding/json"
	"time"
)

// checks if the GetRevdokuStatus200ResponseDataConnection type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetRevdokuStatus200ResponseDataConnection{}

// GetRevdokuStatus200ResponseDataConnection struct for GetRevdokuStatus200ResponseDataConnection
type GetRevdokuStatus200ResponseDataConnection struct {
	ApiKeyId NullableString `json:"api_key_id,omitempty"`
	Label NullableString `json:"label,omitempty"`
	TokenType NullableString `json:"token_type,omitempty"`
	Scope NullableString `json:"scope,omitempty"`
	ExpiresAt NullableTime `json:"expires_at,omitempty"`
	LastUsedAt NullableTime `json:"last_used_at,omitempty"`
	MailboxAccess NullableString `json:"mailbox_access,omitempty"`
	MailboxIds []string `json:"mailbox_ids,omitempty"`
	DeniedMailboxIds []string `json:"denied_mailbox_ids,omitempty"`
	MailboxPermissions *map[string]string `json:"mailbox_permissions,omitempty"`
	Permissions *map[string]bool `json:"permissions,omitempty"`
	Agent map[string]interface{} `json:"agent,omitempty"`
	Transport NullableString `json:"transport,omitempty"`
	Renewal *GetRevdokuStatus200ResponseDataConnectionRenewal `json:"renewal,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _GetRevdokuStatus200ResponseDataConnection GetRevdokuStatus200ResponseDataConnection

// NewGetRevdokuStatus200ResponseDataConnection instantiates a new GetRevdokuStatus200ResponseDataConnection object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetRevdokuStatus200ResponseDataConnection() *GetRevdokuStatus200ResponseDataConnection {
	this := GetRevdokuStatus200ResponseDataConnection{}
	return &this
}

// NewGetRevdokuStatus200ResponseDataConnectionWithDefaults instantiates a new GetRevdokuStatus200ResponseDataConnection object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetRevdokuStatus200ResponseDataConnectionWithDefaults() *GetRevdokuStatus200ResponseDataConnection {
	this := GetRevdokuStatus200ResponseDataConnection{}
	return &this
}

// GetApiKeyId returns the ApiKeyId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetApiKeyId() string {
	if o == nil || IsNil(o.ApiKeyId.Get()) {
		var ret string
		return ret
	}
	return *o.ApiKeyId.Get()
}

// GetApiKeyIdOk returns a tuple with the ApiKeyId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetApiKeyIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ApiKeyId.Get(), o.ApiKeyId.IsSet()
}

// HasApiKeyId returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasApiKeyId() bool {
	if o != nil && o.ApiKeyId.IsSet() {
		return true
	}

	return false
}

// SetApiKeyId gets a reference to the given NullableString and assigns it to the ApiKeyId field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetApiKeyId(v string) {
	o.ApiKeyId.Set(&v)
}
// SetApiKeyIdNil sets the value for ApiKeyId to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetApiKeyIdNil() {
	o.ApiKeyId.Set(nil)
}

// UnsetApiKeyId ensures that no value is present for ApiKeyId, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetApiKeyId() {
	o.ApiKeyId.Unset()
}

// GetLabel returns the Label field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetLabel() string {
	if o == nil || IsNil(o.Label.Get()) {
		var ret string
		return ret
	}
	return *o.Label.Get()
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetLabelOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Label.Get(), o.Label.IsSet()
}

// HasLabel returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasLabel() bool {
	if o != nil && o.Label.IsSet() {
		return true
	}

	return false
}

// SetLabel gets a reference to the given NullableString and assigns it to the Label field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetLabel(v string) {
	o.Label.Set(&v)
}
// SetLabelNil sets the value for Label to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetLabelNil() {
	o.Label.Set(nil)
}

// UnsetLabel ensures that no value is present for Label, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetLabel() {
	o.Label.Unset()
}

// GetTokenType returns the TokenType field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetTokenType() string {
	if o == nil || IsNil(o.TokenType.Get()) {
		var ret string
		return ret
	}
	return *o.TokenType.Get()
}

// GetTokenTypeOk returns a tuple with the TokenType field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetTokenTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.TokenType.Get(), o.TokenType.IsSet()
}

// HasTokenType returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasTokenType() bool {
	if o != nil && o.TokenType.IsSet() {
		return true
	}

	return false
}

// SetTokenType gets a reference to the given NullableString and assigns it to the TokenType field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetTokenType(v string) {
	o.TokenType.Set(&v)
}
// SetTokenTypeNil sets the value for TokenType to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetTokenTypeNil() {
	o.TokenType.Set(nil)
}

// UnsetTokenType ensures that no value is present for TokenType, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetTokenType() {
	o.TokenType.Unset()
}

// GetScope returns the Scope field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetScope() string {
	if o == nil || IsNil(o.Scope.Get()) {
		var ret string
		return ret
	}
	return *o.Scope.Get()
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetScopeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Scope.Get(), o.Scope.IsSet()
}

// HasScope returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasScope() bool {
	if o != nil && o.Scope.IsSet() {
		return true
	}

	return false
}

// SetScope gets a reference to the given NullableString and assigns it to the Scope field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetScope(v string) {
	o.Scope.Set(&v)
}
// SetScopeNil sets the value for Scope to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetScopeNil() {
	o.Scope.Set(nil)
}

// UnsetScope ensures that no value is present for Scope, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetScope() {
	o.Scope.Unset()
}

// GetExpiresAt returns the ExpiresAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetExpiresAt() time.Time {
	if o == nil || IsNil(o.ExpiresAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.ExpiresAt.Get()
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetExpiresAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiresAt.Get(), o.ExpiresAt.IsSet()
}

// HasExpiresAt returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasExpiresAt() bool {
	if o != nil && o.ExpiresAt.IsSet() {
		return true
	}

	return false
}

// SetExpiresAt gets a reference to the given NullableTime and assigns it to the ExpiresAt field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetExpiresAt(v time.Time) {
	o.ExpiresAt.Set(&v)
}
// SetExpiresAtNil sets the value for ExpiresAt to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetExpiresAtNil() {
	o.ExpiresAt.Set(nil)
}

// UnsetExpiresAt ensures that no value is present for ExpiresAt, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetExpiresAt() {
	o.ExpiresAt.Unset()
}

// GetLastUsedAt returns the LastUsedAt field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetLastUsedAt() time.Time {
	if o == nil || IsNil(o.LastUsedAt.Get()) {
		var ret time.Time
		return ret
	}
	return *o.LastUsedAt.Get()
}

// GetLastUsedAtOk returns a tuple with the LastUsedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetLastUsedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUsedAt.Get(), o.LastUsedAt.IsSet()
}

// HasLastUsedAt returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasLastUsedAt() bool {
	if o != nil && o.LastUsedAt.IsSet() {
		return true
	}

	return false
}

// SetLastUsedAt gets a reference to the given NullableTime and assigns it to the LastUsedAt field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetLastUsedAt(v time.Time) {
	o.LastUsedAt.Set(&v)
}
// SetLastUsedAtNil sets the value for LastUsedAt to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetLastUsedAtNil() {
	o.LastUsedAt.Set(nil)
}

// UnsetLastUsedAt ensures that no value is present for LastUsedAt, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetLastUsedAt() {
	o.LastUsedAt.Unset()
}

// GetMailboxAccess returns the MailboxAccess field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxAccess() string {
	if o == nil || IsNil(o.MailboxAccess.Get()) {
		var ret string
		return ret
	}
	return *o.MailboxAccess.Get()
}

// GetMailboxAccessOk returns a tuple with the MailboxAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxAccessOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MailboxAccess.Get(), o.MailboxAccess.IsSet()
}

// HasMailboxAccess returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasMailboxAccess() bool {
	if o != nil && o.MailboxAccess.IsSet() {
		return true
	}

	return false
}

// SetMailboxAccess gets a reference to the given NullableString and assigns it to the MailboxAccess field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetMailboxAccess(v string) {
	o.MailboxAccess.Set(&v)
}
// SetMailboxAccessNil sets the value for MailboxAccess to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetMailboxAccessNil() {
	o.MailboxAccess.Set(nil)
}

// UnsetMailboxAccess ensures that no value is present for MailboxAccess, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetMailboxAccess() {
	o.MailboxAccess.Unset()
}

// GetMailboxIds returns the MailboxIds field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxIds() []string {
	if o == nil || IsNil(o.MailboxIds) {
		var ret []string
		return ret
	}
	return o.MailboxIds
}

// GetMailboxIdsOk returns a tuple with the MailboxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.MailboxIds) {
		return nil, false
	}
	return o.MailboxIds, true
}

// HasMailboxIds returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasMailboxIds() bool {
	if o != nil && !IsNil(o.MailboxIds) {
		return true
	}

	return false
}

// SetMailboxIds gets a reference to the given []string and assigns it to the MailboxIds field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetMailboxIds(v []string) {
	o.MailboxIds = v
}

// GetDeniedMailboxIds returns the DeniedMailboxIds field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseDataConnection) GetDeniedMailboxIds() []string {
	if o == nil || IsNil(o.DeniedMailboxIds) {
		var ret []string
		return ret
	}
	return o.DeniedMailboxIds
}

// GetDeniedMailboxIdsOk returns a tuple with the DeniedMailboxIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) GetDeniedMailboxIdsOk() ([]string, bool) {
	if o == nil || IsNil(o.DeniedMailboxIds) {
		return nil, false
	}
	return o.DeniedMailboxIds, true
}

// HasDeniedMailboxIds returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasDeniedMailboxIds() bool {
	if o != nil && !IsNil(o.DeniedMailboxIds) {
		return true
	}

	return false
}

// SetDeniedMailboxIds gets a reference to the given []string and assigns it to the DeniedMailboxIds field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetDeniedMailboxIds(v []string) {
	o.DeniedMailboxIds = v
}

// GetMailboxPermissions returns the MailboxPermissions field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxPermissions() map[string]string {
	if o == nil || IsNil(o.MailboxPermissions) {
		var ret map[string]string
		return ret
	}
	return *o.MailboxPermissions
}

// GetMailboxPermissionsOk returns a tuple with the MailboxPermissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) GetMailboxPermissionsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.MailboxPermissions) {
		return nil, false
	}
	return o.MailboxPermissions, true
}

// HasMailboxPermissions returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasMailboxPermissions() bool {
	if o != nil && !IsNil(o.MailboxPermissions) {
		return true
	}

	return false
}

// SetMailboxPermissions gets a reference to the given map[string]string and assigns it to the MailboxPermissions field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetMailboxPermissions(v map[string]string) {
	o.MailboxPermissions = &v
}

// GetPermissions returns the Permissions field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseDataConnection) GetPermissions() map[string]bool {
	if o == nil || IsNil(o.Permissions) {
		var ret map[string]bool
		return ret
	}
	return *o.Permissions
}

// GetPermissionsOk returns a tuple with the Permissions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) GetPermissionsOk() (*map[string]bool, bool) {
	if o == nil || IsNil(o.Permissions) {
		return nil, false
	}
	return o.Permissions, true
}

// HasPermissions returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasPermissions() bool {
	if o != nil && !IsNil(o.Permissions) {
		return true
	}

	return false
}

// SetPermissions gets a reference to the given map[string]bool and assigns it to the Permissions field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetPermissions(v map[string]bool) {
	o.Permissions = &v
}

// GetAgent returns the Agent field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetAgent() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Agent
}

// GetAgentOk returns a tuple with the Agent field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetAgentOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Agent) {
		return map[string]interface{}{}, false
	}
	return o.Agent, true
}

// HasAgent returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasAgent() bool {
	if o != nil && !IsNil(o.Agent) {
		return true
	}

	return false
}

// SetAgent gets a reference to the given map[string]interface{} and assigns it to the Agent field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetAgent(v map[string]interface{}) {
	o.Agent = v
}

// GetTransport returns the Transport field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *GetRevdokuStatus200ResponseDataConnection) GetTransport() string {
	if o == nil || IsNil(o.Transport.Get()) {
		var ret string
		return ret
	}
	return *o.Transport.Get()
}

// GetTransportOk returns a tuple with the Transport field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *GetRevdokuStatus200ResponseDataConnection) GetTransportOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transport.Get(), o.Transport.IsSet()
}

// HasTransport returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasTransport() bool {
	if o != nil && o.Transport.IsSet() {
		return true
	}

	return false
}

// SetTransport gets a reference to the given NullableString and assigns it to the Transport field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetTransport(v string) {
	o.Transport.Set(&v)
}
// SetTransportNil sets the value for Transport to be an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) SetTransportNil() {
	o.Transport.Set(nil)
}

// UnsetTransport ensures that no value is present for Transport, not even an explicit nil
func (o *GetRevdokuStatus200ResponseDataConnection) UnsetTransport() {
	o.Transport.Unset()
}

// GetRenewal returns the Renewal field value if set, zero value otherwise.
func (o *GetRevdokuStatus200ResponseDataConnection) GetRenewal() GetRevdokuStatus200ResponseDataConnectionRenewal {
	if o == nil || IsNil(o.Renewal) {
		var ret GetRevdokuStatus200ResponseDataConnectionRenewal
		return ret
	}
	return *o.Renewal
}

// GetRenewalOk returns a tuple with the Renewal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) GetRenewalOk() (*GetRevdokuStatus200ResponseDataConnectionRenewal, bool) {
	if o == nil || IsNil(o.Renewal) {
		return nil, false
	}
	return o.Renewal, true
}

// HasRenewal returns a boolean if a field has been set.
func (o *GetRevdokuStatus200ResponseDataConnection) HasRenewal() bool {
	if o != nil && !IsNil(o.Renewal) {
		return true
	}

	return false
}

// SetRenewal gets a reference to the given GetRevdokuStatus200ResponseDataConnectionRenewal and assigns it to the Renewal field.
func (o *GetRevdokuStatus200ResponseDataConnection) SetRenewal(v GetRevdokuStatus200ResponseDataConnectionRenewal) {
	o.Renewal = &v
}

func (o GetRevdokuStatus200ResponseDataConnection) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetRevdokuStatus200ResponseDataConnection) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.ApiKeyId.IsSet() {
		toSerialize["api_key_id"] = o.ApiKeyId.Get()
	}
	if o.Label.IsSet() {
		toSerialize["label"] = o.Label.Get()
	}
	if o.TokenType.IsSet() {
		toSerialize["token_type"] = o.TokenType.Get()
	}
	if o.Scope.IsSet() {
		toSerialize["scope"] = o.Scope.Get()
	}
	if o.ExpiresAt.IsSet() {
		toSerialize["expires_at"] = o.ExpiresAt.Get()
	}
	if o.LastUsedAt.IsSet() {
		toSerialize["last_used_at"] = o.LastUsedAt.Get()
	}
	if o.MailboxAccess.IsSet() {
		toSerialize["mailbox_access"] = o.MailboxAccess.Get()
	}
	if !IsNil(o.MailboxIds) {
		toSerialize["mailbox_ids"] = o.MailboxIds
	}
	if !IsNil(o.DeniedMailboxIds) {
		toSerialize["denied_mailbox_ids"] = o.DeniedMailboxIds
	}
	if !IsNil(o.MailboxPermissions) {
		toSerialize["mailbox_permissions"] = o.MailboxPermissions
	}
	if !IsNil(o.Permissions) {
		toSerialize["permissions"] = o.Permissions
	}
	if o.Agent != nil {
		toSerialize["agent"] = o.Agent
	}
	if o.Transport.IsSet() {
		toSerialize["transport"] = o.Transport.Get()
	}
	if !IsNil(o.Renewal) {
		toSerialize["renewal"] = o.Renewal
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetRevdokuStatus200ResponseDataConnection) UnmarshalJSON(data []byte) (err error) {
	varGetRevdokuStatus200ResponseDataConnection := _GetRevdokuStatus200ResponseDataConnection{}

	err = json.Unmarshal(data, &varGetRevdokuStatus200ResponseDataConnection)

	if err != nil {
		return err
	}

	*o = GetRevdokuStatus200ResponseDataConnection(varGetRevdokuStatus200ResponseDataConnection)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "api_key_id")
		delete(additionalProperties, "label")
		delete(additionalProperties, "token_type")
		delete(additionalProperties, "scope")
		delete(additionalProperties, "expires_at")
		delete(additionalProperties, "last_used_at")
		delete(additionalProperties, "mailbox_access")
		delete(additionalProperties, "mailbox_ids")
		delete(additionalProperties, "denied_mailbox_ids")
		delete(additionalProperties, "mailbox_permissions")
		delete(additionalProperties, "permissions")
		delete(additionalProperties, "agent")
		delete(additionalProperties, "transport")
		delete(additionalProperties, "renewal")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetRevdokuStatus200ResponseDataConnection struct {
	value *GetRevdokuStatus200ResponseDataConnection
	isSet bool
}

func (v NullableGetRevdokuStatus200ResponseDataConnection) Get() *GetRevdokuStatus200ResponseDataConnection {
	return v.value
}

func (v *NullableGetRevdokuStatus200ResponseDataConnection) Set(val *GetRevdokuStatus200ResponseDataConnection) {
	v.value = val
	v.isSet = true
}

func (v NullableGetRevdokuStatus200ResponseDataConnection) IsSet() bool {
	return v.isSet
}

func (v *NullableGetRevdokuStatus200ResponseDataConnection) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetRevdokuStatus200ResponseDataConnection(val *GetRevdokuStatus200ResponseDataConnection) *NullableGetRevdokuStatus200ResponseDataConnection {
	return &NullableGetRevdokuStatus200ResponseDataConnection{value: val, isSet: true}
}

func (v NullableGetRevdokuStatus200ResponseDataConnection) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetRevdokuStatus200ResponseDataConnection) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


