#!/bin/sh
#
# install-local.sh - one-command local Revdoku Core installer.
#
# Intended usage:
#   curl -fsSL https://raw.githubusercontent.com/revdoku/revdoku/main/install-local.sh | sh
#
# The script is intentionally POSIX sh so the pipe-to-sh form works on macOS,
# Linux, and WSL. It does not install Docker; it checks for Docker Desktop /
# Docker Engine and explains what is missing.

set -eu

APP_DIR="${REVDOKU_HOME:-$HOME/.revdoku}"
IMAGE="${REVDOKU_IMAGE:-ghcr.io/revdoku/revdoku:latest}"
DEFAULT_PORT="${REVDOKU_DEFAULT_LOCAL_PORT:-3217}"
REQUESTED_PORT="${REVDOKU_PORT:-}"
PORT=""
CONTAINER_NAME="${REVDOKU_CONTAINER_NAME:-revdoku-local}"
PROJECT_NAME="${REVDOKU_PROJECT_NAME:-$CONTAINER_NAME}"
DRY_RUN="${REVDOKU_INSTALL_DRY_RUN:-0}"
ENV_CHANGED="0"

ENV_FILE="$APP_DIR/revdoku.env"
COMPOSE_FILE="$APP_DIR/compose.yml"
HELPER_FILE="$APP_DIR/revdoku"
STORAGE_DIR="$APP_DIR/storage"
BACKUP_DIR="$APP_DIR/backups"

info() {
  printf '%s\n' "$*"
}

die() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

random_hex() {
  bytes="$1"
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex "$bytes"
    return
  fi

  if [ -r /dev/urandom ] && command -v od >/dev/null 2>&1; then
    od -An -N "$bytes" -tx1 /dev/urandom | tr -d ' \n'
    printf '\n'
    return
  fi

  die "could not find a secure random generator (openssl or /dev/urandom)"
}

open_url() {
  url="$1"
  if command -v open >/dev/null 2>&1; then
    open "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "" "$url" >/dev/null 2>&1 || true
  fi
}

check_docker() {
  if [ "$DRY_RUN" = "1" ]; then
    return
  fi

  if ! command -v docker >/dev/null 2>&1; then
    die "Docker is not installed. Install Docker Desktop first: https://www.docker.com/products/docker-desktop/"
  fi

  if ! docker info >/dev/null 2>&1; then
    die "Docker is installed but not running. Start Docker Desktop, wait until it is ready, then run this installer again."
  fi

  if ! docker compose version >/dev/null 2>&1; then
    die "Docker Compose is missing. Docker Desktop includes it; update Docker Desktop or install the Compose plugin."
  fi
}

pull_image() {
  if [ "${REVDOKU_SKIP_PULL:-0}" = "1" ]; then
    info "Skipping image pull because REVDOKU_SKIP_PULL=1"
    return
  fi

  info "Downloading Revdoku Docker image:"
  info "  $IMAGE"
  info "Docker will show layer download progress below."
  if ! docker pull "$IMAGE"; then
    info "Image pull failed; continuing with any local or cached image."
  fi
}

env_file_value() {
  key="$1"
  [ -f "$ENV_FILE" ] || return 1
  sed -n "s/^${key}=//p" "$ENV_FILE" | tail -n 1
}

port_available() {
  port="$1"
  if command -v nc >/dev/null 2>&1; then
    ! nc -z 127.0.0.1 "$port" >/dev/null 2>&1
    return
  fi

  if command -v lsof >/dev/null 2>&1; then
    ! lsof -nP -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1
    return
  fi

  return 0
}

choose_port() {
  port="$DEFAULT_PORT"
  max=$((DEFAULT_PORT + 50))
  while [ "$port" -le "$max" ]; do
    if port_available "$port"; then
      printf '%s\n' "$port"
      return
    fi
    port=$((port + 1))
  done

  die "could not find a free localhost port in ${DEFAULT_PORT}-${max}; set REVDOKU_PORT and run again"
}

ensure_env_setting() {
  key="$1"
  value="$2"
  if ! grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
    printf '%s=%s\n' "$key" "$value" >> "$ENV_FILE"
    ENV_CHANGED="1"
  fi
}

write_env_file() {
  if [ -f "$ENV_FILE" ]; then
    info "Keeping existing $ENV_FILE"
    ensure_env_setting "REVDOKU_PORT" "$PORT"
    ensure_env_setting "REVDOKU_LOCAL_ACCESS" "helper"
    ensure_env_setting "REVDOKU_LOCAL_ACCESS_SECRET" "$(random_hex 32)"
    ensure_env_setting "REVDOKU_REGISTRATION_ENABLED" "false"
    return
  fi

  if [ -d "$STORAGE_DIR" ]; then
    die "storage exists but $ENV_FILE is missing. Restore your full Revdoku backup, or move $STORAGE_DIR aside before starting fresh."
  fi

  tmp="$(mktemp "$APP_DIR/revdoku.env.XXXXXX")"
  {
    printf '# Generated by Revdoku install-local.sh.\n'
    printf '# Keep this file with storage/. Back up the whole Revdoku data folder.\n'
    printf '# LOCKBOX_MASTER_KEY is required to read your local Revdoku data.\n'
    printf 'SECRET_KEY_BASE=%s\n' "$(random_hex 64)"
    printf 'LOCKBOX_MASTER_KEY=%s\n' "$(random_hex 32)"
    printf 'PREFIX_ID_SALT=%s\n' "$(random_hex 32)"
    printf 'REVDOKU_DOC_API_KEY=%s\n' "$(random_hex 32)"
    printf 'REVDOKU_LOCAL_ACCESS_SECRET=%s\n' "$(random_hex 32)"
    printf '\n'
    printf 'REVDOKU_PORT=%s\n' "$PORT"
    printf 'REVDOKU_LOCAL_ACCESS=helper\n'
    printf 'REVDOKU_LOGIN_MODE=password_no_confirmation\n'
    printf 'REVDOKU_REGISTRATION_ENABLED=false\n'
    printf 'APP_HOST=localhost\n'
    printf 'APP_PROTOCOL=http\n'
  } > "$tmp"
  chmod 600 "$tmp" 2>/dev/null || true
  mv "$tmp" "$ENV_FILE"
  info "Created $ENV_FILE"
}

write_compose_file() {
  if [ -f "$COMPOSE_FILE" ] && ! grep -q "Generated by Revdoku install-local.sh" "$COMPOSE_FILE" 2>/dev/null; then
    info "Keeping existing $COMPOSE_FILE"
    return
  fi

  cat > "$COMPOSE_FILE" <<EOF
# Generated by Revdoku install-local.sh.
name: ${PROJECT_NAME}

services:
  revdoku:
    image: ${IMAGE}
    container_name: ${CONTAINER_NAME}
    ports:
      - "127.0.0.1:${PORT}:80"
    env_file:
      - ./revdoku.env
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
      REVDOKU_EDITION: "core"
      REVDOKU_RUNNING_IN_DOCKER: "true"
      REVDOKU_DOC_API_URL: "http://localhost:4001"
      SOLID_QUEUE_IN_PUMA: "true"
      ACTIVE_STORAGE_SERVICE: "local"
      DATABASE_PATH: "/rails/storage/production.sqlite3"
      CACHE_DATABASE_PATH: "/rails/storage/production_cache.sqlite3"
      QUEUE_DATABASE_PATH: "/rails/storage/production_queue.sqlite3"
      CABLE_DATABASE_PATH: "/rails/storage/production_cable.sqlite3"
      AUDIT_DATABASE_PATH: "/rails/storage/production_audit.sqlite3"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./storage:/rails/storage
    restart: unless-stopped
EOF
  info "Wrote $COMPOSE_FILE"
}

write_helper() {
  cat > "$HELPER_FILE" <<'EOF'
#!/bin/sh
set -eu

REVDOKU_HOME="${REVDOKU_HOME:-$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)}"

cd "$REVDOKU_HOME"

die() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

env_value() {
  key="$1"
  [ -f revdoku.env ] || return 1
  sed -n "s/^${key}=//p" revdoku.env | tail -n 1
}

set_env_setting() {
  key="$1"
  value="$2"
  tmp="$(mktemp "${REVDOKU_HOME}/revdoku.env.XXXXXX")"
  found=0

  while IFS= read -r line || [ -n "$line" ]; do
    case "$line" in
      "${key}="*)
        printf '%s=%s\n' "$key" "$value"
        found=1
        ;;
      *)
        printf '%s\n' "$line"
        ;;
    esac
  done < revdoku.env > "$tmp"

  if [ "$found" = "0" ]; then
    printf '\n%s=%s\n' "$key" "$value" >> "$tmp"
  fi

  chmod 600 "$tmp" 2>/dev/null || true
  mv "$tmp" revdoku.env
}

file_port="$(env_value REVDOKU_PORT 2>/dev/null || true)"
PORT="${REVDOKU_PORT:-${file_port:-3217}}"
URL="http://localhost:${PORT}"

ensure_local_data() {
  if [ -d storage ] && [ ! -f revdoku.env ]; then
    die "storage/ exists but revdoku.env is missing. Restore the whole Revdoku folder or a backup made with '$0 backup'."
  fi

  if [ ! -f revdoku.env ]; then
    die "revdoku.env is missing from $REVDOKU_HOME. It contains the key needed to read local data."
  fi
}

open_url() {
  url="${1:-$URL}"
  if command -v open >/dev/null 2>&1; then
    open "$url" >/dev/null 2>&1 || true
  elif command -v xdg-open >/dev/null 2>&1; then
    xdg-open "$url" >/dev/null 2>&1 || true
  elif command -v cmd.exe >/dev/null 2>&1; then
    cmd.exe /c start "" "$url" >/dev/null 2>&1 || true
  else
    printf '%s\n' "$url"
  fi
}

wait_for_health() {
  url="http://127.0.0.1:${PORT}/up"
  i=0
  while [ "$i" -lt 60 ]; do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    i=$((i + 1))
    sleep 2
  done
  return 1
}

local_access_url() {
  output="$(docker compose exec -T revdoku bin/rails runner 'puts Revdoku::LocalAccess.issue_url!' 2>/dev/null)" || return 1
  printf '%s\n' "$output" | tail -n 1
}

local_access_error() {
  die "Could not create a local sign-in link. The running image may not include Core local access yet. Run '$0 update' after publishing a new image, or test local source with: docker build -t revdoku-local-current . && REVDOKU_IMAGE=revdoku-local-current REVDOKU_SKIP_PULL=1 sh install-local.sh"
}

case "${1:-help}" in
  start)
    ensure_local_data
    docker compose up -d
    ;;
  stop)
    docker compose down
    ;;
  restart)
    ensure_local_data
    docker compose restart
    ;;
  update)
    ensure_local_data
    docker compose pull
    docker compose up -d
    ;;
  enable-ollama)
    ensure_local_data
    set_env_setting "LOCAL_OLLAMA_API_KEY" "${LOCAL_OLLAMA_API_KEY:-ollama}"
    set_env_setting "LOCAL_OLLAMA_BASE_URL" "${LOCAL_OLLAMA_BASE_URL:-http://host.docker.internal:11434/v1}"
    if ! command -v ollama >/dev/null 2>&1; then
      printf "Warning: the 'ollama' command was not found in this shell. Install Ollama and run: ollama pull gemma4:e4b\n"
    fi
    docker compose up -d --force-recreate
    printf 'Local Ollama is enabled for Revdoku.\n'
    printf 'Install Ollama on this machine, then run: ollama pull gemma4:e4b\n'
    printf 'If Docker cannot reach Ollama, configure Ollama with OLLAMA_HOST=0.0.0.0:11434 and keep port 11434 private.\n'
    printf 'After sign-in, choose Local Gemma in Account -> AI.\n'
    ;;
  logs)
    docker compose logs -f --tail=200
    ;;
  status)
    docker compose ps
    ;;
  login-url)
    ensure_local_data
    login_url="$(local_access_url)" || local_access_error
    [ -n "$login_url" ] || local_access_error
    printf '%s\n' "$login_url"
    ;;
  open)
    ensure_local_data
    docker compose up -d
    wait_for_health || die "Revdoku started, but did not become ready. Run '$0 logs' for details."
    login_url="$(local_access_url)" || local_access_error
    [ -n "$login_url" ] || local_access_error
    printf 'Opening %s\n' "$login_url"
    open_url "$login_url"
    ;;
  backup)
    ensure_local_data
    [ -f compose.yml ] || die "compose.yml is missing from $REVDOKU_HOME."
    mkdir -p backups
    stamp="$(date +%Y%m%d-%H%M%S)"
    out="backups/revdoku-backup-${stamp}.tar.gz"
    was_running=0
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
      running="$(docker compose ps --status running --quiet 2>/dev/null || true)"
      if [ -n "$running" ]; then
        was_running=1
        docker compose stop
      fi
    else
      printf 'Docker Compose is not available; creating a backup without stopping Revdoku.\n'
    fi
    set -- compose.yml revdoku.env
    [ -f revdoku ] && set -- "$@" revdoku
    [ -d storage ] && set -- "$@" storage
    tar -czf "$out" "$@"
    [ "$was_running" = "1" ] && docker compose up -d
    printf 'Backup written: %s/%s\n' "$REVDOKU_HOME" "$out"
    printf 'This archive contains the encryption key and local data needed for restore.\n'
    ;;
  help|--help|-h)
    cat <<HELP
Usage: $0 <command>

Commands:
  start    Start Revdoku
  stop     Stop Revdoku
  restart  Restart Revdoku
  update   Pull the latest image and restart
  logs     Follow container logs
  status   Show container status
  open     Start Revdoku and open a one-time local sign-in link
  login-url Print a one-time local sign-in link
  enable-ollama Configure Revdoku to use local Ollama
  backup   Create a portable backup of the local Revdoku folder

Data folder:
  $REVDOKU_HOME

Important:
  Revdoku local data is encrypted by the key in revdoku.env. Keep the whole
  data folder together, or use the backup command before moving to a new
  machine. Copying storage/ without revdoku.env can make the data unreadable.
HELP
    ;;
  *)
    printf 'Unknown command: %s\n\n' "$1" >&2
    "$0" help >&2
    exit 1
    ;;
esac
EOF
  chmod +x "$HELPER_FILE" 2>/dev/null || true
}

wait_for_health() {
  url="http://127.0.0.1:${PORT}/up"
  i=0
  while [ "$i" -lt 60 ]; do
    if curl -fsS "$url" >/dev/null 2>&1; then
      return 0
    fi
    i=$((i + 1))
    sleep 2
  done
  return 1
}

mkdir -p "$APP_DIR" "$BACKUP_DIR"
umask 077

existing_port="$(env_file_value REVDOKU_PORT 2>/dev/null || true)"
if [ -n "$REQUESTED_PORT" ]; then
  PORT="$REQUESTED_PORT"
elif [ -n "$existing_port" ]; then
  PORT="$existing_port"
else
  PORT="$(choose_port)"
fi

write_env_file
mkdir -p "$STORAGE_DIR"
write_compose_file
write_helper

if [ "$DRY_RUN" = "1" ]; then
  info "Dry run complete. Files are in $APP_DIR"
  info "Back up this whole folder, or run: $HELPER_FILE backup"
  exit 0
fi

check_docker

info ""
info "Starting Revdoku. The first download can take a few minutes."
(
  cd "$APP_DIR"
  pull_image
  if [ "$ENV_CHANGED" = "1" ]; then
    docker compose up -d --force-recreate
  else
    docker compose up -d
  fi
)

if wait_for_health; then
  info ""
  info "Revdoku is running on localhost:${PORT}."
  info "Do not open that address directly; use the helper so you get a one-time local sign-in link."
  info ""
  info "Opening Revdoku now. Use this command later:"
  info "  $HELPER_FILE open"
  info ""
  info "Local data folder:"
  info "  $APP_DIR"
  info "Back up this whole folder, or run:"
  info "  $HELPER_FILE backup"
  info ""
  info "Useful commands:"
  info "  $HELPER_FILE start"
  info "  $HELPER_FILE stop"
  info "  $HELPER_FILE update"
  info "  $HELPER_FILE backup"
  "$HELPER_FILE" open
else
  info ""
  info "Revdoku was started, but the health check did not pass yet."
  info "Open logs with:"
  info "  $HELPER_FILE logs"
  exit 1
fi
