export {
    createNewEnvelope,
    appendEnvelopeRevision,
    getCurrentEnvelopeRevision,
    rollbackToRevision,
    envelopeToJSON,
    envelopeFromJSON,
} from './envelope-utils';

export {
    getFileNameFromFiles,
    cleanFilename,
    truncateFilename,
    getTitleFromFiles,
} from './string-utils';

export {
    canPerform,
    canPerformAny,
    canPerformAll,
} from './roles';

export {
    createNewBaseObject,
    getPageFromEnvelopeRevision,
    PlacementSide,
    getCheckDataTypeLabel,
    getCheckDataTypeLabels,
    REVDOKU_TYPE_BADGE_CHANGES_BORDER,
    REVDOKU_TYPE_BADGE_CHANGES_BG,
    REVDOKU_TYPE_BADGE_CHANGES_TEXT,
    REVDOKU_TYPE_BADGE_RECHECK_BORDER,
    REVDOKU_TYPE_BADGE_RECHECK_BG,
    REVDOKU_TYPE_BADGE_RECHECK_TEXT,
    REVDOKU_ICON_COLOR_CHANGES,
    REVDOKU_ICON_COLOR_RECHECK,
    REVDOKU_RECHECK_ICON_SVG_PATHS,
    REVDOKU_CHANGES_ICON_SVG_PATHS,
    buildCheckIconSvg,
    REVDOKU_TYPE_BADGE_FONT_SCALE,
    REVDOKU_TYPE_BADGE_FONT_WEIGHT,
    REVDOKU_TYPE_BADGE_HEIGHT_SCALE,
    REVDOKU_TYPE_BADGE_PADDING_H,
    REVDOKU_TYPE_BADGE_GAP,
    REVDOKU_TYPE_BADGE_BORDER_RADIUS,
    REVDOKU_CHECK_ICON_SIZE_SCALE,
    REVDOKU_CHECK_ICON_GAP,
    REVDOKU_LABEL_BADGE_GAP,
} from './common-types';

export {
    calculateBadgeMetrics,
    calculateCornerRadius,
    calculateMessageMetrics,
    calculateSourceBadgePosition,
    resolveLabelRelativePositionRelativeToHighlights,
    resolveLabelRelativePositionRelativeToHighlightsExtended,
    computeShortestArrowPath,
    calculateHintBoundingBox,
    calculateOverlapArea,
    calculateOutOfBoundsArea,
    estimateHintDimensions,
    cropCheckToContentBoxes,
    wrapCheckAroundContentBoxes,
    REVDOKU_BADGE_SIZE_MIN,
    REVDOKU_BADGE_SIZE_MAX,
    REVDOKU_BADGE_SIZE_RATIO,
    REVDOKU_BADGE_PADDING,
    REVDOKU_BADGE_BORDER_WIDTH,
    REVDOKU_BADGE_BORDER_RADIUS,
    REVDOKU_BADGE_FONT_SIZE_RATIO,
    REVDOKU_CORNER_RADIUS_MIN,
    REVDOKU_CORNER_RADIUS_MAX,
    REVDOKU_CORNER_RADIUS_RATIO,
    REVDOKU_MESSAGE_FONT_SIZE_MIN,
    REVDOKU_MESSAGE_FONT_SIZE_MAX,
    REVDOKU_MESSAGE_PADDING,
    REVDOKU_MESSAGE_BACKGROUND_OPACITY,
    REVDOKU_SOURCE_BADGE_SIZE,
    REVDOKU_SOURCE_BADGE_OFFSET,
    REVDOKU_HINT_GAP,
    resolveMarginLabelPositions,
    estimateWrappedLabelDimensions,
    computeArrowPath,
    REVDOKU_MARGIN_LABEL_MIN_WIDTH,
    REVDOKU_MARGIN_LABEL_FONT_SIZE,
    REVDOKU_MARGIN_LABEL_LINE_HEIGHT,
    REVDOKU_MARGIN_LABEL_INNER_PADDING,
    REVDOKU_MARGIN_LABEL_HORIZONTAL_PADDING,
    REVDOKU_MARGIN_LABEL_VERTICAL_GAP,
    REVDOKU_MARGIN_LABEL_MAX_LINES,
    REVDOKU_LAYOUT_LABEL_MAX_LINES,
    REVDOKU_MARGIN_LABEL_BORDER_WIDTH,
    REVDOKU_ARROW_LINE_WIDTH,
    REVDOKU_ARROW_HEAD_SIZE,
    REVDOKU_ANNOTATION_MARGIN,
    REVDOKU_ANNOTATION_MARGIN_SCALE_EXPONENT,
    REVDOKU_MAX_HINT_LABEL_WIDTH,
    REVDOKU_MIN_HINT_LABEL_WIDTH,
    REVDOKU_MIN_LABEL_FONT_PSX,
    REVDOKU_MAX_LABEL_FONT_PSX,
    REVDOKU_MIN_EFFECTIVE_FONT_SIZE,
    REVDOKU_MAX_HINT_LABEL_WIDTH_RATIO,
    REVDOKU_INTRA_GROUP_SPACING,
    restackLabels,
    REVDOKU_SIDE_MAX_FILL,
    REVDOKU_SIDE_FILL_SOURCES,
    inferLabelRelativePositionRelativeToHighlight,
    computeLabelMetrics,
    calculateLabelBadgeSpec,
    REVDOKU_LABEL_BADGE_FONT_SCALE,
    REVDOKU_LABEL_OVERLAP_TOLERANCE,
    boundingBoxesOverlap,
    AutoRepositionStep,
    REVDOKU_AUTO_REPOSITION_LABEL_ALL_STEPS,
    AutoRepositionEvent,
    REVDOKU_LABEL_AUTO_REPOSITION_APPLICATION_BY_EVENT,
    REVDOKU_SIDE_SHIFT_DIRECTION,
    REVDOKU_SIDE_TO_MAGNET_TO,
    REVDOKU_LABEL_SIZE_CONSTRAINTS,
    REVDOKU_SIDE_EXPANSION_CONFIG,
    resolveConstraint,
    resolveMinMax,
    updateLabelSides,
    sortAndStackLabelsAtSides,
    autoRepositionLabels,
    spreadLabelsTowardHighlights,
    REVDOKU_CHECK_TYPE_GROUP_PRIORITY,
    getMainBorderForSide,
    computeStraightConnectionLine,
    compareByVisualPosition,
    alignLabelsToTop,
} from './highlight-rendering-utils';

export type {
    AlignToTopLabel,
    LabelRelativePositionRelativeToHighlight,
    BoundingBox,
    HintPlacementInput,
    HintPlacementResult,
    HintPlacementResultExtended,
    Point,
    MarginLabelPlacement,
    MarginLabelConfig,
    IContentBox,
    HintPlacementOptions,
    LabelMetrics,
    LabelBadgeSpec,
    RestackLabelsOptions,
    SideShiftDirection,
    SideMagnetConfig,
    ConstraintMeasure,
    SizeConstraint,
    SideSizeConstraints,
    SideExpansionEntry,
    ConstraintContext,
    AutoRepositionOptions,
    SpreadItem,
    MainBorderSide,
} from './highlight-rendering-utils';

export {
    drawHighlightBorder,
    drawRuleBadge,
    drawSourceBadge,
    drawCheckMessage,
    drawCompleteHighlight,
    drawWrappedText,
    REVDOKU_LABEL_DRAW_FULL_RECTANGLE,
    drawLabelBorder,
    REVDOKU_LEADER_ARROW_MIN,
    REVDOKU_LEADER_ARROW_MAX,
    REVDOKU_LEADER_ARROW_RATIO,
    REVDOKU_LEADER_ARROW_ANGLE,
    REVDOKU_LEADER_LINE_WIDTH_V2,
    REVDOKU_LEADER_OPACITY,
    REVDOKU_VAL_DISPLAY_OPACITY,
    REVDOKU_VAL_DISPLAY_FONT_SCALE,
    formatValDisplay,
    REVDOKU_LEADER_DASH_PATTERN,
    REVDOKU_LEADER_ARROW_INSET,
    drawLabelBadge,
    drawRecheckIcon,
    drawChangesIcon,
} from './canvas-rendering-utils';
export type { CheckIconType } from './canvas-rendering-utils';

export {
    computeInlineLeader,
    computeMarginLeader,
    computeAllLeaders,
    leaderToArrowPath,
    deconflictLeaders,
    computeLeaderRenderPath,
    snapLeaderEndpointToLabel,
    REVDOKU_LEADER_CENTER_MAX_ANGLE,
    REVDOKU_LEADER_ENDPOINT_STYLE,
    REVDOKU_LEADER_CIRCLE_RADIUS,
} from './leader-router';

export type {
    LeaderRect,
    LeaderAnnotation,
    InlineLeader,
    MarginLeader,
    Leader,
    LeaderRenderPath,
} from './leader-router';

export {
    calculateActualSizeForChecks,
    adjustPositionsToAvoidCollision,
} from './label-reflow';

export {
    starRating,
    formatModelDisplayLabel,
    formatModelOptionLabel,
} from './ai-model-utils';

export type {
    IAIModelOption,
} from './ai-model-utils';

export { renderMustache } from './micro-mustache';

export type {
    LabelDescriptor,
    SizeOptions,
    CollisionOptions,
} from './label-reflow';

export {
    REVDOKU_SMALLEST_BASE64_PNG,
    REVDOKU_MANUAL_LABEL_TEXT,
    REVDOKU_MANUAL_LABEL_BG,
    REVDOKU_HIGHLIGHT_ROUNDING_PERCENT,
    REVDOKU_HIGHLIGHT_DASH_PATTERN,
    REVDOKU_HIGHLIGHT_FILL_ENABLED,
    REVDOKU_HIGHLIGHT_BADGE_WIDTH,
    REVDOKU_HIGHLIGHT_BADGE_HEIGHT,
    REVDOKU_HIGHLIGHT_BADGE_MARGIN,
    REVDOKU_BADGE_BACKGROUND_COLOR,
    REVDOKU_BADGE_TEXT_COLOR,
    REVDOKU_MESSAGE_BACKGROUND_COLOR_TEMPLATE,
    REVDOKU_HINT_TEXT_COLOR_FAILED_MANUAL,
    REVDOKU_HINT_TEXT_COLOR_FAILED_AI,
    REVDOKU_HINT_TEXT_COLOR_PASSED,
    EInputFileMimeType,
    ERuleSource,
    ReportJobStatus,
    EnvelopeStatus,
    IBase,
    IUserScript,
    IUserScriptOutput,
    IPageInfo,
    IEnvelopeRevision,
    IEnvelopeRevisionExport,
    IPreviousRevisionExport,
    IChecklistExport,
    IDocumentFileRevisionExport,
    IReport,
    IPageText,
    IPageDiff,
    ICheck,
    IRule,
    ITypedRule,
    ICheckFlatten,
    ICheckForDisplay,
    IHighlightColors,
    IChecklist,
    IEnvelope,
    EnvelopeSource,
    IEnvelopePermissions,
    IDocumentFile,
    IDocumentFileRevision,
    IDocumentFileRevisionLink,
    ICoordinates,
    ICheckForReindex,
    EPageReviewStatus,
    ICheckDescriptionPosition,
    ICheckData,
    ChecklistType,
    RuleOrigin,
    getColorsForCheckResult,
    getDocumentFileRevisionsForEnvelopeRevision,
    getPagesForDocument,
    createFileRevisionLinksFromVeryLatestFileRevisions,
    getFilesWithOnlyRelatedFileRevisionsForEnvelopeRevision,
    getPageDimensionsFromDocument,
    getDocumentMetaData,
    getPageCountFromDocument,
    getDateTimeAgoAsHumanString,
    CheckSource,
    HighlightMode,
    REVDOKU_DEFAULT_HIGHLIGHT_MODE,
    ConnectionLineMode,
    REVDOKU_HIGHLIGHT_MODES_CONFIG,
    REVDOKU_HIGHLIGHT_MODE_OPTIONS,
    getHighlightModeConfig,
    getConnectionLineEndpoint,
    ReportLayoutMode,
    MessageBoxMode,
    getMinOpacityForImageSize,
    getWidth,
    getHeight,
    isMimeTypeImage,
    isMimeTypePdf,
    createColorWithOpacity,
    generateColorPalette,
    createHighlightStyles,
    createNewRule,
    hasValueMarker,
    stripValueMarker,
    REVDOKU_VALUE_MARKER_RE,
    extractScriptTemplate,
    stripScriptTemplate,
    splitScriptCodeAndTemplate,
    joinScriptCodeAndTemplate,
    stripCodeFence,
    createNewCheck,
    createNewReport,
    createNewChecklist,
    ITag,
    TagColor,
    HighlightModeIcon,
    HighlightModeConfig,
    LabelFontFamily,
    REVDOKU_LABEL_FONT_FAMILIES,
    REVDOKU_DEFAULT_LABEL_FONT_FAMILY,
    LabelTextAlignment,
    REVDOKU_DEFAULT_LABEL_TEXT_ALIGNMENT,
    getFontFamilyCss,
    getCharWidthFactor,
    REVDOKU_CATCH_CHANGES_RULE_ID,
    REVDOKU_CATCH_ALL_RULE_ID,
    CheckType,
    CheckFilterType,
    REVDOKU_CHECK_FILTER_LABELS,
    getCheckTypes,
    getCheckIconType,
    filterChecksByType,

} from './common-types';

export {
    placeLabels,
} from './label-placer';

export {
    svgR,
    svgEsc,
    svgHighlight,
    svgSourceBadge,
    svgLeaderLine,
    svgBadge,
    svgRecheckIcon,
    svgChangesIcon,
    svgTypeBadge,
    svgLabelBox,
    svgFormatLabelHtml,
    REVDOKU_LABEL_BORDER_WIDTH,
    REVDOKU_LABEL_BORDER_RADIUS,
} from './svg-drawing-primitives';
export type { TypeBadgePlacement, LabelBoxOptions, LeaderLineOptions } from './svg-drawing-primitives';

export type {
    PlacerRect,
    PlacerSide,
    LabelPlacementInput,
    LabelPlacementOptions,
    LabelPlacementResult,
    PlacedLabel,
} from './label-placer';
