/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Revdoku.Api.Client.FileParameter;
using OpenAPIDateConverter = Revdoku.Api.Client.OpenAPIDateConverter;

namespace Revdoku.Api.Model
{
    /// <summary>
    /// CreateMailboxEmailAliasRequest
    /// </summary>
    [DataContract(Name = "createMailboxEmailAlias_request")]
    public partial class CreateMailboxEmailAliasRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMailboxEmailAliasRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CreateMailboxEmailAliasRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="CreateMailboxEmailAliasRequest" /> class.
        /// </summary>
        /// <param name="username">Local part of the new address; platform reserved names are unavailable. (required).</param>
        /// <param name="domain">Available platform domain or ready account-owned domain; defaults to the platform domain..</param>
        public CreateMailboxEmailAliasRequest(string username = default, string domain = default)
        {
            // to ensure "username" is required (not null)
            if (username == null)
            {
                throw new ArgumentNullException("username is a required property for CreateMailboxEmailAliasRequest and cannot be null");
            }
            this.Username = username;
            this.Domain = domain;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Local part of the new address; platform reserved names are unavailable.
        /// </summary>
        /// <value>Local part of the new address; platform reserved names are unavailable.</value>
        [DataMember(Name = "username", IsRequired = true, EmitDefaultValue = true)]
        public string Username { get; set; }

        /// <summary>
        /// Available platform domain or ready account-owned domain; defaults to the platform domain.
        /// </summary>
        /// <value>Available platform domain or ready account-owned domain; defaults to the platform domain.</value>
        [DataMember(Name = "domain", EmitDefaultValue = false)]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class CreateMailboxEmailAliasRequest {\n");
            sb.Append("  Username: ").Append(Username).Append("\n");
            sb.Append("  Domain: ").Append(Domain).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Username (string) maxLength
            if (this.Username != null && this.Username.Length > 64)
            {
                yield return new ValidationResult("Invalid value for Username, length must be less than 64.", new [] { "Username" });
            }

            // Username (string) minLength
            if (this.Username != null && this.Username.Length < 1)
            {
                yield return new ValidationResult("Invalid value for Username, length must be greater than 1.", new [] { "Username" });
            }

            yield break;
        }
    }

}
