/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Revdoku.Api.Client.FileParameter;
using OpenAPIDateConverter = Revdoku.Api.Client.OpenAPIDateConverter;

namespace Revdoku.Api.Model
{
    /// <summary>
    /// DecodedIncomingMessageAttachmentsInner
    /// </summary>
    [DataContract(Name = "DecodedIncomingMessage_attachments_inner")]
    public partial class DecodedIncomingMessageAttachmentsInner : IValidatableObject
    {
        /// <summary>
        /// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
        /// </summary>
        /// <value>For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OriginEnum
        {
            /// <summary>
            /// Enum Original for value: original
            /// </summary>
            [EnumMember(Value = "original")]
            Original = 1,

            /// <summary>
            /// Enum Forwarder for value: forwarder
            /// </summary>
            [EnumMember(Value = "forwarder")]
            Forwarder = 2,

            /// <summary>
            /// Enum ForwardedMessage for value: forwarded_message
            /// </summary>
            [EnumMember(Value = "forwarded_message")]
            ForwardedMessage = 3,

            /// <summary>
            /// Enum Unspecified for value: unspecified
            /// </summary>
            [EnumMember(Value = "unspecified")]
            Unspecified = 4
        }


        /// <summary>
        /// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
        /// </summary>
        /// <value>For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.</value>
        [DataMember(Name = "origin", EmitDefaultValue = false)]
        public OriginEnum? Origin { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DecodedIncomingMessageAttachmentsInner" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DecodedIncomingMessageAttachmentsInner()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="DecodedIncomingMessageAttachmentsInner" /> class.
        /// </summary>
        /// <param name="path">Relative to message folder. (required).</param>
        /// <param name="originalFilename">originalFilename (required).</param>
        /// <param name="contentType">contentType (required).</param>
        /// <param name="sizeBytes">sizeBytes (required).</param>
        /// <param name="origin">For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin..</param>
        public DecodedIncomingMessageAttachmentsInner(string path = default, string originalFilename = default, string contentType = default, long sizeBytes = default, OriginEnum? origin = default)
        {
            // to ensure "path" is required (not null)
            if (path == null)
            {
                throw new ArgumentNullException("path is a required property for DecodedIncomingMessageAttachmentsInner and cannot be null");
            }
            this.Path = path;
            // to ensure "originalFilename" is required (not null)
            if (originalFilename == null)
            {
                throw new ArgumentNullException("originalFilename is a required property for DecodedIncomingMessageAttachmentsInner and cannot be null");
            }
            this.OriginalFilename = originalFilename;
            // to ensure "contentType" is required (not null)
            if (contentType == null)
            {
                throw new ArgumentNullException("contentType is a required property for DecodedIncomingMessageAttachmentsInner and cannot be null");
            }
            this.ContentType = contentType;
            this.SizeBytes = sizeBytes;
            this.Origin = origin;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Relative to message folder.
        /// </summary>
        /// <value>Relative to message folder.</value>
        [DataMember(Name = "path", IsRequired = true, EmitDefaultValue = true)]
        public string Path { get; set; }

        /// <summary>
        /// Gets or Sets OriginalFilename
        /// </summary>
        [DataMember(Name = "original_filename", IsRequired = true, EmitDefaultValue = true)]
        public string OriginalFilename { get; set; }

        /// <summary>
        /// Gets or Sets ContentType
        /// </summary>
        [DataMember(Name = "content_type", IsRequired = true, EmitDefaultValue = true)]
        public string ContentType { get; set; }

        /// <summary>
        /// Gets or Sets SizeBytes
        /// </summary>
        [DataMember(Name = "size_bytes", IsRequired = true, EmitDefaultValue = true)]
        public long SizeBytes { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DecodedIncomingMessageAttachmentsInner {\n");
            sb.Append("  Path: ").Append(Path).Append("\n");
            sb.Append("  OriginalFilename: ").Append(OriginalFilename).Append("\n");
            sb.Append("  ContentType: ").Append(ContentType).Append("\n");
            sb.Append("  SizeBytes: ").Append(SizeBytes).Append("\n");
            sb.Append("  Origin: ").Append(Origin).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // SizeBytes (long) minimum
            if (this.SizeBytes < (long)0)
            {
                yield return new ValidationResult("Invalid value for SizeBytes, must be a value greater than or equal to 0.", new [] { "SizeBytes" });
            }

            yield break;
        }
    }

}
