/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Revdoku.Api.Client.FileParameter;
using OpenAPIDateConverter = Revdoku.Api.Client.OpenAPIDateConverter;

namespace Revdoku.Api.Model
{
    /// <summary>
    /// GetRevdokuStatus200ResponseData
    /// </summary>
    [DataContract(Name = "getRevdokuStatus_200_response_data")]
    public partial class GetRevdokuStatus200ResponseData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetRevdokuStatus200ResponseData" /> class.
        /// </summary>
        /// <param name="account">account.</param>
        /// <param name="defaultAccountId">defaultAccountId.</param>
        /// <param name="accounts">accounts.</param>
        /// <param name="features">features.</param>
        /// <param name="connected">connected.</param>
        /// <param name="serverVersion">serverVersion.</param>
        /// <param name="clientVersion">clientVersion.</param>
        /// <param name="connection">connection.</param>
        /// <param name="limits">limits.</param>
        public GetRevdokuStatus200ResponseData(AccountIdentity account = default, string defaultAccountId = default, List<AccountIdentity> accounts = default, GetRevdokuStatus200ResponseDataFeatures features = default, bool connected = default, string serverVersion = default, string clientVersion = default, GetRevdokuStatus200ResponseDataConnection connection = default, Dictionary<string, Object> limits = default)
        {
            this.Account = account;
            this.DefaultAccountId = defaultAccountId;
            this.Accounts = accounts;
            this.Features = features;
            this.Connected = connected;
            this.ServerVersion = serverVersion;
            this.ClientVersion = clientVersion;
            this.Connection = connection;
            this.Limits = limits;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Account
        /// </summary>
        [DataMember(Name = "account", EmitDefaultValue = false)]
        public AccountIdentity Account { get; set; }

        /// <summary>
        /// Gets or Sets DefaultAccountId
        /// </summary>
        [DataMember(Name = "default_account_id", EmitDefaultValue = true)]
        public string DefaultAccountId { get; set; }

        /// <summary>
        /// Gets or Sets Accounts
        /// </summary>
        [DataMember(Name = "accounts", EmitDefaultValue = false)]
        public List<AccountIdentity> Accounts { get; set; }

        /// <summary>
        /// Gets or Sets Features
        /// </summary>
        [DataMember(Name = "features", EmitDefaultValue = false)]
        public GetRevdokuStatus200ResponseDataFeatures Features { get; set; }

        /// <summary>
        /// Gets or Sets Connected
        /// </summary>
        [DataMember(Name = "connected", EmitDefaultValue = true)]
        public bool Connected { get; set; }

        /// <summary>
        /// Gets or Sets ServerVersion
        /// </summary>
        [DataMember(Name = "server_version", EmitDefaultValue = false)]
        public string ServerVersion { get; set; }

        /// <summary>
        /// Gets or Sets ClientVersion
        /// </summary>
        [DataMember(Name = "client_version", EmitDefaultValue = false)]
        public string ClientVersion { get; set; }

        /// <summary>
        /// Gets or Sets Connection
        /// </summary>
        [DataMember(Name = "connection", EmitDefaultValue = false)]
        public GetRevdokuStatus200ResponseDataConnection Connection { get; set; }

        /// <summary>
        /// Gets or Sets Limits
        /// </summary>
        [DataMember(Name = "limits", EmitDefaultValue = true)]
        public Dictionary<string, Object> Limits { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetRevdokuStatus200ResponseData {\n");
            sb.Append("  Account: ").Append(Account).Append("\n");
            sb.Append("  DefaultAccountId: ").Append(DefaultAccountId).Append("\n");
            sb.Append("  Accounts: ").Append(Accounts).Append("\n");
            sb.Append("  Features: ").Append(Features).Append("\n");
            sb.Append("  Connected: ").Append(Connected).Append("\n");
            sb.Append("  ServerVersion: ").Append(ServerVersion).Append("\n");
            sb.Append("  ClientVersion: ").Append(ClientVersion).Append("\n");
            sb.Append("  Connection: ").Append(Connection).Append("\n");
            sb.Append("  Limits: ").Append(Limits).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
