/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Revdoku.Api.Client.FileParameter;
using OpenAPIDateConverter = Revdoku.Api.Client.OpenAPIDateConverter;

namespace Revdoku.Api.Model
{
    /// <summary>
    /// Caller-specific customization capability on the dedicated email GET/rotate endpoints.
    /// </summary>
    [DataContract(Name = "MailboxEmail_customization")]
    public partial class MailboxEmailCustomization : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MailboxEmailCustomization" /> class.
        /// </summary>
        /// <param name="allowed">allowed.</param>
        /// <param name="blockedReason">blockedReason.</param>
        /// <param name="settingsUrl">Account-domain settings link for administrators; null otherwise..</param>
        public MailboxEmailCustomization(bool allowed = default, string blockedReason = default, string settingsUrl = default)
        {
            this.Allowed = allowed;
            this.BlockedReason = blockedReason;
            this.SettingsUrl = settingsUrl;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Allowed
        /// </summary>
        [DataMember(Name = "allowed", EmitDefaultValue = true)]
        public bool Allowed { get; set; }

        /// <summary>
        /// Gets or Sets BlockedReason
        /// </summary>
        [DataMember(Name = "blocked_reason", EmitDefaultValue = true)]
        public string BlockedReason { get; set; }

        /// <summary>
        /// Account-domain settings link for administrators; null otherwise.
        /// </summary>
        /// <value>Account-domain settings link for administrators; null otherwise.</value>
        [DataMember(Name = "settings_url", EmitDefaultValue = true)]
        public string SettingsUrl { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MailboxEmailCustomization {\n");
            sb.Append("  Allowed: ").Append(Allowed).Append("\n");
            sb.Append("  BlockedReason: ").Append(BlockedReason).Append("\n");
            sb.Append("  SettingsUrl: ").Append(SettingsUrl).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
