/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = Revdoku.Api.Client.FileParameter;
using OpenAPIDateConverter = Revdoku.Api.Client.OpenAPIDateConverter;

namespace Revdoku.Api.Model
{
    /// <summary>
    /// UpdateMailboxEmailAllowlistRequest
    /// </summary>
    [DataContract(Name = "updateMailboxEmailAllowlist_request")]
    public partial class UpdateMailboxEmailAllowlistRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateMailboxEmailAllowlistRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected UpdateMailboxEmailAllowlistRequest()
        {
            this.AdditionalProperties = new Dictionary<string, object>();
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateMailboxEmailAllowlistRequest" /> class.
        /// </summary>
        /// <param name="senderAllowlist">senderAllowlist (required).</param>
        /// <param name="expectedVersion">expectedVersion (required).</param>
        /// <param name="accountId">accountId.</param>
        /// <param name="reason">reason.</param>
        public UpdateMailboxEmailAllowlistRequest(UpdateMailboxEmailAllowlistRequestSenderAllowlist senderAllowlist = default, string expectedVersion = default, string accountId = default, string reason = default)
        {
            // to ensure "senderAllowlist" is required (not null)
            if (senderAllowlist == null)
            {
                throw new ArgumentNullException("senderAllowlist is a required property for UpdateMailboxEmailAllowlistRequest and cannot be null");
            }
            this.SenderAllowlist = senderAllowlist;
            // to ensure "expectedVersion" is required (not null)
            if (expectedVersion == null)
            {
                throw new ArgumentNullException("expectedVersion is a required property for UpdateMailboxEmailAllowlistRequest and cannot be null");
            }
            this.ExpectedVersion = expectedVersion;
            this.AccountId = accountId;
            this.Reason = reason;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets SenderAllowlist
        /// </summary>
        [DataMember(Name = "sender_allowlist", IsRequired = true, EmitDefaultValue = true)]
        public UpdateMailboxEmailAllowlistRequestSenderAllowlist SenderAllowlist { get; set; }

        /// <summary>
        /// Gets or Sets ExpectedVersion
        /// </summary>
        [DataMember(Name = "expected_version", IsRequired = true, EmitDefaultValue = true)]
        public string ExpectedVersion { get; set; }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "account_id", EmitDefaultValue = false)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateMailboxEmailAllowlistRequest {\n");
            sb.Append("  SenderAllowlist: ").Append(SenderAllowlist).Append("\n");
            sb.Append("  ExpectedVersion: ").Append(ExpectedVersion).Append("\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Reason (string) maxLength
            if (this.Reason != null && this.Reason.Length > 2000)
            {
                yield return new ValidationResult("Invalid value for Reason, length must be less than 2000.", new [] { "Reason" });
            }

            yield break;
        }
    }

}
