/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.AccountIdentityAgencyAccount;
import com.revdoku.api.model.AccountIdentityPermissions;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * AccountIdentity
 */
@JsonPropertyOrder({
  AccountIdentity.JSON_PROPERTY_ID,
  AccountIdentity.JSON_PROPERTY_NAME,
  AccountIdentity.JSON_PROPERTY_ACCOUNT_KIND,
  AccountIdentity.JSON_PROPERTY_CLIENT_NAME,
  AccountIdentity.JSON_PROPERTY_AGENCY_ACCOUNT,
  AccountIdentity.JSON_PROPERTY_REGION,
  AccountIdentity.JSON_PROPERTY_STATUS,
  AccountIdentity.JSON_PROPERTY_PERMISSIONS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class AccountIdentity {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nonnull
  private String id;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nonnull
  private String name;

  /**
   * Gets or Sets accountKind
   */
  public enum AccountKindEnum {
    STANDARD(String.valueOf("standard")),
    
    AGENCY(String.valueOf("agency")),
    
    CLIENT(String.valueOf("client"));

    private String value;

    AccountKindEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AccountKindEnum fromValue(String value) {
      for (AccountKindEnum b : AccountKindEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_ACCOUNT_KIND = "account_kind";
  @javax.annotation.Nonnull
  private AccountKindEnum accountKind;

  public static final String JSON_PROPERTY_CLIENT_NAME = "client_name";
  @javax.annotation.Nullable
  private String clientName;

  public static final String JSON_PROPERTY_AGENCY_ACCOUNT = "agency_account";
  @javax.annotation.Nullable
  private AccountIdentityAgencyAccount agencyAccount;

  public static final String JSON_PROPERTY_REGION = "region";
  private JsonNullable<String> region = JsonNullable.<String>undefined();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    ACTIVE(String.valueOf("active")),
    
    READ_ONLY(String.valueOf("read_only"));

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static StatusEnum fromValue(String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nullable
  private StatusEnum status;

  public static final String JSON_PROPERTY_PERMISSIONS = "permissions";
  @javax.annotation.Nullable
  private AccountIdentityPermissions permissions;

  public AccountIdentity() { 
  }

  public AccountIdentity id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public AccountIdentity name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Account name, separate from the client person or business.
   * @return name
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public AccountIdentity accountKind(@javax.annotation.Nonnull AccountKindEnum accountKind) {
    this.accountKind = accountKind;
    return this;
  }

  /**
   * Get accountKind
   * @return accountKind
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountKindEnum getAccountKind() {
    return accountKind;
  }


  @JsonProperty(value = JSON_PROPERTY_ACCOUNT_KIND, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountKind(@javax.annotation.Nonnull AccountKindEnum accountKind) {
    this.accountKind = accountKind;
  }


  public AccountIdentity clientName(@javax.annotation.Nullable String clientName) {
    this.clientName = clientName;
    return this;
  }

  /**
   * Client person or business name, or null when unset.
   * @return clientName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CLIENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getClientName() {
    return clientName;
  }


  @JsonProperty(value = JSON_PROPERTY_CLIENT_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClientName(@javax.annotation.Nullable String clientName) {
    this.clientName = clientName;
  }


  public AccountIdentity agencyAccount(@javax.annotation.Nullable AccountIdentityAgencyAccount agencyAccount) {
    this.agencyAccount = agencyAccount;
    return this;
  }

  /**
   * Get agencyAccount
   * @return agencyAccount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AGENCY_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public AccountIdentityAgencyAccount getAgencyAccount() {
    return agencyAccount;
  }


  @JsonProperty(value = JSON_PROPERTY_AGENCY_ACCOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAgencyAccount(@javax.annotation.Nullable AccountIdentityAgencyAccount agencyAccount) {
    this.agencyAccount = agencyAccount;
  }


  public AccountIdentity region(@javax.annotation.Nullable String region) {
    this.region = JsonNullable.<String>of(region);
    return this;
  }

  /**
   * Get region
   * @return region
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getRegion() {
        return region.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REGION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getRegion_JsonNullable() {
    return region;
  }
  
  @JsonProperty(JSON_PROPERTY_REGION)
  public void setRegion_JsonNullable(JsonNullable<String> region) {
    this.region = region;
  }

  public void setRegion(@javax.annotation.Nullable String region) {
    this.region = JsonNullable.<String>of(region);
  }


  public AccountIdentity status(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusEnum getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@javax.annotation.Nullable StatusEnum status) {
    this.status = status;
  }


  public AccountIdentity permissions(@javax.annotation.Nullable AccountIdentityPermissions permissions) {
    this.permissions = permissions;
    return this;
  }

  /**
   * Get permissions
   * @return permissions
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public AccountIdentityPermissions getPermissions() {
    return permissions;
  }


  @JsonProperty(value = JSON_PROPERTY_PERMISSIONS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPermissions(@javax.annotation.Nullable AccountIdentityPermissions permissions) {
    this.permissions = permissions;
  }


  /**
   * Return true if this AccountIdentity object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountIdentity accountIdentity = (AccountIdentity) o;
    return Objects.equals(this.id, accountIdentity.id) &&
        Objects.equals(this.name, accountIdentity.name) &&
        Objects.equals(this.accountKind, accountIdentity.accountKind) &&
        Objects.equals(this.clientName, accountIdentity.clientName) &&
        Objects.equals(this.agencyAccount, accountIdentity.agencyAccount) &&
        equalsNullable(this.region, accountIdentity.region) &&
        Objects.equals(this.status, accountIdentity.status) &&
        Objects.equals(this.permissions, accountIdentity.permissions);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, accountKind, clientName, agencyAccount, hashCodeNullable(region), status, permissions);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountIdentity {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    accountKind: ").append(toIndentedString(accountKind)).append("\n");
    sb.append("    clientName: ").append(toIndentedString(clientName)).append("\n");
    sb.append("    agencyAccount: ").append(toIndentedString(agencyAccount)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    permissions: ").append(toIndentedString(permissions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

