/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.CreateMailboxRequestMailboxEmail;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CreateMailboxRequestMailbox
 */
@JsonPropertyOrder({
  CreateMailboxRequestMailbox.JSON_PROPERTY_DESCRIPTION,
  CreateMailboxRequestMailbox.JSON_PROPERTY_METADATA,
  CreateMailboxRequestMailbox.JSON_PROPERTY_TAG_IDS,
  CreateMailboxRequestMailbox.JSON_PROPERTY_TAG_PATHS,
  CreateMailboxRequestMailbox.JSON_PROPERTY_EMAIL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class CreateMailboxRequestMailbox {
  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private String description;

  public static final String JSON_PROPERTY_METADATA = "metadata";
  @javax.annotation.Nullable
  private Map<String, Object> metadata = new HashMap<>();

  public static final String JSON_PROPERTY_TAG_IDS = "tag_ids";
  @javax.annotation.Nullable
  private List<String> tagIds = new ArrayList<>();

  public static final String JSON_PROPERTY_TAG_PATHS = "tag_paths";
  @javax.annotation.Nullable
  private List<String> tagPaths = new ArrayList<>();

  public static final String JSON_PROPERTY_EMAIL = "email";
  @javax.annotation.Nullable
  private CreateMailboxRequestMailboxEmail email;

  public CreateMailboxRequestMailbox() { 
  }

  public CreateMailboxRequestMailbox description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Get description
   * @return description
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  public CreateMailboxRequestMailbox metadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
    return this;
  }

  public CreateMailboxRequestMailbox putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

  /**
   * Get metadata
   * @return metadata
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getMetadata() {
    return metadata;
  }


  @JsonProperty(value = JSON_PROPERTY_METADATA, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetadata(@javax.annotation.Nullable Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public CreateMailboxRequestMailbox tagIds(@javax.annotation.Nullable List<String> tagIds) {
    this.tagIds = tagIds;
    return this;
  }

  public CreateMailboxRequestMailbox addTagIdsItem(String tagIdsItem) {
    if (this.tagIds == null) {
      this.tagIds = new ArrayList<>();
    }
    this.tagIds.add(tagIdsItem);
    return this;
  }

  /**
   * Get tagIds
   * @return tagIds
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTagIds() {
    return tagIds;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_IDS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagIds(@javax.annotation.Nullable List<String> tagIds) {
    this.tagIds = tagIds;
  }


  public CreateMailboxRequestMailbox tagPaths(@javax.annotation.Nullable List<String> tagPaths) {
    this.tagPaths = tagPaths;
    return this;
  }

  public CreateMailboxRequestMailbox addTagPathsItem(String tagPathsItem) {
    if (this.tagPaths == null) {
      this.tagPaths = new ArrayList<>();
    }
    this.tagPaths.add(tagPathsItem);
    return this;
  }

  /**
   * Get tagPaths
   * @return tagPaths
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_TAG_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getTagPaths() {
    return tagPaths;
  }


  @JsonProperty(value = JSON_PROPERTY_TAG_PATHS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTagPaths(@javax.annotation.Nullable List<String> tagPaths) {
    this.tagPaths = tagPaths;
  }


  public CreateMailboxRequestMailbox email(@javax.annotation.Nullable CreateMailboxRequestMailboxEmail email) {
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CreateMailboxRequestMailboxEmail getEmail() {
    return email;
  }


  @JsonProperty(value = JSON_PROPERTY_EMAIL, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@javax.annotation.Nullable CreateMailboxRequestMailboxEmail email) {
    this.email = email;
  }


  /**
   * Return true if this createMailbox_request_mailbox object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateMailboxRequestMailbox createMailboxRequestMailbox = (CreateMailboxRequestMailbox) o;
    return Objects.equals(this.description, createMailboxRequestMailbox.description) &&
        Objects.equals(this.metadata, createMailboxRequestMailbox.metadata) &&
        Objects.equals(this.tagIds, createMailboxRequestMailbox.tagIds) &&
        Objects.equals(this.tagPaths, createMailboxRequestMailbox.tagPaths) &&
        Objects.equals(this.email, createMailboxRequestMailbox.email);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, metadata, tagIds, tagPaths, email);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateMailboxRequestMailbox {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    tagIds: ").append(toIndentedString(tagIds)).append("\n");
    sb.append("    tagPaths: ").append(toIndentedString(tagPaths)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

