/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.FileActor;
import com.revdoku.api.model.FileKey;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * FileVersion
 */
@JsonPropertyOrder({
  FileVersion.JSON_PROPERTY_ID,
  FileVersion.JSON_PROPERTY_FILE_ID,
  FileVersion.JSON_PROPERTY_NAME,
  FileVersion.JSON_PROPERTY_MIME_TYPE,
  FileVersion.JSON_PROPERTY_SHA256,
  FileVersion.JSON_PROPERTY_REASON,
  FileVersion.JSON_PROPERTY_META_KEY,
  FileVersion.JSON_PROPERTY_CREATED_BY_SYSTEM,
  FileVersion.JSON_PROPERTY_DELETED,
  FileVersion.JSON_PROPERTY_READY,
  FileVersion.JSON_PROPERTY_HAS_TEXT,
  FileVersion.JSON_PROPERTY_NORMALIZATION_REQUIRED,
  FileVersion.JSON_PROPERTY_META_READY,
  FileVersion.JSON_PROPERTY_VERSION_NUMBER,
  FileVersion.JSON_PROPERTY_BYTE_SIZE,
  FileVersion.JSON_PROPERTY_CREATED_AT,
  FileVersion.JSON_PROPERTY_META_CREATED_AT,
  FileVersion.JSON_PROPERTY_CREATED_BY,
  FileVersion.JSON_PROPERTY_UPDATED_BY,
  FileVersion.JSON_PROPERTY_CREATED_BY_AGENT,
  FileVersion.JSON_PROPERTY_UPDATED_BY_AGENT,
  FileVersion.JSON_PROPERTY_CREATED_BY_API_KEY,
  FileVersion.JSON_PROPERTY_UPDATED_BY_API_KEY,
  FileVersion.JSON_PROPERTY_READ,
  FileVersion.JSON_PROPERTY_READ_AT,
  FileVersion.JSON_PROPERTY_READ_BY,
  FileVersion.JSON_PROPERTY_READ_BY_API_KEY
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class FileVersion {
  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private String id;

  public static final String JSON_PROPERTY_FILE_ID = "file_id";
  @javax.annotation.Nullable
  private String fileId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_MIME_TYPE = "mime_type";
  @javax.annotation.Nullable
  private String mimeType;

  public static final String JSON_PROPERTY_SHA256 = "sha256";
  @javax.annotation.Nullable
  private String sha256;

  public static final String JSON_PROPERTY_REASON = "reason";
  private JsonNullable<String> reason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_META_KEY = "meta_key";
  @javax.annotation.Nullable
  private String metaKey;

  public static final String JSON_PROPERTY_CREATED_BY_SYSTEM = "created_by_system";
  @javax.annotation.Nullable
  private String createdBySystem;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private Boolean deleted;

  public static final String JSON_PROPERTY_READY = "ready";
  @javax.annotation.Nullable
  private Boolean ready;

  public static final String JSON_PROPERTY_HAS_TEXT = "has_text";
  @javax.annotation.Nullable
  private Boolean hasText;

  public static final String JSON_PROPERTY_NORMALIZATION_REQUIRED = "normalization_required";
  @javax.annotation.Nullable
  private Boolean normalizationRequired;

  public static final String JSON_PROPERTY_META_READY = "meta_ready";
  @javax.annotation.Nullable
  private Boolean metaReady;

  public static final String JSON_PROPERTY_VERSION_NUMBER = "version_number";
  @javax.annotation.Nullable
  private Long versionNumber;

  public static final String JSON_PROPERTY_BYTE_SIZE = "byte_size";
  @javax.annotation.Nullable
  private Long byteSize;

  public static final String JSON_PROPERTY_CREATED_AT = "created_at";
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_META_CREATED_AT = "meta_created_at";
  @javax.annotation.Nullable
  private OffsetDateTime metaCreatedAt;

  public static final String JSON_PROPERTY_CREATED_BY = "created_by";
  @javax.annotation.Nullable
  private FileActor createdBy;

  public static final String JSON_PROPERTY_UPDATED_BY = "updated_by";
  @javax.annotation.Nullable
  private FileActor updatedBy;

  public static final String JSON_PROPERTY_CREATED_BY_AGENT = "created_by_agent";
  @javax.annotation.Nullable
  private Map<String, Object> createdByAgent = new HashMap<>();

  public static final String JSON_PROPERTY_UPDATED_BY_AGENT = "updated_by_agent";
  @javax.annotation.Nullable
  private Map<String, Object> updatedByAgent = new HashMap<>();

  public static final String JSON_PROPERTY_CREATED_BY_API_KEY = "created_by_api_key";
  @javax.annotation.Nullable
  private Map<String, Object> createdByApiKey = new HashMap<>();

  public static final String JSON_PROPERTY_UPDATED_BY_API_KEY = "updated_by_api_key";
  @javax.annotation.Nullable
  private Map<String, Object> updatedByApiKey = new HashMap<>();

  public static final String JSON_PROPERTY_READ = "read";
  @javax.annotation.Nullable
  private Boolean read;

  public static final String JSON_PROPERTY_READ_AT = "read_at";
  private JsonNullable<OffsetDateTime> readAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_READ_BY = "read_by";
  private JsonNullable<FileActor> readBy = JsonNullable.<FileActor>undefined();

  public static final String JSON_PROPERTY_READ_BY_API_KEY = "read_by_api_key";
  private JsonNullable<FileKey> readByApiKey = JsonNullable.<FileKey>undefined();

  public FileVersion() { 
  }

  public FileVersion id(@javax.annotation.Nullable String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getId() {
    return id;
  }


  @JsonProperty(value = JSON_PROPERTY_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@javax.annotation.Nullable String id) {
    this.id = id;
  }


  public FileVersion fileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
    return this;
  }

  /**
   * Get fileId
   * @return fileId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFileId() {
    return fileId;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFileId(@javax.annotation.Nullable String fileId) {
    this.fileId = fileId;
  }


  public FileVersion name(@javax.annotation.Nullable String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getName() {
    return name;
  }


  @JsonProperty(value = JSON_PROPERTY_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public FileVersion mimeType(@javax.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

  /**
   * Get mimeType
   * @return mimeType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMimeType() {
    return mimeType;
  }


  @JsonProperty(value = JSON_PROPERTY_MIME_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMimeType(@javax.annotation.Nullable String mimeType) {
    this.mimeType = mimeType;
  }


  public FileVersion sha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
    return this;
  }

  /**
   * Get sha256
   * @return sha256
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SHA256, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSha256() {
    return sha256;
  }


  @JsonProperty(value = JSON_PROPERTY_SHA256, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSha256(@javax.annotation.Nullable String sha256) {
    this.sha256 = sha256;
  }


  public FileVersion reason(@javax.annotation.Nullable String reason) {
    this.reason = JsonNullable.<String>of(reason);
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getReason() {
        return reason.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getReason_JsonNullable() {
    return reason;
  }
  
  @JsonProperty(JSON_PROPERTY_REASON)
  public void setReason_JsonNullable(JsonNullable<String> reason) {
    this.reason = reason;
  }

  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = JsonNullable.<String>of(reason);
  }


  public FileVersion metaKey(@javax.annotation.Nullable String metaKey) {
    this.metaKey = metaKey;
    return this;
  }

  /**
   * Get metaKey
   * @return metaKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMetaKey() {
    return metaKey;
  }


  @JsonProperty(value = JSON_PROPERTY_META_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaKey(@javax.annotation.Nullable String metaKey) {
    this.metaKey = metaKey;
  }


  public FileVersion createdBySystem(@javax.annotation.Nullable String createdBySystem) {
    this.createdBySystem = createdBySystem;
    return this;
  }

  /**
   * Get createdBySystem
   * @return createdBySystem
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getCreatedBySystem() {
    return createdBySystem;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_SYSTEM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBySystem(@javax.annotation.Nullable String createdBySystem) {
    this.createdBySystem = createdBySystem;
  }


  public FileVersion deleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
    return this;
  }

  /**
   * Get deleted
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDeleted() {
    return deleted;
  }


  @JsonProperty(value = JSON_PROPERTY_DELETED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeleted(@javax.annotation.Nullable Boolean deleted) {
    this.deleted = deleted;
  }


  public FileVersion ready(@javax.annotation.Nullable Boolean ready) {
    this.ready = ready;
    return this;
  }

  /**
   * Get ready
   * @return ready
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_READY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getReady() {
    return ready;
  }


  @JsonProperty(value = JSON_PROPERTY_READY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReady(@javax.annotation.Nullable Boolean ready) {
    this.ready = ready;
  }


  public FileVersion hasText(@javax.annotation.Nullable Boolean hasText) {
    this.hasText = hasText;
    return this;
  }

  /**
   * Get hasText
   * @return hasText
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_HAS_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHasText() {
    return hasText;
  }


  @JsonProperty(value = JSON_PROPERTY_HAS_TEXT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasText(@javax.annotation.Nullable Boolean hasText) {
    this.hasText = hasText;
  }


  public FileVersion normalizationRequired(@javax.annotation.Nullable Boolean normalizationRequired) {
    this.normalizationRequired = normalizationRequired;
    return this;
  }

  /**
   * Get normalizationRequired
   * @return normalizationRequired
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_NORMALIZATION_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getNormalizationRequired() {
    return normalizationRequired;
  }


  @JsonProperty(value = JSON_PROPERTY_NORMALIZATION_REQUIRED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNormalizationRequired(@javax.annotation.Nullable Boolean normalizationRequired) {
    this.normalizationRequired = normalizationRequired;
  }


  public FileVersion metaReady(@javax.annotation.Nullable Boolean metaReady) {
    this.metaReady = metaReady;
    return this;
  }

  /**
   * Get metaReady
   * @return metaReady
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_READY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getMetaReady() {
    return metaReady;
  }


  @JsonProperty(value = JSON_PROPERTY_META_READY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaReady(@javax.annotation.Nullable Boolean metaReady) {
    this.metaReady = metaReady;
  }


  public FileVersion versionNumber(@javax.annotation.Nullable Long versionNumber) {
    this.versionNumber = versionNumber;
    return this;
  }

  /**
   * Get versionNumber
   * @return versionNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getVersionNumber() {
    return versionNumber;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION_NUMBER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersionNumber(@javax.annotation.Nullable Long versionNumber) {
    this.versionNumber = versionNumber;
  }


  public FileVersion byteSize(@javax.annotation.Nullable Long byteSize) {
    this.byteSize = byteSize;
    return this;
  }

  /**
   * Get byteSize
   * @return byteSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BYTE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getByteSize() {
    return byteSize;
  }


  @JsonProperty(value = JSON_PROPERTY_BYTE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setByteSize(@javax.annotation.Nullable Long byteSize) {
    this.byteSize = byteSize;
  }


  public FileVersion createdAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedAt(@javax.annotation.Nullable OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public FileVersion metaCreatedAt(@javax.annotation.Nullable OffsetDateTime metaCreatedAt) {
    this.metaCreatedAt = metaCreatedAt;
    return this;
  }

  /**
   * Get metaCreatedAt
   * @return metaCreatedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_META_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public OffsetDateTime getMetaCreatedAt() {
    return metaCreatedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_META_CREATED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMetaCreatedAt(@javax.annotation.Nullable OffsetDateTime metaCreatedAt) {
    this.metaCreatedAt = metaCreatedAt;
  }


  public FileVersion createdBy(@javax.annotation.Nullable FileActor createdBy) {
    this.createdBy = createdBy;
    return this;
  }

  /**
   * Get createdBy
   * @return createdBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FileActor getCreatedBy() {
    return createdBy;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedBy(@javax.annotation.Nullable FileActor createdBy) {
    this.createdBy = createdBy;
  }


  public FileVersion updatedBy(@javax.annotation.Nullable FileActor updatedBy) {
    this.updatedBy = updatedBy;
    return this;
  }

  /**
   * Get updatedBy
   * @return updatedBy
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FileActor getUpdatedBy() {
    return updatedBy;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedBy(@javax.annotation.Nullable FileActor updatedBy) {
    this.updatedBy = updatedBy;
  }


  public FileVersion createdByAgent(@javax.annotation.Nullable Map<String, Object> createdByAgent) {
    this.createdByAgent = createdByAgent;
    return this;
  }

  public FileVersion putCreatedByAgentItem(String key, Object createdByAgentItem) {
    if (this.createdByAgent == null) {
      this.createdByAgent = new HashMap<>();
    }
    this.createdByAgent.put(key, createdByAgentItem);
    return this;
  }

  /**
   * Get createdByAgent
   * @return createdByAgent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getCreatedByAgent() {
    return createdByAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedByAgent(@javax.annotation.Nullable Map<String, Object> createdByAgent) {
    this.createdByAgent = createdByAgent;
  }


  public FileVersion updatedByAgent(@javax.annotation.Nullable Map<String, Object> updatedByAgent) {
    this.updatedByAgent = updatedByAgent;
    return this;
  }

  public FileVersion putUpdatedByAgentItem(String key, Object updatedByAgentItem) {
    if (this.updatedByAgent == null) {
      this.updatedByAgent = new HashMap<>();
    }
    this.updatedByAgent.put(key, updatedByAgentItem);
    return this;
  }

  /**
   * Get updatedByAgent
   * @return updatedByAgent
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getUpdatedByAgent() {
    return updatedByAgent;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY_AGENT, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedByAgent(@javax.annotation.Nullable Map<String, Object> updatedByAgent) {
    this.updatedByAgent = updatedByAgent;
  }


  public FileVersion createdByApiKey(@javax.annotation.Nullable Map<String, Object> createdByApiKey) {
    this.createdByApiKey = createdByApiKey;
    return this;
  }

  public FileVersion putCreatedByApiKeyItem(String key, Object createdByApiKeyItem) {
    if (this.createdByApiKey == null) {
      this.createdByApiKey = new HashMap<>();
    }
    this.createdByApiKey.put(key, createdByApiKeyItem);
    return this;
  }

  /**
   * Get createdByApiKey
   * @return createdByApiKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_API_KEY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getCreatedByApiKey() {
    return createdByApiKey;
  }


  @JsonProperty(value = JSON_PROPERTY_CREATED_BY_API_KEY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreatedByApiKey(@javax.annotation.Nullable Map<String, Object> createdByApiKey) {
    this.createdByApiKey = createdByApiKey;
  }


  public FileVersion updatedByApiKey(@javax.annotation.Nullable Map<String, Object> updatedByApiKey) {
    this.updatedByApiKey = updatedByApiKey;
    return this;
  }

  public FileVersion putUpdatedByApiKeyItem(String key, Object updatedByApiKeyItem) {
    if (this.updatedByApiKey == null) {
      this.updatedByApiKey = new HashMap<>();
    }
    this.updatedByApiKey.put(key, updatedByApiKeyItem);
    return this;
  }

  /**
   * Get updatedByApiKey
   * @return updatedByApiKey
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY_API_KEY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getUpdatedByApiKey() {
    return updatedByApiKey;
  }


  @JsonProperty(value = JSON_PROPERTY_UPDATED_BY_API_KEY, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedByApiKey(@javax.annotation.Nullable Map<String, Object> updatedByApiKey) {
    this.updatedByApiKey = updatedByApiKey;
  }


  public FileVersion read(@javax.annotation.Nullable Boolean read) {
    this.read = read;
    return this;
  }

  /**
   * Get read
   * @return read
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_READ, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getRead() {
    return read;
  }


  @JsonProperty(value = JSON_PROPERTY_READ, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRead(@javax.annotation.Nullable Boolean read) {
    this.read = read;
  }


  public FileVersion readAt(@javax.annotation.Nullable OffsetDateTime readAt) {
    this.readAt = JsonNullable.<OffsetDateTime>of(readAt);
    return this;
  }

  /**
   * Get readAt
   * @return readAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getReadAt() {
        return readAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_READ_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getReadAt_JsonNullable() {
    return readAt;
  }
  
  @JsonProperty(JSON_PROPERTY_READ_AT)
  public void setReadAt_JsonNullable(JsonNullable<OffsetDateTime> readAt) {
    this.readAt = readAt;
  }

  public void setReadAt(@javax.annotation.Nullable OffsetDateTime readAt) {
    this.readAt = JsonNullable.<OffsetDateTime>of(readAt);
  }


  public FileVersion readBy(@javax.annotation.Nullable FileActor readBy) {
    this.readBy = JsonNullable.<FileActor>of(readBy);
    return this;
  }

  /**
   * Get readBy
   * @return readBy
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public FileActor getReadBy() {
        return readBy.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_READ_BY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<FileActor> getReadBy_JsonNullable() {
    return readBy;
  }
  
  @JsonProperty(JSON_PROPERTY_READ_BY)
  public void setReadBy_JsonNullable(JsonNullable<FileActor> readBy) {
    this.readBy = readBy;
  }

  public void setReadBy(@javax.annotation.Nullable FileActor readBy) {
    this.readBy = JsonNullable.<FileActor>of(readBy);
  }


  public FileVersion readByApiKey(@javax.annotation.Nullable FileKey readByApiKey) {
    this.readByApiKey = JsonNullable.<FileKey>of(readByApiKey);
    return this;
  }

  /**
   * Get readByApiKey
   * @return readByApiKey
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public FileKey getReadByApiKey() {
        return readByApiKey.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_READ_BY_API_KEY, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<FileKey> getReadByApiKey_JsonNullable() {
    return readByApiKey;
  }
  
  @JsonProperty(JSON_PROPERTY_READ_BY_API_KEY)
  public void setReadByApiKey_JsonNullable(JsonNullable<FileKey> readByApiKey) {
    this.readByApiKey = readByApiKey;
  }

  public void setReadByApiKey(@javax.annotation.Nullable FileKey readByApiKey) {
    this.readByApiKey = JsonNullable.<FileKey>of(readByApiKey);
  }


  /**
   * Return true if this FileVersion object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FileVersion fileVersion = (FileVersion) o;
    return Objects.equals(this.id, fileVersion.id) &&
        Objects.equals(this.fileId, fileVersion.fileId) &&
        Objects.equals(this.name, fileVersion.name) &&
        Objects.equals(this.mimeType, fileVersion.mimeType) &&
        Objects.equals(this.sha256, fileVersion.sha256) &&
        equalsNullable(this.reason, fileVersion.reason) &&
        Objects.equals(this.metaKey, fileVersion.metaKey) &&
        Objects.equals(this.createdBySystem, fileVersion.createdBySystem) &&
        Objects.equals(this.deleted, fileVersion.deleted) &&
        Objects.equals(this.ready, fileVersion.ready) &&
        Objects.equals(this.hasText, fileVersion.hasText) &&
        Objects.equals(this.normalizationRequired, fileVersion.normalizationRequired) &&
        Objects.equals(this.metaReady, fileVersion.metaReady) &&
        Objects.equals(this.versionNumber, fileVersion.versionNumber) &&
        Objects.equals(this.byteSize, fileVersion.byteSize) &&
        Objects.equals(this.createdAt, fileVersion.createdAt) &&
        Objects.equals(this.metaCreatedAt, fileVersion.metaCreatedAt) &&
        Objects.equals(this.createdBy, fileVersion.createdBy) &&
        Objects.equals(this.updatedBy, fileVersion.updatedBy) &&
        Objects.equals(this.createdByAgent, fileVersion.createdByAgent) &&
        Objects.equals(this.updatedByAgent, fileVersion.updatedByAgent) &&
        Objects.equals(this.createdByApiKey, fileVersion.createdByApiKey) &&
        Objects.equals(this.updatedByApiKey, fileVersion.updatedByApiKey) &&
        Objects.equals(this.read, fileVersion.read) &&
        equalsNullable(this.readAt, fileVersion.readAt) &&
        equalsNullable(this.readBy, fileVersion.readBy) &&
        equalsNullable(this.readByApiKey, fileVersion.readByApiKey);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, fileId, name, mimeType, sha256, hashCodeNullable(reason), metaKey, createdBySystem, deleted, ready, hasText, normalizationRequired, metaReady, versionNumber, byteSize, createdAt, metaCreatedAt, createdBy, updatedBy, createdByAgent, updatedByAgent, createdByApiKey, updatedByApiKey, read, hashCodeNullable(readAt), hashCodeNullable(readBy), hashCodeNullable(readByApiKey));
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FileVersion {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    fileId: ").append(toIndentedString(fileId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    sha256: ").append(toIndentedString(sha256)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    metaKey: ").append(toIndentedString(metaKey)).append("\n");
    sb.append("    createdBySystem: ").append(toIndentedString(createdBySystem)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    ready: ").append(toIndentedString(ready)).append("\n");
    sb.append("    hasText: ").append(toIndentedString(hasText)).append("\n");
    sb.append("    normalizationRequired: ").append(toIndentedString(normalizationRequired)).append("\n");
    sb.append("    metaReady: ").append(toIndentedString(metaReady)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    byteSize: ").append(toIndentedString(byteSize)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    metaCreatedAt: ").append(toIndentedString(metaCreatedAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    updatedBy: ").append(toIndentedString(updatedBy)).append("\n");
    sb.append("    createdByAgent: ").append(toIndentedString(createdByAgent)).append("\n");
    sb.append("    updatedByAgent: ").append(toIndentedString(updatedByAgent)).append("\n");
    sb.append("    createdByApiKey: ").append(toIndentedString(createdByApiKey)).append("\n");
    sb.append("    updatedByApiKey: ").append(toIndentedString(updatedByApiKey)).append("\n");
    sb.append("    read: ").append(toIndentedString(read)).append("\n");
    sb.append("    readAt: ").append(toIndentedString(readAt)).append("\n");
    sb.append("    readBy: ").append(toIndentedString(readBy)).append("\n");
    sb.append("    readByApiKey: ").append(toIndentedString(readByApiKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

