/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.EmailSenderAllowlist;
import com.revdoku.api.model.MailboxEmailAliasesInner;
import com.revdoku.api.model.MailboxEmailAssignment;
import com.revdoku.api.model.MailboxEmailAvailableDomainsInner;
import com.revdoku.api.model.MailboxEmailCustomization;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Authorized mailbox reads include the email address. Creation and opt-in reads also include receiving settings; use the emails collection for a durable arrival cursor.
 */
@JsonPropertyOrder({
  MailboxEmail.JSON_PROPERTY_ADDRESS,
  MailboxEmail.JSON_PROPERTY_RECEIVED_COUNT,
  MailboxEmail.JSON_PROPERTY_LAST_RECEIVED_AT,
  MailboxEmail.JSON_PROPERTY_LAST_RECEIVED_PATH,
  MailboxEmail.JSON_PROPERTY_BLOCKED_REASON,
  MailboxEmail.JSON_PROPERTY_AVAILABLE_DOMAINS,
  MailboxEmail.JSON_PROPERTY_ASSIGNMENT,
  MailboxEmail.JSON_PROPERTY_CUSTOMIZATION,
  MailboxEmail.JSON_PROPERTY_RECEIVING_ENABLED,
  MailboxEmail.JSON_PROPERTY_SENDER_ALLOWLIST,
  MailboxEmail.JSON_PROPERTY_USERNAME,
  MailboxEmail.JSON_PROPERTY_SENDING_ENABLED,
  MailboxEmail.JSON_PROPERTY_ALIASES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class MailboxEmail {
  public static final String JSON_PROPERTY_ADDRESS = "address";
  private JsonNullable<String> address = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_RECEIVED_COUNT = "received_count";
  @javax.annotation.Nullable
  private Long receivedCount;

  public static final String JSON_PROPERTY_LAST_RECEIVED_AT = "last_received_at";
  private JsonNullable<OffsetDateTime> lastReceivedAt = JsonNullable.<OffsetDateTime>undefined();

  public static final String JSON_PROPERTY_LAST_RECEIVED_PATH = "last_received_path";
  private JsonNullable<String> lastReceivedPath = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_BLOCKED_REASON = "blocked_reason";
  private JsonNullable<String> blockedReason = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_AVAILABLE_DOMAINS = "available_domains";
  @javax.annotation.Nullable
  private List<MailboxEmailAvailableDomainsInner> availableDomains = new ArrayList<>();

  public static final String JSON_PROPERTY_ASSIGNMENT = "assignment";
  @javax.annotation.Nullable
  private MailboxEmailAssignment assignment;

  public static final String JSON_PROPERTY_CUSTOMIZATION = "customization";
  @javax.annotation.Nullable
  private MailboxEmailCustomization customization;

  public static final String JSON_PROPERTY_RECEIVING_ENABLED = "receiving_enabled";
  @javax.annotation.Nullable
  private Boolean receivingEnabled;

  public static final String JSON_PROPERTY_SENDER_ALLOWLIST = "sender_allowlist";
  @javax.annotation.Nullable
  private EmailSenderAllowlist senderAllowlist;

  public static final String JSON_PROPERTY_USERNAME = "username";
  private JsonNullable<String> username = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_SENDING_ENABLED = "sending_enabled";
  @javax.annotation.Nullable
  private Boolean sendingEnabled;

  public static final String JSON_PROPERTY_ALIASES = "aliases";
  @javax.annotation.Nullable
  private List<MailboxEmailAliasesInner> aliases = new ArrayList<>();

  public MailboxEmail() { 
  }

  public MailboxEmail address(@javax.annotation.Nullable String address) {
    this.address = JsonNullable.<String>of(address);
    return this;
  }

  /**
   * Get address
   * @return address
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getAddress() {
        return address.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_ADDRESS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getAddress_JsonNullable() {
    return address;
  }
  
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  public void setAddress_JsonNullable(JsonNullable<String> address) {
    this.address = address;
  }

  public void setAddress(@javax.annotation.Nullable String address) {
    this.address = JsonNullable.<String>of(address);
  }


  public MailboxEmail receivedCount(@javax.annotation.Nullable Long receivedCount) {
    this.receivedCount = receivedCount;
    return this;
  }

  /**
   * Get receivedCount
   * minimum: 0
   * @return receivedCount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECEIVED_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getReceivedCount() {
    return receivedCount;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVED_COUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivedCount(@javax.annotation.Nullable Long receivedCount) {
    this.receivedCount = receivedCount;
  }


  public MailboxEmail lastReceivedAt(@javax.annotation.Nullable OffsetDateTime lastReceivedAt) {
    this.lastReceivedAt = JsonNullable.<OffsetDateTime>of(lastReceivedAt);
    return this;
  }

  /**
   * Get lastReceivedAt
   * @return lastReceivedAt
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public OffsetDateTime getLastReceivedAt() {
        return lastReceivedAt.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_RECEIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<OffsetDateTime> getLastReceivedAt_JsonNullable() {
    return lastReceivedAt;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_RECEIVED_AT)
  public void setLastReceivedAt_JsonNullable(JsonNullable<OffsetDateTime> lastReceivedAt) {
    this.lastReceivedAt = lastReceivedAt;
  }

  public void setLastReceivedAt(@javax.annotation.Nullable OffsetDateTime lastReceivedAt) {
    this.lastReceivedAt = JsonNullable.<OffsetDateTime>of(lastReceivedAt);
  }


  public MailboxEmail lastReceivedPath(@javax.annotation.Nullable String lastReceivedPath) {
    this.lastReceivedPath = JsonNullable.<String>of(lastReceivedPath);
    return this;
  }

  /**
   * Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
   * @return lastReceivedPath
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getLastReceivedPath() {
        return lastReceivedPath.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_LAST_RECEIVED_PATH, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getLastReceivedPath_JsonNullable() {
    return lastReceivedPath;
  }
  
  @JsonProperty(JSON_PROPERTY_LAST_RECEIVED_PATH)
  public void setLastReceivedPath_JsonNullable(JsonNullable<String> lastReceivedPath) {
    this.lastReceivedPath = lastReceivedPath;
  }

  public void setLastReceivedPath(@javax.annotation.Nullable String lastReceivedPath) {
    this.lastReceivedPath = JsonNullable.<String>of(lastReceivedPath);
  }


  public MailboxEmail blockedReason(@javax.annotation.Nullable String blockedReason) {
    this.blockedReason = JsonNullable.<String>of(blockedReason);
    return this;
  }

  /**
   * Why receiving is unavailable; omitted when receiving_enabled is true.
   * @return blockedReason
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getBlockedReason() {
        return blockedReason.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_BLOCKED_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getBlockedReason_JsonNullable() {
    return blockedReason;
  }
  
  @JsonProperty(JSON_PROPERTY_BLOCKED_REASON)
  public void setBlockedReason_JsonNullable(JsonNullable<String> blockedReason) {
    this.blockedReason = blockedReason;
  }

  public void setBlockedReason(@javax.annotation.Nullable String blockedReason) {
    this.blockedReason = JsonNullable.<String>of(blockedReason);
  }


  public MailboxEmail availableDomains(@javax.annotation.Nullable List<MailboxEmailAvailableDomainsInner> availableDomains) {
    this.availableDomains = availableDomains;
    return this;
  }

  public MailboxEmail addAvailableDomainsItem(MailboxEmailAvailableDomainsInner availableDomainsItem) {
    if (this.availableDomains == null) {
      this.availableDomains = new ArrayList<>();
    }
    this.availableDomains.add(availableDomainsItem);
    return this;
  }

  /**
   * Get availableDomains
   * @return availableDomains
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DOMAINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<MailboxEmailAvailableDomainsInner> getAvailableDomains() {
    return availableDomains;
  }


  @JsonProperty(value = JSON_PROPERTY_AVAILABLE_DOMAINS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAvailableDomains(@javax.annotation.Nullable List<MailboxEmailAvailableDomainsInner> availableDomains) {
    this.availableDomains = availableDomains;
  }


  public MailboxEmail assignment(@javax.annotation.Nullable MailboxEmailAssignment assignment) {
    this.assignment = assignment;
    return this;
  }

  /**
   * Get assignment
   * @return assignment
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ASSIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MailboxEmailAssignment getAssignment() {
    return assignment;
  }


  @JsonProperty(value = JSON_PROPERTY_ASSIGNMENT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAssignment(@javax.annotation.Nullable MailboxEmailAssignment assignment) {
    this.assignment = assignment;
  }


  public MailboxEmail customization(@javax.annotation.Nullable MailboxEmailCustomization customization) {
    this.customization = customization;
    return this;
  }

  /**
   * Get customization
   * @return customization
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CUSTOMIZATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MailboxEmailCustomization getCustomization() {
    return customization;
  }


  @JsonProperty(value = JSON_PROPERTY_CUSTOMIZATION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCustomization(@javax.annotation.Nullable MailboxEmailCustomization customization) {
    this.customization = customization;
  }


  public MailboxEmail receivingEnabled(@javax.annotation.Nullable Boolean receivingEnabled) {
    this.receivingEnabled = receivingEnabled;
    return this;
  }

  /**
   * Whether this mailbox can currently receive email. False when configuration, account state, quota or routing prevents receiving.
   * @return receivingEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_RECEIVING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getReceivingEnabled() {
    return receivingEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_RECEIVING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReceivingEnabled(@javax.annotation.Nullable Boolean receivingEnabled) {
    this.receivingEnabled = receivingEnabled;
  }


  public MailboxEmail senderAllowlist(@javax.annotation.Nullable EmailSenderAllowlist senderAllowlist) {
    this.senderAllowlist = senderAllowlist;
    return this;
  }

  /**
   * Get senderAllowlist
   * @return senderAllowlist
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDER_ALLOWLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EmailSenderAllowlist getSenderAllowlist() {
    return senderAllowlist;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDER_ALLOWLIST, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSenderAllowlist(@javax.annotation.Nullable EmailSenderAllowlist senderAllowlist) {
    this.senderAllowlist = senderAllowlist;
  }


  public MailboxEmail username(@javax.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @javax.annotation.Nullable
  @JsonIgnore
  public String getUsername() {
        return username.orElse(null);
  }

  @JsonProperty(value = JSON_PROPERTY_USERNAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public JsonNullable<String> getUsername_JsonNullable() {
    return username;
  }
  
  @JsonProperty(JSON_PROPERTY_USERNAME)
  public void setUsername_JsonNullable(JsonNullable<String> username) {
    this.username = username;
  }

  public void setUsername(@javax.annotation.Nullable String username) {
    this.username = JsonNullable.<String>of(username);
  }


  public MailboxEmail sendingEnabled(@javax.annotation.Nullable Boolean sendingEnabled) {
    this.sendingEnabled = sendingEnabled;
    return this;
  }

  /**
   * Always false. Sending is not implemented.
   * @return sendingEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SENDING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSendingEnabled() {
    return sendingEnabled;
  }


  @JsonProperty(value = JSON_PROPERTY_SENDING_ENABLED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSendingEnabled(@javax.annotation.Nullable Boolean sendingEnabled) {
    this.sendingEnabled = sendingEnabled;
  }


  public MailboxEmail aliases(@javax.annotation.Nullable List<MailboxEmailAliasesInner> aliases) {
    this.aliases = aliases;
    return this;
  }

  public MailboxEmail addAliasesItem(MailboxEmailAliasesInner aliasesItem) {
    if (this.aliases == null) {
      this.aliases = new ArrayList<>();
    }
    this.aliases.add(aliasesItem);
    return this;
  }

  /**
   * Get aliases
   * @return aliases
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ALIASES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<MailboxEmailAliasesInner> getAliases() {
    return aliases;
  }


  @JsonProperty(value = JSON_PROPERTY_ALIASES, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAliases(@javax.annotation.Nullable List<MailboxEmailAliasesInner> aliases) {
    this.aliases = aliases;
  }


  /**
   * Return true if this MailboxEmail object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MailboxEmail mailboxEmail = (MailboxEmail) o;
    return equalsNullable(this.address, mailboxEmail.address) &&
        Objects.equals(this.receivedCount, mailboxEmail.receivedCount) &&
        equalsNullable(this.lastReceivedAt, mailboxEmail.lastReceivedAt) &&
        equalsNullable(this.lastReceivedPath, mailboxEmail.lastReceivedPath) &&
        equalsNullable(this.blockedReason, mailboxEmail.blockedReason) &&
        Objects.equals(this.availableDomains, mailboxEmail.availableDomains) &&
        Objects.equals(this.assignment, mailboxEmail.assignment) &&
        Objects.equals(this.customization, mailboxEmail.customization) &&
        Objects.equals(this.receivingEnabled, mailboxEmail.receivingEnabled) &&
        Objects.equals(this.senderAllowlist, mailboxEmail.senderAllowlist) &&
        equalsNullable(this.username, mailboxEmail.username) &&
        Objects.equals(this.sendingEnabled, mailboxEmail.sendingEnabled) &&
        Objects.equals(this.aliases, mailboxEmail.aliases);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(hashCodeNullable(address), receivedCount, hashCodeNullable(lastReceivedAt), hashCodeNullable(lastReceivedPath), hashCodeNullable(blockedReason), availableDomains, assignment, customization, receivingEnabled, senderAllowlist, hashCodeNullable(username), sendingEnabled, aliases);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MailboxEmail {\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    receivedCount: ").append(toIndentedString(receivedCount)).append("\n");
    sb.append("    lastReceivedAt: ").append(toIndentedString(lastReceivedAt)).append("\n");
    sb.append("    lastReceivedPath: ").append(toIndentedString(lastReceivedPath)).append("\n");
    sb.append("    blockedReason: ").append(toIndentedString(blockedReason)).append("\n");
    sb.append("    availableDomains: ").append(toIndentedString(availableDomains)).append("\n");
    sb.append("    assignment: ").append(toIndentedString(assignment)).append("\n");
    sb.append("    customization: ").append(toIndentedString(customization)).append("\n");
    sb.append("    receivingEnabled: ").append(toIndentedString(receivingEnabled)).append("\n");
    sb.append("    senderAllowlist: ").append(toIndentedString(senderAllowlist)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    sendingEnabled: ").append(toIndentedString(sendingEnabled)).append("\n");
    sb.append("    aliases: ").append(toIndentedString(aliases)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

