/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.FileVersion;
import com.revdoku.api.model.MailboxFile;
import com.revdoku.api.model.StorageUpload;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * A new upload returns signed_id and direct_upload. Identical content returns skipped&#x3D;true, duplicate&#x3D;true, file and version without a storage upload.
 */
@JsonPropertyOrder({
  PreparedFileUpload.JSON_PROPERTY_SIGNED_ID,
  PreparedFileUpload.JSON_PROPERTY_FILENAME,
  PreparedFileUpload.JSON_PROPERTY_BYTE_SIZE,
  PreparedFileUpload.JSON_PROPERTY_CHECKSUM,
  PreparedFileUpload.JSON_PROPERTY_CONTENT_TYPE,
  PreparedFileUpload.JSON_PROPERTY_SERVICE_NAME,
  PreparedFileUpload.JSON_PROPERTY_DIRECT_UPLOAD,
  PreparedFileUpload.JSON_PROPERTY_FILE,
  PreparedFileUpload.JSON_PROPERTY_VERSION,
  PreparedFileUpload.JSON_PROPERTY_SKIPPED,
  PreparedFileUpload.JSON_PROPERTY_DUPLICATE,
  PreparedFileUpload.JSON_PROPERTY_REASON,
  PreparedFileUpload.JSON_PROPERTY_DETAILS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class PreparedFileUpload {
  public static final String JSON_PROPERTY_SIGNED_ID = "signed_id";
  @javax.annotation.Nullable
  private String signedId;

  public static final String JSON_PROPERTY_FILENAME = "filename";
  @javax.annotation.Nullable
  private String filename;

  public static final String JSON_PROPERTY_BYTE_SIZE = "byte_size";
  @javax.annotation.Nullable
  private Long byteSize;

  public static final String JSON_PROPERTY_CHECKSUM = "checksum";
  @javax.annotation.Nullable
  private String checksum;

  public static final String JSON_PROPERTY_CONTENT_TYPE = "content_type";
  @javax.annotation.Nullable
  private String contentType;

  public static final String JSON_PROPERTY_SERVICE_NAME = "service_name";
  @javax.annotation.Nullable
  private String serviceName;

  public static final String JSON_PROPERTY_DIRECT_UPLOAD = "direct_upload";
  @javax.annotation.Nullable
  private StorageUpload directUpload;

  public static final String JSON_PROPERTY_FILE = "file";
  @javax.annotation.Nullable
  private MailboxFile _file;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nullable
  private FileVersion version;

  public static final String JSON_PROPERTY_SKIPPED = "skipped";
  @javax.annotation.Nullable
  private Boolean skipped;

  public static final String JSON_PROPERTY_DUPLICATE = "duplicate";
  @javax.annotation.Nullable
  private Boolean duplicate;

  public static final String JSON_PROPERTY_REASON = "reason";
  @javax.annotation.Nullable
  private String reason;

  public static final String JSON_PROPERTY_DETAILS = "details";
  @javax.annotation.Nullable
  private Map<String, Object> details = new HashMap<>();

  public PreparedFileUpload() { 
  }

  public PreparedFileUpload signedId(@javax.annotation.Nullable String signedId) {
    this.signedId = signedId;
    return this;
  }

  /**
   * Get signedId
   * @return signedId
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SIGNED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getSignedId() {
    return signedId;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNED_ID, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSignedId(@javax.annotation.Nullable String signedId) {
    this.signedId = signedId;
  }


  public PreparedFileUpload filename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
    return this;
  }

  /**
   * Get filename
   * @return filename
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFilename() {
    return filename;
  }


  @JsonProperty(value = JSON_PROPERTY_FILENAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFilename(@javax.annotation.Nullable String filename) {
    this.filename = filename;
  }


  public PreparedFileUpload byteSize(@javax.annotation.Nullable Long byteSize) {
    this.byteSize = byteSize;
    return this;
  }

  /**
   * Get byteSize
   * @return byteSize
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_BYTE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Long getByteSize() {
    return byteSize;
  }


  @JsonProperty(value = JSON_PROPERTY_BYTE_SIZE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setByteSize(@javax.annotation.Nullable Long byteSize) {
    this.byteSize = byteSize;
  }


  public PreparedFileUpload checksum(@javax.annotation.Nullable String checksum) {
    this.checksum = checksum;
    return this;
  }

  /**
   * Get checksum
   * @return checksum
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CHECKSUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getChecksum() {
    return checksum;
  }


  @JsonProperty(value = JSON_PROPERTY_CHECKSUM, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChecksum(@javax.annotation.Nullable String checksum) {
    this.checksum = checksum;
  }


  public PreparedFileUpload contentType(@javax.annotation.Nullable String contentType) {
    this.contentType = contentType;
    return this;
  }

  /**
   * Get contentType
   * @return contentType
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getContentType() {
    return contentType;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTENT_TYPE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContentType(@javax.annotation.Nullable String contentType) {
    this.contentType = contentType;
  }


  public PreparedFileUpload serviceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
    return this;
  }

  /**
   * Get serviceName
   * @return serviceName
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getServiceName() {
    return serviceName;
  }


  @JsonProperty(value = JSON_PROPERTY_SERVICE_NAME, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceName(@javax.annotation.Nullable String serviceName) {
    this.serviceName = serviceName;
  }


  public PreparedFileUpload directUpload(@javax.annotation.Nullable StorageUpload directUpload) {
    this.directUpload = directUpload;
    return this;
  }

  /**
   * Get directUpload
   * @return directUpload
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DIRECT_UPLOAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StorageUpload getDirectUpload() {
    return directUpload;
  }


  @JsonProperty(value = JSON_PROPERTY_DIRECT_UPLOAD, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectUpload(@javax.annotation.Nullable StorageUpload directUpload) {
    this.directUpload = directUpload;
  }


  public PreparedFileUpload _file(@javax.annotation.Nullable MailboxFile _file) {
    this._file = _file;
    return this;
  }

  /**
   * Get _file
   * @return _file
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public MailboxFile getFile() {
    return _file;
  }


  @JsonProperty(value = JSON_PROPERTY_FILE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFile(@javax.annotation.Nullable MailboxFile _file) {
    this._file = _file;
  }


  public PreparedFileUpload version(@javax.annotation.Nullable FileVersion version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public FileVersion getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVersion(@javax.annotation.Nullable FileVersion version) {
    this.version = version;
  }


  public PreparedFileUpload skipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
    return this;
  }

  /**
   * Get skipped
   * @return skipped
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_SKIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getSkipped() {
    return skipped;
  }


  @JsonProperty(value = JSON_PROPERTY_SKIPPED, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSkipped(@javax.annotation.Nullable Boolean skipped) {
    this.skipped = skipped;
  }


  public PreparedFileUpload duplicate(@javax.annotation.Nullable Boolean duplicate) {
    this.duplicate = duplicate;
    return this;
  }

  /**
   * Get duplicate
   * @return duplicate
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DUPLICATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getDuplicate() {
    return duplicate;
  }


  @JsonProperty(value = JSON_PROPERTY_DUPLICATE, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDuplicate(@javax.annotation.Nullable Boolean duplicate) {
    this.duplicate = duplicate;
  }


  public PreparedFileUpload reason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
    return this;
  }

  /**
   * Get reason
   * @return reason
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getReason() {
    return reason;
  }


  @JsonProperty(value = JSON_PROPERTY_REASON, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setReason(@javax.annotation.Nullable String reason) {
    this.reason = reason;
  }


  public PreparedFileUpload details(@javax.annotation.Nullable Map<String, Object> details) {
    this.details = details;
    return this;
  }

  public PreparedFileUpload putDetailsItem(String key, Object detailsItem) {
    if (this.details == null) {
      this.details = new HashMap<>();
    }
    this.details.put(key, detailsItem);
    return this;
  }

  /**
   * Get details
   * @return details
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public Map<String, Object> getDetails() {
    return details;
  }


  @JsonProperty(value = JSON_PROPERTY_DETAILS, required = false)
  @JsonInclude(content = JsonInclude.Include.ALWAYS, value = JsonInclude.Include.USE_DEFAULTS)
  public void setDetails(@javax.annotation.Nullable Map<String, Object> details) {
    this.details = details;
  }


  /**
   * Return true if this PreparedFileUpload object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PreparedFileUpload preparedFileUpload = (PreparedFileUpload) o;
    return Objects.equals(this.signedId, preparedFileUpload.signedId) &&
        Objects.equals(this.filename, preparedFileUpload.filename) &&
        Objects.equals(this.byteSize, preparedFileUpload.byteSize) &&
        Objects.equals(this.checksum, preparedFileUpload.checksum) &&
        Objects.equals(this.contentType, preparedFileUpload.contentType) &&
        Objects.equals(this.serviceName, preparedFileUpload.serviceName) &&
        Objects.equals(this.directUpload, preparedFileUpload.directUpload) &&
        Objects.equals(this._file, preparedFileUpload._file) &&
        Objects.equals(this.version, preparedFileUpload.version) &&
        Objects.equals(this.skipped, preparedFileUpload.skipped) &&
        Objects.equals(this.duplicate, preparedFileUpload.duplicate) &&
        Objects.equals(this.reason, preparedFileUpload.reason) &&
        Objects.equals(this.details, preparedFileUpload.details);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signedId, filename, byteSize, checksum, contentType, serviceName, directUpload, _file, version, skipped, duplicate, reason, details);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PreparedFileUpload {\n");
    sb.append("    signedId: ").append(toIndentedString(signedId)).append("\n");
    sb.append("    filename: ").append(toIndentedString(filename)).append("\n");
    sb.append("    byteSize: ").append(toIndentedString(byteSize)).append("\n");
    sb.append("    checksum: ").append(toIndentedString(checksum)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    serviceName: ").append(toIndentedString(serviceName)).append("\n");
    sb.append("    directUpload: ").append(toIndentedString(directUpload)).append("\n");
    sb.append("    _file: ").append(toIndentedString(_file)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    skipped: ").append(toIndentedString(skipped)).append("\n");
    sb.append("    duplicate: ").append(toIndentedString(duplicate)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    details: ").append(toIndentedString(details)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

