/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.revdoku.api.model.SignupChallenge;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * StartAgentSignup202ResponseData
 */
@JsonPropertyOrder({
  StartAgentSignup202ResponseData.JSON_PROPERTY_SIGNUP
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class StartAgentSignup202ResponseData {
  public static final String JSON_PROPERTY_SIGNUP = "signup";
  @javax.annotation.Nonnull
  private SignupChallenge signup;

  public StartAgentSignup202ResponseData() { 
  }

  public StartAgentSignup202ResponseData signup(@javax.annotation.Nonnull SignupChallenge signup) {
    this.signup = signup;
    return this;
  }

  /**
   * Get signup
   * @return signup
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNUP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public SignupChallenge getSignup() {
    return signup;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNUP, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignup(@javax.annotation.Nonnull SignupChallenge signup) {
    this.signup = signup;
  }


  /**
   * Return true if this startAgentSignup_202_response_data object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StartAgentSignup202ResponseData startAgentSignup202ResponseData = (StartAgentSignup202ResponseData) o;
    return Objects.equals(this.signup, startAgentSignup202ResponseData.signup);
  }

  @Override
  public int hashCode() {
    return Objects.hash(signup);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StartAgentSignup202ResponseData {\n");
    sb.append("    signup: ").append(toIndentedString(signup)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

