/*
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.revdoku.api.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * VerifyAgentSignupRequest
 */
@JsonPropertyOrder({
  VerifyAgentSignupRequest.JSON_PROPERTY_CODE,
  VerifyAgentSignupRequest.JSON_PROPERTY_SIGNUP_TOKEN
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.25.0")
public class VerifyAgentSignupRequest {
  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nonnull
  private String code;

  public static final String JSON_PROPERTY_SIGNUP_TOKEN = "signup_token";
  @javax.annotation.Nonnull
  private String signupToken;

  public VerifyAgentSignupRequest() { 
  }

  public VerifyAgentSignupRequest code(@javax.annotation.Nonnull String code) {
    this.code = code;
    return this;
  }

  /**
   * Six-digit email verification code.
   * @return code
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCode() {
    return code;
  }


  @JsonProperty(value = JSON_PROPERTY_CODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(@javax.annotation.Nonnull String code) {
    this.code = code;
  }


  public VerifyAgentSignupRequest signupToken(@javax.annotation.Nonnull String signupToken) {
    this.signupToken = signupToken;
    return this;
  }

  /**
   * Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
   * @return signupToken
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SIGNUP_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getSignupToken() {
    return signupToken;
  }


  @JsonProperty(value = JSON_PROPERTY_SIGNUP_TOKEN, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSignupToken(@javax.annotation.Nonnull String signupToken) {
    this.signupToken = signupToken;
  }


  /**
   * Return true if this verifyAgentSignup_request object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyAgentSignupRequest verifyAgentSignupRequest = (VerifyAgentSignupRequest) o;
    return Objects.equals(this.code, verifyAgentSignupRequest.code) &&
        Objects.equals(this.signupToken, verifyAgentSignupRequest.signupToken);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, signupToken);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyAgentSignupRequest {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    signupToken: ").append(toIndentedString(signupToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    return o == null ? "null" : o.toString().replace("\n", "\n    ");
  }
}

