/* tslint:disable */
/* eslint-disable */
/**
 * Revdoku public agent API
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SignupPoliciesResponseData } from './SignupPoliciesResponseData';
import {
    SignupPoliciesResponseDataFromJSON,
    SignupPoliciesResponseDataFromJSONTyped,
    SignupPoliciesResponseDataToJSON,
    SignupPoliciesResponseDataToJSONTyped,
} from './SignupPoliciesResponseData';

/**
 * 
 * @export
 * @interface SignupPoliciesResponse
 */
export interface SignupPoliciesResponse {
    /**
     * 
     */
    success: boolean;
    /**
     * 
     */
    data: SignupPoliciesResponseData;
}

/**
 * Check if a given object implements the SignupPoliciesResponse interface.
 */
export function instanceOfSignupPoliciesResponse(value: object): value is SignupPoliciesResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    if (!('data' in value) || value['data'] === undefined) return false;
    return true;
}

export function SignupPoliciesResponseFromJSON(json: any): SignupPoliciesResponse {
    return SignupPoliciesResponseFromJSONTyped(json, false);
}

export function SignupPoliciesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignupPoliciesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'data': SignupPoliciesResponseDataFromJSON(json['data']),
    };
}

export function SignupPoliciesResponseToJSON(json: any): SignupPoliciesResponse {
    return SignupPoliciesResponseToJSONTyped(json, false);
}

export function SignupPoliciesResponseToJSONTyped(value?: SignupPoliciesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'data': SignupPoliciesResponseDataToJSON(value['data']),
    };
}

