/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DecodedIncomingMessageAttachmentsInner {
    /// Relative to message folder.
    #[serde(rename = "path")]
    pub path: String,
    #[serde(rename = "original_filename")]
    pub original_filename: String,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "size_bytes")]
    pub size_bytes: i64,
    /// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Origin>,
}

impl DecodedIncomingMessageAttachmentsInner {
    pub fn new(path: String, original_filename: String, content_type: String, size_bytes: i64) -> DecodedIncomingMessageAttachmentsInner {
        DecodedIncomingMessageAttachmentsInner {
            path,
            original_filename,
            content_type,
            size_bytes,
            origin: None,
        }
    }
}
/// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Origin {
    #[serde(rename = "original")]
    Original,
    #[serde(rename = "forwarder")]
    Forwarder,
    #[serde(rename = "forwarded_message")]
    ForwardedMessage,
    #[serde(rename = "unspecified")]
    Unspecified,
}

impl Default for Origin {
    fn default() -> Origin {
        Self::Original
    }
}

