/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.535
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct EmailAttachment {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "content_type", deserialize_with = "Option::deserialize")]
    pub content_type: Option<String>,
    #[serde(rename = "size_bytes")]
    pub size_bytes: i64,
    /// Present only with include_storage=true.
    #[serde(rename = "version_id", skip_serializing_if = "Option::is_none")]
    pub version_id: Option<String>,
    /// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<Origin>,
}

impl EmailAttachment {
    pub fn new(id: String, filename: String, content_type: Option<String>, size_bytes: i64) -> EmailAttachment {
        EmailAttachment {
            id,
            filename,
            content_type,
            size_bytes,
            version_id: None,
            origin: None,
        }
    }
}
/// For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Origin {
    #[serde(rename = "original")]
    Original,
    #[serde(rename = "forwarder")]
    Forwarder,
    #[serde(rename = "forwarded_message")]
    ForwardedMessage,
    #[serde(rename = "unspecified")]
    Unspecified,
}

impl Default for Origin {
    fn default() -> Origin {
        Self::Original
    }
}

