/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetAccountLimits200ResponseDataUsage : Present only for full-account administrator credentials and full-account browser sessions.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetAccountLimits200ResponseDataUsage {
    #[serde(rename = "mailbox_creations", skip_serializing_if = "Option::is_none")]
    pub mailbox_creations: Option<Box<models::GetAccountLimits200ResponseDataUsageMailboxCreations>>,
}

impl GetAccountLimits200ResponseDataUsage {
    /// Present only for full-account administrator credentials and full-account browser sessions.
    pub fn new() -> GetAccountLimits200ResponseDataUsage {
        GetAccountLimits200ResponseDataUsage {
            mailbox_creations: None,
        }
    }
}

