/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetEmailOriginalDownloadUrl200ResponseData {
    #[serde(rename = "download")]
    pub download: Box<models::EmailDownload>,
}

impl GetEmailOriginalDownloadUrl200ResponseData {
    pub fn new(download: models::EmailDownload) -> GetEmailOriginalDownloadUrl200ResponseData {
        GetEmailOriginalDownloadUrl200ResponseData {
            download: Box::new(download),
        }
    }
}

