/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetMailboxEmailSettings200Response {
    #[serde(rename = "data")]
    pub data: Box<models::MailboxEmail>,
    #[serde(rename = "success")]
    pub success: bool,
}

impl GetMailboxEmailSettings200Response {
    pub fn new(data: models::MailboxEmail, success: bool) -> GetMailboxEmailSettings200Response {
        GetMailboxEmailSettings200Response {
            data: Box::new(data),
            success,
        }
    }
}

