/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.527
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MailboxEmailActivity {
    #[serde(rename = "received_count", skip_serializing_if = "Option::is_none")]
    pub received_count: Option<i32>,
    #[serde(rename = "last_received_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_received_at: Option<Option<chrono::DateTime<chrono::FixedOffset>>>,
    /// Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
    #[serde(rename = "last_received_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_received_path: Option<Option<String>>,
}

impl MailboxEmailActivity {
    pub fn new() -> MailboxEmailActivity {
        MailboxEmailActivity {
            received_count: None,
            last_received_at: None,
            last_received_path: None,
        }
    }
}

