/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PreparedFileUpload : A new upload returns signed_id and direct_upload. Identical content returns skipped=true, duplicate=true, file and version without a storage upload.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PreparedFileUpload {
    #[serde(rename = "signed_id", skip_serializing_if = "Option::is_none")]
    pub signed_id: Option<String>,
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,
    #[serde(rename = "byte_size", skip_serializing_if = "Option::is_none")]
    pub byte_size: Option<i64>,
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<String>,
    #[serde(rename = "content_type", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "service_name", skip_serializing_if = "Option::is_none")]
    pub service_name: Option<String>,
    #[serde(rename = "direct_upload", skip_serializing_if = "Option::is_none")]
    pub direct_upload: Option<Box<models::StorageUpload>>,
    #[serde(rename = "file", skip_serializing_if = "Option::is_none")]
    pub file: Option<Box<models::MailboxFile>>,
    #[serde(rename = "version", skip_serializing_if = "Option::is_none")]
    pub version: Option<Box<models::FileVersion>>,
    #[serde(rename = "skipped", skip_serializing_if = "Option::is_none")]
    pub skipped: Option<bool>,
    #[serde(rename = "duplicate", skip_serializing_if = "Option::is_none")]
    pub duplicate: Option<bool>,
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    #[serde(rename = "details", skip_serializing_if = "Option::is_none")]
    pub details: Option<std::collections::HashMap<String, serde_json::Value>>,
}

impl PreparedFileUpload {
    /// A new upload returns signed_id and direct_upload. Identical content returns skipped=true, duplicate=true, file and version without a storage upload.
    pub fn new() -> PreparedFileUpload {
        PreparedFileUpload {
            signed_id: None,
            filename: None,
            byte_size: None,
            checksum: None,
            content_type: None,
            service_name: None,
            direct_upload: None,
            file: None,
            version: None,
            skipped: None,
            duplicate: None,
            reason: None,
            details: None,
        }
    }
}

