/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StartAgentSignupRequest {
    /// Email address for the new account.
    #[serde(rename = "email")]
    pub email: String,
    /// Agree to the Terms (https://revdoku.com/terms) and Acceptable Use Policy (https://revdoku.com/acceptable-use), and acknowledge the Privacy Policy (https://revdoku.com/privacy).
    #[serde(rename = "accept_terms_and_policy")]
    pub accept_terms_and_policy: bool,
}

impl StartAgentSignupRequest {
    pub fn new(email: String, accept_terms_and_policy: bool) -> StartAgentSignupRequest {
        StartAgentSignupRequest {
            email,
            accept_terms_and_policy,
        }
    }
}

