/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Create your account at https://app.revdoku.com/users/sign_up. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateEmail200ResponseData {
    #[serde(rename = "email")]
    pub email: Box<models::EmailSummary>,
}

impl UpdateEmail200ResponseData {
    pub fn new(email: models::EmailSummary) -> UpdateEmail200ResponseData {
        UpdateEmail200ResponseData {
            email: Box::new(email),
        }
    }
}

