/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 2.0.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UploadBlob {
    #[serde(rename = "filename")]
    pub filename: String,
    #[serde(rename = "byte_size")]
    pub byte_size: i64,
    #[serde(rename = "checksum")]
    pub checksum: String,
    #[serde(rename = "content_type")]
    pub content_type: String,
    #[serde(rename = "sha256")]
    pub sha256: String,
    #[serde(rename = "purpose")]
    pub purpose: Purpose,
}

impl UploadBlob {
    pub fn new(filename: String, byte_size: i64, checksum: String, content_type: String, sha256: String, purpose: Purpose) -> UploadBlob {
        UploadBlob {
            filename,
            byte_size,
            checksum,
            content_type,
            sha256,
            purpose,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Purpose {
    #[serde(rename = "mailbox_file")]
    MailboxFile,
}

impl Default for Purpose {
    fn default() -> Purpose {
        Self::MailboxFile
    }
}

