/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyAgentSignup200ResponseDataSignup {
    #[serde(rename = "status")]
    pub status: Status,
    #[serde(rename = "account_id")]
    pub account_id: String,
    #[serde(rename = "mailbox_id")]
    pub mailbox_id: String,
}

impl VerifyAgentSignup200ResponseDataSignup {
    pub fn new(status: Status, account_id: String, mailbox_id: String) -> VerifyAgentSignup200ResponseDataSignup {
        VerifyAgentSignup200ResponseDataSignup {
            status,
            account_id,
            mailbox_id,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "completed")]
    Completed,
}

impl Default for Status {
    fn default() -> Status {
        Self::Completed
    }
}

