/*
 * Revdoku public agent API
 *
 * Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.
 *
 * The version of the OpenAPI document: 1.0.526
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VerifyAgentSignupRequest {
    /// Required until the challenge is verified; collect privately, never in chat.
    #[serde(rename = "code", skip_serializing_if = "Option::is_none")]
    pub code: Option<String>,
    /// Optional exact name for the first mailbox. Omit to generate a name. Platform reserved and retired name rules apply.
    #[serde(rename = "username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    /// Private signup token returned by the first request. Send only in the JSON body; never log it or show it in chat.
    #[serde(rename = "signup_token")]
    pub signup_token: String,
}

impl VerifyAgentSignupRequest {
    pub fn new(signup_token: String) -> VerifyAgentSignupRequest {
        VerifyAgentSignupRequest {
            code: None,
            username: None,
            signup_token,
        }
    }
}

