//
// CreateMailbox201Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateMailbox201Response: Codable, JSONEncodable, Hashable {

    public var data: CreateMailbox201ResponseData
    public var success: Bool

    public init(data: CreateMailbox201ResponseData, success: Bool) {
        self.data = data
        self.success = success
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case data
        case success
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(data, forKey: .data)
        try container.encode(success, forKey: .success)
    }
}

