//
// EmailPagination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmailPagination: Codable, JSONEncodable, Hashable {

    public static let limitRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public var limit: Int
    public var hasMore: Bool
    public var nextCursor: String

    public init(limit: Int, hasMore: Bool, nextCursor: String) {
        self.limit = limit
        self.hasMore = hasMore
        self.nextCursor = nextCursor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case hasMore = "has_more"
        case nextCursor = "next_cursor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limit, forKey: .limit)
        try container.encode(hasMore, forKey: .hasMore)
        try container.encode(nextCursor, forKey: .nextCursor)
    }
}

