//
// EmailAttachment.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmailAttachment: Codable, JSONEncodable, Hashable {

    public enum Origin: String, Codable, CaseIterable {
        case original = "original"
        case forwarder = "forwarder"
        case forwardedMessage = "forwarded_message"
        case unspecified = "unspecified"
    }
    public static let idRule = StringRule(minLength: nil, maxLength: nil, pattern: "/^df_/")
    public static let sizeBytesRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var id: String
    public var filename: String
    public var contentType: String?
    public var sizeBytes: Int64
    /** Present only with include_storage=true. */
    public var versionId: String?
    /** For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin. */
    public var origin: Origin?

    public init(id: String, filename: String, contentType: String?, sizeBytes: Int64, versionId: String? = nil, origin: Origin? = nil) {
        self.id = id
        self.filename = filename
        self.contentType = contentType
        self.sizeBytes = sizeBytes
        self.versionId = versionId
        self.origin = origin
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case filename
        case contentType = "content_type"
        case sizeBytes = "size_bytes"
        case versionId = "version_id"
        case origin
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(filename, forKey: .filename)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(sizeBytes, forKey: .sizeBytes)
        try container.encodeIfPresent(versionId, forKey: .versionId)
        try container.encodeIfPresent(origin, forKey: .origin)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension EmailAttachment: Identifiable {}
