//
// EmailDomainCheckResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct EmailDomainCheckResponse: Codable, JSONEncodable, Hashable {

    public var success: Bool
    public var data: EmailDomainCheck

    public init(success: Bool, data: EmailDomainCheck) {
        self.success = success
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case success
        case data
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(success, forKey: .success)
        try container.encode(data, forKey: .data)
    }
}

