//
// MailboxCreateOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MailboxCreateOptions: Codable, JSONEncodable, Hashable {

    public var description: String?
    public var metadata: [String: AnyCodable]?
    public var tagIds: [String]?
    public var tagPaths: [String]?
    public var email: MailboxEmailOptions?

    public init(description: String? = nil, metadata: [String: AnyCodable]? = nil, tagIds: [String]? = nil, tagPaths: [String]? = nil, email: MailboxEmailOptions? = nil) {
        self.description = description
        self.metadata = metadata
        self.tagIds = tagIds
        self.tagPaths = tagPaths
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case metadata
        case tagIds = "tag_ids"
        case tagPaths = "tag_paths"
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(tagIds, forKey: .tagIds)
        try container.encodeIfPresent(tagPaths, forKey: .tagPaths)
        try container.encodeIfPresent(email, forKey: .email)
    }
}

