//
// MailboxLockLockedByApiKey.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MailboxLockLockedByApiKey: Codable, JSONEncodable, Hashable {

    public var id: String?
    public var label: String?
    public var tokenType: String?

    public init(id: String? = nil, label: String? = nil, tokenType: String? = nil) {
        self.id = id
        self.label = label
        self.tokenType = tokenType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case label
        case tokenType = "token_type"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(tokenType, forKey: .tokenType)
    }
}


@available(iOS 13, tvOS 13, watchOS 6, macOS 10.15, *)
extension MailboxLockLockedByApiKey: Identifiable {}
