//
// PrepareFileUploadRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PrepareFileUploadRequest: Codable, JSONEncodable, Hashable {

    public var mailboxId: String
    public var accountId: String?
    public var path: String
    public var blob: UploadBlob

    public init(mailboxId: String, accountId: String? = nil, path: String, blob: UploadBlob) {
        self.mailboxId = mailboxId
        self.accountId = accountId
        self.path = path
        self.blob = blob
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case mailboxId = "mailbox_id"
        case accountId = "account_id"
        case path
        case blob
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(mailboxId, forKey: .mailboxId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encode(path, forKey: .path)
        try container.encode(blob, forKey: .blob)
    }
}

