//
// SaveUploadedFileRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SaveUploadedFileRequest: Codable, JSONEncodable, Hashable {

    public static let reasonRule = StringRule(minLength: nil, maxLength: 2000, pattern: nil)
    public var path: String
    public var signedBlobId: String
    public var accountId: String?
    public var expectedMailboxRevisionId: String?
    /** Optional purpose for this action. AI agents should explain intentional reads and changes when known; omit when unknown. Do not include secrets, file contents, or transcripts. */
    public var reason: String?

    public init(path: String, signedBlobId: String, accountId: String? = nil, expectedMailboxRevisionId: String? = nil, reason: String? = nil) {
        self.path = path
        self.signedBlobId = signedBlobId
        self.accountId = accountId
        self.expectedMailboxRevisionId = expectedMailboxRevisionId
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case path
        case signedBlobId = "signed_blob_id"
        case accountId = "account_id"
        case expectedMailboxRevisionId = "expected_mailbox_revision_id"
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        try container.encode(signedBlobId, forKey: .signedBlobId)
        try container.encodeIfPresent(accountId, forKey: .accountId)
        try container.encodeIfPresent(expectedMailboxRevisionId, forKey: .expectedMailboxRevisionId)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

