//
// SignupResult.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** First verification returns api_key, account and mailbox. Repeated verification returns completed IDs and recovery_url without the key. */
public struct SignupResult: Codable, JSONEncodable, Hashable {

    public enum Scope: String, Codable, CaseIterable {
        case mailboxAdmin = "mailbox_admin"
    }
    public var signup: SignupStatus
    /** Returned once; store privately. Never write to logs or chat. */
    public var apiKey: String?
    public var scope: Scope?
    public var expiresAt: Date?
    public var account: SignupAccount?
    public var mailbox: SignupMailbox?
    public var recoveryUrl: String?

    public init(signup: SignupStatus, apiKey: String? = nil, scope: Scope? = nil, expiresAt: Date? = nil, account: SignupAccount? = nil, mailbox: SignupMailbox? = nil, recoveryUrl: String? = nil) {
        self.signup = signup
        self.apiKey = apiKey
        self.scope = scope
        self.expiresAt = expiresAt
        self.account = account
        self.mailbox = mailbox
        self.recoveryUrl = recoveryUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case signup
        case apiKey = "api_key"
        case scope
        case expiresAt = "expires_at"
        case account
        case mailbox
        case recoveryUrl = "recovery_url"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(signup, forKey: .signup)
        try container.encodeIfPresent(apiKey, forKey: .apiKey)
        try container.encodeIfPresent(scope, forKey: .scope)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(account, forKey: .account)
        try container.encodeIfPresent(mailbox, forKey: .mailbox)
        try container.encodeIfPresent(recoveryUrl, forKey: .recoveryUrl)
    }
}

