//
// StorageUpload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct StorageUpload: Codable, JSONEncodable, Hashable {

    public var url: String
    public var headers: [String: String]

    public init(url: String, headers: [String: String]) {
        self.url = url
        self.headers = headers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case headers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(headers, forKey: .headers)
    }
}

