//
// UpdateMailboxEmailAllowlistRequestSenderAllowlist.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateMailboxEmailAllowlistRequestSenderAllowlist: Codable, JSONEncodable, Hashable {

    public static let entriesRule = ArrayRule(minItems: nil, maxItems: 500, uniqueItems: false)
    public var enabled: Bool
    public var entries: [String]

    public init(enabled: Bool, entries: [String]) {
        self.enabled = enabled
        self.entries = entries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case entries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(enabled, forKey: .enabled)
        try container.encode(entries, forKey: .entries)
    }
}

