=begin
#Revdoku public agent API

#Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

The version of the OpenAPI document: 2.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module RevdokuApi
  class DecodedIncomingMessageAttachmentsInner < ApiModelBase
    # Relative to message folder.
    attr_accessor :path

    attr_accessor :original_filename

    attr_accessor :content_type

    attr_accessor :size_bytes

    # For normalized forwards: inner attachment, member addition, attached source EML, or unknown inline-forward origin.
    attr_accessor :origin

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'path' => :'path',
        :'original_filename' => :'original_filename',
        :'content_type' => :'content_type',
        :'size_bytes' => :'size_bytes',
        :'origin' => :'origin'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'path' => :'String',
        :'original_filename' => :'String',
        :'content_type' => :'String',
        :'size_bytes' => :'Integer',
        :'origin' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RevdokuApi::DecodedIncomingMessageAttachmentsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RevdokuApi::DecodedIncomingMessageAttachmentsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      else
        self.path = nil
      end

      if attributes.key?(:'original_filename')
        self.original_filename = attributes[:'original_filename']
      else
        self.original_filename = nil
      end

      if attributes.key?(:'content_type')
        self.content_type = attributes[:'content_type']
      else
        self.content_type = nil
      end

      if attributes.key?(:'size_bytes')
        self.size_bytes = attributes[:'size_bytes']
      else
        self.size_bytes = nil
      end

      if attributes.key?(:'origin')
        self.origin = attributes[:'origin']
      end
    end

    # Custom attribute writer method with validation
    # @param [Object] path Value to be assigned
    def path=(path)
      if path.nil?
        fail ArgumentError, 'path cannot be nil'
      end

      @path = path
    end

    # Custom attribute writer method with validation
    # @param [Object] original_filename Value to be assigned
    def original_filename=(original_filename)
      if original_filename.nil?
        fail ArgumentError, 'original_filename cannot be nil'
      end

      @original_filename = original_filename
    end

    # Custom attribute writer method with validation
    # @param [Object] content_type Value to be assigned
    def content_type=(content_type)
      if content_type.nil?
        fail ArgumentError, 'content_type cannot be nil'
      end

      @content_type = content_type
    end

    # Custom attribute writer method with validation
    # @param [Object] size_bytes Value to be assigned
    def size_bytes=(size_bytes)
      if size_bytes.nil?
        fail ArgumentError, 'size_bytes cannot be nil'
      end

      if size_bytes < 0
        fail ArgumentError, 'invalid value for "size_bytes", must be greater than or equal to 0.'
      end

      @size_bytes = size_bytes
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] origin Object to be assigned
    def origin=(origin)
      validator = EnumAttributeValidator.new('String', ["original", "forwarder", "forwarded_message", "unspecified"])
      unless validator.valid?(origin)
        fail ArgumentError, "invalid value for \"origin\", must be one of #{validator.allowable_values}."
      end
      @origin = origin
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          path == o.path &&
          original_filename == o.original_filename &&
          content_type == o.content_type &&
          size_bytes == o.size_bytes &&
          origin == o.origin
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [path, original_filename, content_type, size_bytes, origin].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
