=begin
#Revdoku public agent API

#Email mailboxes for people and AI agents, with private file storage. Create mailboxes, read messages and attachments, and store additional files. Direct API signup requires verification of the human operator email. This document covers selected endpoints; see https://revdoku.com/api.md for the complete API.

The version of the OpenAPI document: 2.0.1

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module RevdokuApi
  # Authorized mailbox reads include the email address. Creation and opt-in reads also include receiving settings; use the emails collection for a durable arrival cursor.
  class MailboxEmail < ApiModelBase
    attr_accessor :address

    attr_accessor :received_count

    attr_accessor :last_received_at

    # Latest message folder with trailing slash; null before receipt. May become stale after manual file moves/deletion.
    attr_accessor :last_received_path

    # Why receiving is unavailable; omitted when receiving_enabled is true.
    attr_accessor :blocked_reason

    attr_accessor :available_domains

    attr_accessor :assignment

    attr_accessor :customization

    # Whether this mailbox can currently receive email. False when configuration, account state, quota or routing prevents receiving.
    attr_accessor :receiving_enabled

    attr_accessor :sender_allowlist

    attr_accessor :username

    # Always false. Sending is not implemented.
    attr_accessor :sending_enabled

    attr_accessor :aliases

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'address' => :'address',
        :'received_count' => :'received_count',
        :'last_received_at' => :'last_received_at',
        :'last_received_path' => :'last_received_path',
        :'blocked_reason' => :'blocked_reason',
        :'available_domains' => :'available_domains',
        :'assignment' => :'assignment',
        :'customization' => :'customization',
        :'receiving_enabled' => :'receiving_enabled',
        :'sender_allowlist' => :'sender_allowlist',
        :'username' => :'username',
        :'sending_enabled' => :'sending_enabled',
        :'aliases' => :'aliases'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'address' => :'String',
        :'received_count' => :'Integer',
        :'last_received_at' => :'Time',
        :'last_received_path' => :'String',
        :'blocked_reason' => :'String',
        :'available_domains' => :'Array<MailboxEmailAvailableDomainsInner>',
        :'assignment' => :'MailboxEmailAssignment',
        :'customization' => :'MailboxEmailCustomization',
        :'receiving_enabled' => :'Boolean',
        :'sender_allowlist' => :'EmailSenderAllowlist',
        :'username' => :'String',
        :'sending_enabled' => :'Boolean',
        :'aliases' => :'Array<MailboxEmailAliasesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'address',
        :'last_received_at',
        :'last_received_path',
        :'blocked_reason',
        :'username',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RevdokuApi::MailboxEmail` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RevdokuApi::MailboxEmail`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'address')
        self.address = attributes[:'address']
      end

      if attributes.key?(:'received_count')
        self.received_count = attributes[:'received_count']
      end

      if attributes.key?(:'last_received_at')
        self.last_received_at = attributes[:'last_received_at']
      end

      if attributes.key?(:'last_received_path')
        self.last_received_path = attributes[:'last_received_path']
      end

      if attributes.key?(:'blocked_reason')
        self.blocked_reason = attributes[:'blocked_reason']
      end

      if attributes.key?(:'available_domains')
        if (value = attributes[:'available_domains']).is_a?(Array)
          self.available_domains = value
        end
      end

      if attributes.key?(:'assignment')
        self.assignment = attributes[:'assignment']
      end

      if attributes.key?(:'customization')
        self.customization = attributes[:'customization']
      end

      if attributes.key?(:'receiving_enabled')
        self.receiving_enabled = attributes[:'receiving_enabled']
      end

      if attributes.key?(:'sender_allowlist')
        self.sender_allowlist = attributes[:'sender_allowlist']
      end

      if attributes.key?(:'username')
        self.username = attributes[:'username']
      end

      if attributes.key?(:'sending_enabled')
        self.sending_enabled = attributes[:'sending_enabled']
      end

      if attributes.key?(:'aliases')
        if (value = attributes[:'aliases']).is_a?(Array)
          self.aliases = value
        end
      end
    end

    # Custom attribute writer method with validation
    # @param [Object] received_count Value to be assigned
    def received_count=(received_count)
      if received_count.nil?
        fail ArgumentError, 'received_count cannot be nil'
      end

      if received_count < 0
        fail ArgumentError, 'invalid value for "received_count", must be greater than or equal to 0.'
      end

      @received_count = received_count
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          address == o.address &&
          received_count == o.received_count &&
          last_received_at == o.last_received_at &&
          last_received_path == o.last_received_path &&
          blocked_reason == o.blocked_reason &&
          available_domains == o.available_domains &&
          assignment == o.assignment &&
          customization == o.customization &&
          receiving_enabled == o.receiving_enabled &&
          sender_allowlist == o.sender_allowlist &&
          username == o.username &&
          sending_enabled == o.sending_enabled &&
          aliases == o.aliases
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [address, received_count, last_received_at, last_received_path, blocked_reason, available_domains, assignment, customization, receiving_enabled, sender_allowlist, username, sending_enabled, aliases].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
